### ISSUE TITLE
Fatal error: Class 'Aws\S3\Sync\UploadSyncBuilder' not found

### ISSUE THREAD

**Issue by korrio** [humanmade/S3-Uploads#100]
this happen when i type 
wp s3-uploads upload-directory videos --allow-root

**Comment by PierreLvx** [comment]
Same issue here, with the following :

`wp s3-uploads upload-directory ./wp-content/uploads/media/file/diapo/ s3://REDACTED/uploads/media/file/diapo/`

FWIW, `php -v` gives :

```
PHP 5.6.25-2+deb.sury.org~xenial+1 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by joehoyle** [comment]
Hmm interesting, are either of you using the aws-sdk elsewhere in your codebases and therefor have an additional copy?

**Comment by PierreLvx** [comment]
Negative

**Comment by elvismdev** [comment]
Same problem here, I just cloned this repo and started to upload all my /wp-content/uploads folder. But when trying the `upload-directory` command to upload subdirectories within this one I get the same error.

```
Fatal error: Class 'Aws\S3\Sync\UploadSyncBuilder' not found
```

**Comment by jakejackson1** [comment]
[Since there isn't even a class called `UploadSyncBuilder` in this plugin](https://github.com/humanmade/S3-Uploads/search?utf8=%E2%9C%93&q=UploadSyncBuilder) it seems like `extends Aws\S3\Sync\UploadSyncBuilder` should be removed permanently.

**Comment by KyleAtDND** [comment]
Please merge the commit to fix ;)

**Comment by albertosoho** [comment]
Same issue here migrate-attachments works fine, but upload-directory throws 

> Fatal error: Class 'Aws\S3\Sync\UploadSyncBuilder' not found

**Comment by mclucario** [comment]
Is this ever gonna get updated?

**Comment by mclucario** [comment]
A temporary fix for composer users

`    "repositories": {
        "s3-uploads": {
            "type": "vcs",
            "url": "https://github.com/mclucario/S3-Uploads"
        }
    },
    "require": {
        "mclucario/S3-Uploads": "^2.0"
    },`

**Comment by rmccue** [comment]
@joehoyle Did we ever fix this?

**Comment by mclucario** [comment]
Im using composer and added the repo as a source for my project. Composer automatically uses version 2.0 of the project if that helps in any way. I think all you gotta do is merge the pull request of @pramanikshreya

**Comment by dingo-d** [comment]
Nope, you didn't ;) My plugin stopped working and I got the same error as the above. The aws-sdk-php v3 doesn't have Aws\S3\Sync\UploadSyncBuilder class. They changed the entire namespace substantially.

I can remove or comment out that line, but will this break the plugin functionality? I haven't looked that in depth in it.

**Comment by Arrig0** [comment]
I confirm,  It doesn't break.

**Comment by carl-alberto** [comment]
Seems modifying: S3-Uploads/inc/class-s3-uploads-uploadsyncbuilder.php Line 3

from 

`class S3_Uploads_UploadSyncBuilder extends Aws\S3\Sync\UploadSyncBuilder {`

to

`//class S3_Uploads_UploadSyncBuilder {`

works but not sure if this is a long term solution..

**Comment by radd2004** [comment]
Any update on this?  look like there is an outstanding [pull request](https://github.com/humanmade/S3-Uploads/pull/147)

**Comment by Ciul** [comment]
Please merge this.

**Comment by craigpearson** [comment]
Any chance of getting an update on this being merged @joehoyle? Any noise would be appreciated

**Comment by joehoyle** [comment]
This will be fixed by https://github.com/humanmade/S3-Uploads/pull/293/files, you should be able to use that branch as a temporary solution.
