### ISSUE TITLE
Multisite Network Support?

### ISSUE THREAD

**Issue by christianduncan** [humanmade/S3-Uploads#105]
Curious if there's a way I can use this plugin in a WP network environment, with the AWS constants set on a per-site basis? The network uses domain mapping, and I use cloudfront cnames for each site on the network ( `cdn.site1.com, cdn.site2.com` ). 

Any ideas? Love the plugin, really hoping we can get this working!!

C

**Comment by foalford** [comment]
There is a little patch for enabling this. https://github.com/nayankira/S3-Uploads

**Comment by joehoyle** [comment]
@christianduncan this _should_ be possible to do via the `s3_uploads_putObject_params` filter and the `s3_uploads_bucket_url` filter to adjust them to match the current site.
