### ISSUE TITLE
URL rewrites

### ISSUE THREAD

**Issue by andrew40** [humanmade/S3-Uploads#106]
Whilst uploading all the old images to S3 and then optionally delete them, does this plugin subsequently then rewrite the urls in the past posts for the images used?

**Comment by joehoyle** [comment]
@andrew40 it doest directly, however after performing the upload step for migration (noted here https://github.com/humanmade/S3-Uploads#uploading-files-to-s3) it will give you a CLI command to run to do a search-replace on your database.
