### ISSUE TITLE
Unable to create directory uploads/2016/06. Is its parent directory writable by the server

### ISSUE THREAD

**Issue by pojke** [humanmade/S3-Uploads#107]
Leaving here just for SEO and troubleshooting. The plugin works great guys thanks for that!

After playing with SDK I came down to this error from SDK itself:

**Unable to find the wrapper "s3" - did you forget to enable it when you configured PHP?** 

Above error (after wasted 3h of my life) is caused by PHP setting allow_url_fopen = off.
You need to make sure that you change it and reboot nginx / apache2 otherwise you won't be able to upload files to S3.

**Comment by joehoyle** [comment]
Thanks!
