### ISSUE TITLE
new images are not uploaded

### ISSUE THREAD

**Issue by jabawack81** [humanmade/S3-Uploads#108]
Hi I've installed the stable version of the plugin and even if I can move all the upload folder to the bucket, when I upload a new file this is loaded in the server and not in the bucket,

My situation:
Wordpress: 4.5.3
S3-upload: 1.1.0 (cloned and checked out to the commit 9cb7652)

to be sure to test everything I've added `define('S3_UPLOADS_AUTOENABLE', true);` to my `wp-config.php` and I'm sure is activate because in the `wp_options` table I have a row with:

option_name: s3_uploads_enabled,
option_value: enabled
autoload: yes

I'm missing something?

**Comment by tylershuster** [comment]
Experiencing this as well.
