### ISSUE TITLE
Add dns-prefetch link into header

### ISSUE THREAD

**Issue by spacedmonkey** [humanmade/S3-Uploads#110]
To help performance, you could add a link reference in header to prefetch dns for s3 domain url. In WordPress this would be pretty simple in 4.6 with the new filter. 

``` php

function s3_resource_hints( $hints, $relation_type ) {
    if ( 'dns-prefetch' === $relation_type ) {
        $hints[] = $this->get_s3_url();
    } 

    return $hints;
}

add_filter( 'wp_resource_hints', 's3_resource_hints', 10, 2 );
```

**Comment by joehoyle** [comment]
This could be good, however not sure if it would always want adding, as you might not have any uploads images on all pages, in which case it's a waster prefetch.

**Comment by rmccue** [comment]
@peterwilsoncc Curious: do you have any thoughts on this?

**Comment by peterwilsoncc** [comment]
I'd add a crossorigin preconnect for preference if there is an image in `$wp_query->post->post_content` as the first post:

* is early on the page on an index
* part of the content the user is after on a singular page

No strong feelings on always adding a `dns-prefetch`, they're quick requests but images are non blocking.

**Comment by rmccue** [comment]
So, roughly: get first post, if it contains `src="{bucket_url}`, add `dns-prefetch`?

**Comment by rmccue** [comment]
(It's about the same amount of work to check all posts in the query, so I'd suggest we do that rather than special-casing the first.)

**Comment by spacedmonkey** [comment]
There are lots of examples where you could have image in the page not in
the content like.

- No image in content, but featured image is echoed in theme
- Header image in theme
- Site logo displayed
- Images displayed in widget area, i.e. Image widget in jet pack

I know we are heading forwards an image lighter web with icon fonts etc,
but there are few pages on the sites I make / use there are really no
images on the page at all. Maybe on a 404 or something, but for 99% of
page, there will be a at least one image. I think the pay off, for
imageless pages compared to the benefit, I think it worth to have the
prefetch. If people don't like it, they can easier filter it again and
remove it.

On 8 Jan 2017, at 20:15, Ryan McCue <notifications@github.com> wrote:

(It's about the same amount of work to check all posts in the query, so I'd
suggest we do that rather than special-casing the first.)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/humanmade/S3-Uploads/issues/110#issuecomment-271196273>,
or mute the thread

**Comment by rmccue** [comment]
I tend to agree, adding it statically doesn't really cost us much AFAIK. @peterwilsoncc Think that'd be OK?

**Comment by spacedmonkey** [comment]
I personally do not think it is so much overhead to prefetch DNS compared the benefits. 

I have created #209 as a talking point.

**Comment by joehoyle** [comment]
Hmm another use case here (which affects us). We don't actually use the S3 Bucket url, as Tachyon replaces all of these. Though `wp_upload_dir()['baseurl']` is `s3.amazonaws.com` or whatever, Tachyon rewrites image URLs to be `eu-west-1.tchyn.io`, but it's not done the wp_upload_dir hooks (for several reasons). I think we might be an unusual case here, so I'm going to roll with #209
