### ISSUE TITLE
where should i clone this repo?

### ISSUE THREAD

**Issue by amitrahav** [humanmade/S3-Uploads#112]
is it a wp plugin and should clone into /wp-content/plugins ?
or wp-cli package and should clone into .wp-cli/packages ?

when i tried clone it in to /wp-content/plugins it appears as wp plugin at wp plugin list, but on trying to 
`wp plugin activate S3-Uploads-master` it returns `Parse error: syntax error, unexpected '$value' (T_VARIABLE) in /home/amit/photos/wp-content/plugins/S3-Uploads-master/lib/aws-sdk/Aws/functions.php on line 36`

when tried clone it into .wp-cli/packages it dosent appears as a wp-cli package on `wp package list`

**Comment by rmccue** [comment]
Make sure you're using PHP 5.4 or newer. It needs to be installed as a plugin on the site.

**Comment by amitrahav** [comment]
hey, i'm using php 5.4.46
yet - got this error when trying to activate plugin

```
X@Y:~/photos$ wp plugin list
+--------------------------+----------+--------+-------------+
| name                     | status   | update | version     |
+--------------------------+----------+--------+-------------+
| akismet                  | inactive | none   | 3.1.11      |
| amazon-web-services      | inactive | none   | 0.3.6       |
| hello                    | inactive | none   | 1.6         |
| S3-Uploads               | inactive | none   | 2.0.0-beta1 |
| amazon-s3-and-cloudfront | inactive | none   | 1.0.4       |
+--------------------------+----------+--------+-------------+
X@Y:~/photos$ wp plugin activate S3-Uploads
Parse error: syntax error, unexpected '$value' (T_VARIABLE) in /home/amit/photos/wp-content/plugins/S3-Uploads/lib/aws-sdk/Aws/functions.php on line 36
X@Y:~/photos$ php -v
PHP 5.4.46-dev (cli) (built: Jun 18 2016 16:47:05) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

```

**Comment by danielbachhuber** [comment]
@amitrahav Can you share `wp --info` ? WP-CLI may be using a different PHP binary than `php`.

**Comment by amitrahav** [comment]
nope:
```
PHP binary:	/opt/php-5.4/bin/php
PHP version:	5.4.46-dev
php.ini used:	
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	/home/amit/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.23.1

```

**Comment by joehoyle** [comment]
I think actually the version 3 of the AWS SDK requires PHP 5.5+, sorry about that! Given we really want to use the latest SDK, I don't know of an easy way around this.

Both 5.4 and PHP 5.5 are unsupported versions of PHP, I'd recommend upgrading to 5.6
