### ISSUE TITLE
Failed to moved  to S3 on migrate-attachments

### ISSUE THREAD

**Issue by amitrahav** [humanmade/S3-Uploads#113]
hey, error on `wp s3-uploads migrate-attachments`:

`Failed to moved  to S3
PHP Warning:  copy(): The first argument to copy() function cannot be a directory in /home/amit/oldnoalphotoswp/wp-content/plugins/S3-Uploads/inc/class-s3-uploads-wp-cli-command.php on line 121
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/wp:0
PHP   2. include() /usr/local/bin/wp:4
PHP   3. include() phar:///usr/local/bin/wp/php/boot-phar.php:5
PHP   4. WP_CLI\Runner->start() phar:///usr/local/bin/wp/php/wp-cli.php:21
PHP   5. WP_CLI\Runner->_run_command() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:757
PHP   6. WP_CLI\Runner->run_command() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:334
PHP   7. WP_CLI\Dispatcher\Subcommand->invoke() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:327
PHP   8. call_user_func:{phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:351}() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:351
PHP   9. WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:351
PHP  10. call_user_func:{phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:67}() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:67
PHP  11. S3_Uploads_WP_CLI_Command->migrate_attachments_to_s3() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:67
PHP  12. S3_Uploads_WP_CLI_Command->migrate_attachment_to_s3() /home/amit/oldnoalphotoswp/wp-content/plugins/S3-Uploads/inc/class-s3-uploads-wp-cli-command.php:72
PHP  13. copy() /home/amit/oldnoalphotoswp/wp-content/plugins/S3-Uploads/inc/class-s3-uploads-wp-cli-command.php:121
`

php v : 5.6.2
wp cli v: 0.23.1

**Comment by joehoyle** [comment]
@amitrahav thanks for the report, `migrate-attachments` is somewhat old and deprecated now, the recommended solution is to use https://github.com/humanmade/S3-Uploads#uploading-files-to-s3 with the `upload-director` command.
