### ISSUE TITLE
Anyway to pass Content-Encoding headers?

### ISSUE THREAD

**Issue by conwaydev** [humanmade/S3-Uploads#114]
So I'm trying to upload svgz file types, but in order to serve svgz they have to be gzipped. 

File uploaded through WP media library and uploaded with S3 Uploads: https://media.sproutsocial.com/uploads/customer-logo-marquette.svgz
File uploaded directly to S3 from Transmit with these headers* set: https://media.sproutsocial.com/uploads/customer-logo-marquette-great.svgz

*:
<img width="508" alt="screen shot 2016-08-04 at 10 27 41 am" src="https://cloud.githubusercontent.com/assets/1868805/17407719/fd8a5eb8-5a2d-11e6-85dd-a8f466cde817.png">

Is there any way to mimic these custom upload headers with the plugin?

**Comment by joehoyle** [comment]
Hmm I'm not sure - does this work uploading `.svgz` files to `wp-uploads` without the S3 Uploads plugin (normal WordPress)? Or is this specifically because you can't serve files gzipped from S3 on the fly?

**Comment by conwaydev** [comment]
Hey I'm going to close this as its not really a bug with your plugin, sorry thanks!
