### ISSUE TITLE
Loading S3-Uploads constants from environmental variables

### ISSUE THREAD

**Issue by NathanKleekamp** [humanmade/S3-Uploads#121]
In order to commit our wp-config.php file to a public git repo, we use environment variables instead of strings when defining constants. like so:

```php
define('DB_NAME', getenv('DB_NAME'));
```

This doesn't appear to work, though, when setting the S3-Uploads constants similarly:

```php
define('S3_UPLOADS_BUCKET', getenv('S3_UPLOADS_BUCKET'));
define('S3_UPLOADS_KEY',    getenv('S3_UPLOADS_KEY'));
define('S3_UPLOADS_SECRET', getenv('S3_UPLOADS_SECRET'));
define('S3_UPLOADS_REGION', getenv('S3_UPLOADS_REGION'));
```
And trying to run any of the wp-cli related commands. Is this something where we'll have to set them to the strings, run wp-cli commands, and then switch back to defining from environment variables or is there another way to accomplish this?

Thanks,
Nathan

*edited

**Comment by joehoyle** [comment]
Hmm I really don't understand why this would not work, unless somehow these env vars are not set when in wp cli. What happens if you do:

```
wp shell
> S3_UPLOADS_BUCKET
```

And

```
wp shell
> getenv('S3_UPLOADS_BUCKET')
```

**Comment by NathanKleekamp** [comment]
OK, I've just set these values as environment variables in Bash via the command line, and it's working fine today. I tried the same thing yesterday, but I clearly must have mistyped something. This appears to be user error on my part. Thanks for such a great pluign!

Ultimately I ran something like the following in case is useful to anyone else:

```bash
WP_DB_NAME='wordpress' WP_DB_USER='wordpress' WP_DB_PASSWORD='wordpress' WP_DB_HOST='localhost' WP_S3_UPLOADS_BUCKET='bucketname' WP_S3_UPLOADS_KEY='key' WP_S3_UPLOADS_SECRET='secret' WP_S3_UPLOADS_REGION='region' /usr/local/bin/wp --path='/path/to/wp' --url='http://wordpress.dev' s3-uploads verify
```

**Comment by joehoyle** [comment]
Good to hear!

**Comment by enys** [comment]
Strangely Had the same issue today.
Env vars are defined.
` s3-uploads verify` works,
But then it fails via the WP web ui.
Hardcoding the values works fine. As if it was not able to get env vars at runtime.

**Comment by rmccue** [comment]
This sounds like you have a difference in your configuration between php-fpm and php-cli

**Comment by enys** [comment]
You are correct, I traced this back down to "clear_env" defaulted to yes in php-fpm, and set to yes on most official docker images for wordpress.
