### ISSUE TITLE
Double definition of Guzzle class

### ISSUE THREAD

**Issue by jpresley23** [humanmade/S3-Uploads#129]
I tried v2.0.0-beta2 and found this error.
`Fatal error: Cannot redeclare GuzzleHttp\uri_template() (previously declared in /var/www/vendor/guzzlehttp/guzzle/src/functions.php:18) in /var/www/httpdocs/wp-content/plugins/s3-uploads/lib/aws-sdk/GuzzleHttp/functions.php on line 18`

We are a composer project which already has Guzzle as a dependency in our project.

**Comment by joehoyle** [comment]
Hmm interesting, this is probably because functions can not be autoloaded, so guzzle just includes them regardless of if they already exist. However, it's possible there would be other compatibility issues with running s3-uploads using your copy form composer due to versions. 

As a temporary workaround, you could remove the vender directory in s3-uploads and add the aws-sdk to main composer deps.

**Comment by jpresley23** [comment]
That doesn't really work for us since S3-Uploads is also a composer dependency for us. Is there a way to test whether Guzzle is already loaded before including the vendor directory? Unfortunately this goes to the problem that WordPress doesn't have a real dependency manager for third party libraries.

**Comment by brunolanevik** [comment]
@jpresley23 The only way to fix this is for you to fork the project and remove the guzzle library and add it as a composer dependency. Thats the only solution that worked for me

**Comment by ArondeParon** [comment]
Having the same problem here. Would love to hear if there is a more elegant solution to this problem, since we're handling everything through Composer.

**Comment by rmccue** [comment]
As of #172 `aws/aws-sdk-php` is included via Composer for people using Composer, which should sort out the dependencies here.

**Comment by tillkruss** [comment]
@rmccue: Could you release a new beta version, so I don't have to run `dev-master`?

**Comment by rmccue** [comment]
cc @joehoyle ^

**Comment by spacedmonkey** [comment]
Can you just load the AWS sdk in composer. This would mean that guzzle and AWS sdk will be autoloaded outside the project.

**Comment by rmccue** [comment]
@spacedmonkey Before #172 that wasn't possible; we just need a new tag for the changes including that. :)

@tillkruss #224 for the tagging. :)
