### ISSUE TITLE
migrate-attachments not working on multisite wordpress

### ISSUE THREAD

**Issue by koleror** [humanmade/S3-Uploads#130]
When using a multisite wordpress, the upload folder structure is different :

```
uploads/sites/<site_id>/<year>/...
```

Instead of :

```
uploads/<year>/...
```

Any way to make it working?

Newly added media are also uploaded locally instead of S3 probably for the same reason

**Comment by mcrowson** [comment]
I'm working on a similar issue and am setting the UPLOADS setting. 

https://codex.wordpress.org/Editing_wp-config.php#Moving_uploads_folder

so in your wp-config.php

define( 'UPLOADS', 'wp-content/sites/' . $site_id );

You'd have to figure out the site ID prior to that obviously

**Comment by allurewebsolutions** [comment]
Did anyone find a global solution to this?

**Comment by daohoangson** [comment]
This seems to work as of today. I used `--url='http://site.wordpress.domain'`.

**Comment by allurewebsolutions** [comment]
@daohoangson Can you please elaborate on how you used that? Where did you place that code?

**Comment by joehoyle** [comment]
`migrate-attachments` is a per-site level operation, so you need to run WP CLI in the context of the site you want to migrate to s3. That's where `--url='http://site.wordpress.domain` comes in, as a CLI command option.

However, I'd recommend against the use of `migrate-attachments` and instead use `wp s3-uploads upload-directory` to just upload the whole uploads directory (including all the sites) to s3. We'll likely remove `migrate-attachments` at some point as it's not necessary.

**Comment by stjo15** [comment]
When running this command on a multisite :
`wp s3-uploads upload-directory ./uploads/sites/4 s3://toplady-media/uploads/sites/4`
... I get this error:
`PHP Fatal error:  Class 'Aws\S3\Sync\UploadSyncBuilder' not found in /kunder/wallma_2716/toplad_4494/public/wp-content/plugins/S3-Uploads-master/inc/class-s3-uploads-uploadsyncbuilder.php on line 3`

**Comment by mlangone** [comment]
This is the command I use for uploading existing files in a multisite env.

`wp site list --field=url | xargs -n1 -I % wp --url=% s3-uploads upload-directory ./wp-content/uploads /uploads`

Seems to work pretty well, I did do the "hack" about adjusting the class in this issue #100 

Also there is no gui reporting so I feel like "its working" but there is not terminal notification like
"Success: Moved file revslider/concept/concept_bg2-768x432.jpg to S3"

**Comment by mattrn** [comment]
Should the automatic upload (when uploading smth with the Media Library) be working on subsites now?

When I try it, the media gets uploaded locally only like OP mentioned.
