### ISSUE TITLE
Thumbnail are not generating after activating S3-Uploads

### ISSUE THREAD

**Issue by anaspk** [humanmade/S3-Uploads#137]
I have just activated S3-Uploads plugin on my website and migrated all attachments using wp cli. Now everything else is working fine except that whenever I upload a new image, its smaller thumbnails are not generated. Original image gets uploaded to S3 just fine and wordpress uses it directly on every place, instead of the thumbnails. Thumbnails are being used for products (this is a woocommerce install) that were created before installing and activating S3-Uploads. So, it means there is no problem with the theme or wordpress itself. Registered thumbnail sizes are: 150x150, 180x180, 300x215, 300x300 and 600x429
Original dimension of a test image for which no thumbnails are generated are: 488x349

Any idea why this might be happening? How I can track down exactly what might be wrong?

**Comment by anaspk** [comment]
No worries. I fixed it by installing php-imagick on my server.

**Comment by christophwolff** [comment]
I have the same problem. Also i activated php-imagick in my docker container. 
Shouldnt the plugin upload the different images sizes to s3?

**Comment by anaspk** [comment]
Did you also restart apache?

**Comment by christophwolff** [comment]
yes.. i rebuild the docker container. I added the extension to the php.ini. maybe that works now

**Comment by anaspk** [comment]
I am not familiar with Docker but I think you will have to install php-imagick too before adding it to php.ini. So, you have to follow these steps in this order:

1. Install php-imagick using your OS's method. e.g. on Ubuntu `sudo apt-get install php-imagick`
2. Add it to php.ini if previous step didn't add automatically
3. Restart Apache.

And then it should work.

**Comment by christophwolff** [comment]
I will try this. Thank you.

**Comment by mhennessie** [comment]
I am also having this issue. Works fine when I deactivate the plugin but as soon as I activate the plugin, no smaller images or thumbnails are created. I am sure have image magick installed which is why the normal Wordpress uploads work fine. I am running this on an Amazon Linux AMI EC2 instance with PHP 7.

**Comment by mhennessie** [comment]
Turns out to be a conflict with the Wordpress theme I am using, no idea what the conflict is though.

**Comment by Jaace** [comment]
I too am having this issue and I have no idea why
