### ISSUE TITLE
Really use Composer

### ISSUE THREAD

**Issue by szepeviktor** [humanmade/S3-Uploads#142]
Please consider using Composer to replace the included aws-sdk in this repo.
https://github.com/humanmade/S3-Uploads/tree/master/lib/aws-sdk

WP.org ready ZIP-s could be uploaded to the releases.

**Comment by rmccue** [comment]
We do not use Composer internally at HM, and we don't want to make it a dependency of the project for those who also don't use it. Also, we don't publish this plugin on W.org, as we use submodules instead, so using releases wouldn't work for us.

**However**: bundling the AWS SDK with the plugin isn't a great solution, and also doesn't behave nicely when using multiple AWS-based plugins together (such as our SES plugin, etc). I think we could come up with a better solution.

Here's what I'm thinking:
* Require users of the plugin to install the SDK themselves.
* Make SDK installation really clear and easy.
  * For people who do use Composer, list the SDK as a dependency.
  * For those who don't, provide detailed instructions on installing the SDK. (Potentially, loading it automatically from a well-known location to simplify installation.)
* Adjust all our (developer-focussed) plugins to work this way.
* Detect the SDK and provide instructions if it's missing.

This would allow Composer installation if you'd like, and would additionally solve the multiple-SDK problems you can run into. It would also avoid duplication of the SDK. It does mean a higher burden on the user, however there's already a large barrier-to-entry with our AWS plugins, and it can ideally be made no more complex than installing this plugin itself.

@joehoyle Thoughts? If you're 👍, I'd be happy to tackle this in the new year.

**Comment by rmccue** [comment]
> I'd be happy to tackle this in the new year.

(Also just to note: most of HM is away over the holiday break until the 8th of Jan or so, so replies may be delayed. :) )

**Comment by szepeviktor** [comment]
I see. It is really complicated.
Duplicated libraries in WP plugins **is** a problem.

**Comment by joehoyle** [comment]
This is an issue for sure - I'd rather also not require composer for people using the plugin via GitHub. I don't really have an issue of bundling the SDK for users who don't want to manage the dependancy themselves, however maybe we can make loading it a bit smarter. What about if we had a constant to disabling S3 Uploads to require the SDK and instead relied on the user to have it loaded via autoloading or whatever other way they wanted?

**Comment by joehoyle** [comment]
Actually, I think we already do a `class_exists` check, so the bundled SDK would not already be used if a composer autoloader was used.

**Comment by szepeviktor** [comment]
> have it loaded via autoloading or whatever other way they wanted

You may release a clean AWS SDK plugin on WP.org as this one
https://wordpress.org/plugins/amazon-web-services/

**Comment by larssn** [comment]
Careful using Composer. If two different plugins, says this one and another one both decide to include the AWS SDK via their autoloader, it effectively means that two separate autoloaders will have a copy of AWS SDK. This will lead to horrible issues.

There is no clean way of using dependency management in a modular setup like Wordpress that I know of. Maybe wrapping the autoloaded namespaces in another unique namespace could work, but that would be a separate project in itself.

**Comment by rmccue** [comment]
> Careful using Composer. If two different plugins, says this one and another one both decide to include the AWS SDK via their autoloader, it effectively means that two separate autoloaders will have a copy of AWS SDK. This will lead to horrible issues.

My thinking was we simply do a `class_exists`; if it's already loaded, we skip completely.

**Comment by rmccue** [comment]
> You may release a clean AWS SDK only plugin on WP.org as this one

Also, as noted previously, we don't release on WordPress.org :)

**Comment by pdufour** [comment]
👍

**Comment by korobochkin** [comment]
Just an opinion: You can create a separated git repository which will contain all the necessary files right into repository.

**Comment by omarramadan** [comment]
Can we at least add a configuration to exclude/include the local AWS version inside the plugin? 
That way if you already have AWS SDK loaded using composer it doesn't conflict ?

**Comment by rmccue** [comment]
You should now be able to provide your own version of the AWS SDK (specifically, the `Aws\S3\S3Client` class must exist), and it will be required automatically if using Composer.

**Comment by szepeviktor** [comment]
Thanks.
