### ISSUE TITLE
Blade templating system compatibility

### ISSUE THREAD

**Issue by ChrissiQ** [humanmade/S3-Uploads#149]
Hi,

I'm not entirely sure whether the resolution of this issue should be the responsibility of the maintainers of blade (Laravel's PHP templating system) or this plugin.  I'm leaning toward this plugin, so I'm posting here first.  Please let me know if it's something that should be addressed in Blade instead.

I'm using Laravel's Blade templating system and also trying to use this plugin.  The plugin works fine when I am using a theme that does not use Blade.  However, when I am using a theme that uses blade, I get these warnings:

```
Warning: include(): s3:// wrapper is disabled in the server configuration by allow_url_include=0 in <theme_path>/vendor/illuminate/view/Engines/PhpEngine.php on line 42
Warning: include(s3://<s3_bucket>/uploads/cache/compiled/563dba826a5a3395d8776a4424541dfffd89f792.php): failed to open stream: no suitable wrapper could be found in <theme_path>/vendor/illuminate/view/Engines/PhpEngine.php on line 42
Warning: include(): Failed opening 's3://<s3_bucket>/uploads/cache/compiled/563dba826a5a3395d8776a4424541dfffd89f792.php' for inclusion (include_path='.:/usr/share/php') in <theme_path>/vendor/illuminate/view/Engines/PhpEngine.php on line 42
```

It seems that the way Blade's templating system works is by processing the template file and uploading the compiled PHP file to the media folder.  Since the media folder is on s3, PHP files are getting uploaded to my s3 bucket.  Presumably if I configured the server to `allow_url_include=1`, I may be able to execute these files.  However, I think this is probably a pretty bad idea, as it allows remote PHP execution.  I don't like that.

Is there a way to perhaps exclude a certain directory from getting sent to PHP, and allow it to be fed locally instead?  I'm not sure what the best solution is here.  Blade is a pretty common templating system, and if this plugin doesn't work with it, it seems like a solution may be at hand?

Or it's possible there is something in my server's config that I need to change.  I'm not sure.

Any advice or possible solution is appreciated.  Thanks.

**Comment by ChrissiQ** [comment]
After a bit more investigating, I found a solution.  You can change the paths config for Blade.

For future reference in case anyone else has the same problem, I'm using Sage 9.0.0-beta.2 starter theme, so for me, the config for this is in <theme_path>/src/setup.php, line 127.  Changing the existing `view.compiled` setting to `WP_CONTENT_DIR . "/uploads/cache/compiled"` seems to fix it.

Feel free to close this if you don't think there's anything more to do.  Sorry if opening this issue was kind of pointless!

**Comment by rmccue** [comment]
> It seems that the way Blade's templating system works is by processing the template file and uploading the compiled PHP file to the media folder.

This process is not supported, nor recommended. Treating files inside the uploads directory as executable by PHP is not a good idea from a security perspective.

We also don't explicitly support any templating system except WordPress' built-in templates, and it's up to third-party templating systems to ensure they work correctly with WordPress' internal systems (such as the uploads API).

**Comment by ChrissiQ** [comment]
That makes perfect sense.  Thank you.

**Comment by frenzis** [comment]
Thanks @ChrissiQ and @rmccue. Just an update: the Sage final version 9.0.0 moved the compiled file path configuration to the `<theme_path>/config/view.php` file. To ensure compatibility with S3 Uploads plugin I changed the line 32 from `'compiled' => wp_upload_dir()['basedir'].'/cache'` to `'compiled' => WP_CONTENT_DIR.'/cache'`.

**Comment by ciarans** [comment]
@frenzis thank you so much - saved me a bunch time!
