### ISSUE TITLE
Enabling the plugin via CLI 

### ISSUE THREAD

**Issue by benmay** [humanmade/S3-Uploads#15]
The docs indicate you need to run `wp s3-uploads enable` to enable the plugin, however when run, CLI returns and error `Error: 's3-uploads enable' is not a registered wp command. See 'wp help'.` and uploading didn't work or return any errors with all the usual debugging on.

**Comment by benmay** [comment]
(The plugin works - but maybe that ref in the doc can come out)

**Comment by rmccue** [comment]
I think it's meant to be `wp plugin enable s3-uploads` ?

**Comment by rmccue** [comment]
Or not, ¯\_(ツ)_/¯

**Comment by joehoyle** [comment]
Good point - I think in the past I had planned for it to be disabled until one had uploaded all existing uploads to s3, and then you could flip the "enabled" switch - but that never came to fruition, however I think this is still planned, so I'm going to leave this ticket open for that.

**Comment by benmay** [comment]
I think that would be better done via a constant so it could be deployed to production environments easier? Rather than having to run wp-cli commands on prod server(s).

In our case this week, we moved 30GB of uploads via s3cmd, then did a SQL update on the post_content to map all the urls, then simply deployed the drop in to take over from there -- so enabling wouldn't really have been beneficial - but I'm sure there are other edge cases :)
