### ISSUE TITLE
"Just works" and easing migration

### ISSUE THREAD

**Issue by jdub** [humanmade/S3-Uploads#153]
Hey gang,

It'd be nice to be able to specify the destination bucket path, particularly for CloudFront/S3 migrations. This approach might even suggest a better default.

Almost all WordPress sites expose their uploads directory via `/wp-content/uploads` when getting started on a single server.

When considering a migration to CloudFront/S3, I would prefer not to break any of those URLs. Sure, they're media files, and WordPress (with S3-Uploads) will happily munge the URLs while rendering, but links to these URLs aren't always available for filtering in the WordPress loop.

For example:

- Although it's a bit wrong, I often see themes referring to uploaded files with hard-coded links.
- Other sites, including those under control of the WordPress site operator, might link directly to those URLs.

Plus:

- Why bother filtering everything in the WordPress loop if you don't have to? It's just more work for PHP to do.

If you're just using S3, you have to replace the `<site>/wp-content/uploads` URL with an S3 link. But if you're using CloudFront, you don't have to, and ideally don't want to!

If you set up CloudFront cache behaviours properly, and your files are in the right place in S3, you can migrate to CloudFront/S3 without changing a single URL.

In CloudFormation YAML:

```yaml
DefaultCacheBehavior:
  TargetOriginId: LoadBalancer
  ...
CacheBehaviors:
  - PathPattern: /wp-content/uploads/*
     TargetOriginId: Bucket
```

The only issue is that objects in the bucket must have the key prefix `wp-content/uploads/`. Right now, they're all under `uploads/` and there's no setting to change it. What I'd like:

```php
# default:
# define('S3_UPLOADS_PREFIX', 'uploads/`);
define('S3_UPLOADS_PREFIX', 'wp-content/uploads/`);
```

(It may be better to not require the slash, or just stripslashes it.)

But then it might be worth discussing the default. 😄

**Comment by rmccue** [comment]
Rather than introducing `S3_UPLOADS_PREFIX`, can you simply change the `upload_path` and `upload_url_path` options instead? Alternatively, you may be able to define `UPLOADS`.

Internally, all S3 Uploads does is replace `WP_CONTENT_DIR` with `s3://bucket/`, so defining the option yourself should allow this flexibility.

**Comment by jdub** [comment]
Ahr, hidden options! I will have a play. Then I might send you a PR for the README. 😄

**Comment by rmccue** [comment]
Worth mentioning that these are all core WordPress options, not S3-specific :) Happy to include in the readme though.

**Comment by jdub** [comment]
OK, so:

Because S3 Uploads replaces `WP_CONTENT_DIR` with `s3://<bucket>/`, when `upload_path` is empty (by default), the eventual S3 path will begin with `s3://<bucket>/uploads`.

If I set `upload_path` or `UPLOADS` to `wp-content/uploads`, the eventual S3 path will begin with `s3://<bucket>/wp-content/uploads`.

But I probably shouldn't change `upload_url_path`, because it's going to be `<site_url>/wp-content/uploads` by default, which is what I want.

Correct?

**Comment by rmccue** [comment]
Sounds correct to me, but I'd verify if I were you :) `wp-content/uploads` is specifically special-cased in a few spots in WP core.

**Comment by jdub** [comment]
Yeah, I was wrong. Because `wp-content/uploads` is the default value of `upload_path` (when empty), it just results in the same S3 path.

So, dirty hack: Set `upload_path` to `wp-content/wp-content/uploads`, with the hope that when `WP_CONTENT_DIR` is replaced, the S3 path will be `s3://<bucket>/wp-content/uploads`.

Looks like it works. Will have to try `UPLOADS` too.

Pretty dirty hack though, telling WordPress to do something unnatural to make it behave more naturally. Would be nice if it were cleaner.

**Comment by rmccue** [comment]
The reason it needs to do that is because WP internally special-cases `'wp-content/uploads'` and assumes you screwed up, correcting it to `WP_CONTENT_DIR . '/uploads'`. For literally any other value, it uses what you've set. ¯\_(ツ)_/¯

**Comment by joehoyle** [comment]
Hmm thanks for the digging on this @jdub. I think having this issue be here for anyone that might run into this with a workaround is enough. I don't think I'm wild about trying to provide a different behavior in S3 uploads.
