### ISSUE TITLE
Double bucket name in file path

### ISSUE THREAD

**Issue by cehwitham** [humanmade/S3-Uploads#157]
I'm running the command:
`wp s3-uploads upload-directory /my-path/wp-content/uploads s3://bucket-name/uploads --sync`

Which outputs all items as:
`Transferring /my-path/wp-content/uploads/2017/01/X.jpg -> s3://bucket-name/bucket-name/uploads/2017/01/X.jpg (PutObject)`

And no files actually get written to S3.

If I run:
`wp s3-uploads upload-directory /my-path/wp-content/uploads s3://uploads --sync`

It works just fine.

Is this desired? The instructions seem to suggest you need to include the bucket name in the S3 file path?

**Comment by joehoyle** [comment]
Per https://github.com/humanmade/S3-Uploads/blob/master/inc/class-s3-uploads-wp-cli-command.php#L242, you should not inlcude the `s3://` scheme in `to`. I really don't know how that works for you!
