### ISSUE TITLE
IAM roles support instead of KEY and SECRET

### ISSUE THREAD

**Issue by gansbrest** [humanmade/S3-Uploads#159]
Hi,

I wonder if it's possible to use IAM roles instead of passing credentials? That would be much more convenient (and secure) to manage and supported by modern sdk's out of the box.

Are those constants S3_UPLOADS_KEY and S3_UPLOADS_SECRET mandatory?

Also S3_UPLOADS_REGION seem to be optional for East region, but gave me an error that it's required.

**Comment by rmccue** [comment]
Hi! You can define `S3_UPLOADS_USE_INSTANCE_PROFILE`, which will use the IAM credentials on the machine. We should document this better. :)

We always require `S3_UPLOADS_REGION`, even in us-east-1.

**Comment by gansbrest** [comment]
Set it to `define( 'S3_UPLOADS_USE_INSTANCE_PROFILE', true);` and it tries to write to local filesystem instead of s3. 

Doesnt work for me basically.

**Comment by philipowen** [comment]
@gansbrest I got this working on an EC2 instance by setting S3_UPLOADS_KEY and S3_UPLOADS_SECRET to empty and it just picked up the instance creds. I just set S3_UPLOADS_BUCKET and S3_UPLOADS_REGION.

**Comment by crmpicco** [comment]
Can anyone confirm if this works with the latest version of the plugin? I see a comment by @gansbrest above which suggests it may not work 100%. @joehoyle

**Comment by jdsrepo** [comment]
I'm getting WP 4.8.3 and 2.0.0-beta2 to core when I use this flag for IAM instance role.  Any comments?

**Comment by joehoyle** [comment]
This defintly works because we use it on all our production machines this way. See https://github.com/humanmade/S3-Uploads/blob/master/s3-uploads.php#L24 for all the checks to enable S3 Uploads though. It's possible one of these is failing, even though it's picking up the instance profile.
