### ISSUE TITLE
Files not being deleted from bucket

### ISSUE THREAD

**Issue by philipowen** [humanmade/S3-Uploads#161]
I am using WP 4.5.6 with the latest S3 plugin. If I upload a file via the UI I can see the file appear in the S3 bucket. However, deleting the file only removes it from the Media Library, it does not remove it from S3. Is this by design?

Subsequent uploads of a file with the same name get an indexed suffix to avoid conflict but this does risk leaving a lot of old files hanging around in S3. I notice that something similar is mentioned in passing on the second comment of #158 

I am not specifying S3 bucket credentials, but instead leveraging the instance credentials.

**Comment by mojowill** [comment]
Yeah this is definitely not working for me either. 

I create the upload in the WP Media area, URL is remapped and I can see the file correctly set in S3, when I delete the image though it gets removed from WP but stays in the S3 bucket.

I used the generate-iam-policy to create the IAM policy for the user in question on S3?

**Comment by philipowen** [comment]
When I noticed this I think the policy I had applied was wide-open. I too am using the suggested one now.

You could try the suggested IAM policy in #123 and see if that makes a difference, but I doubt it will. I suspect this isn't a permissions issue.

**Comment by edv** [comment]
My problem seems related. When permanently deleting a file from the media library, all sizes of the given image are deleted, except for the original file.

I'm using the IAM policy as provided by the wp cli command, and everything else seems to work okay.

**Comment by philipowen** [comment]
This seems to be a duplicate of #92 So I shall close this one off.
