### ISSUE TITLE
Call to undefined function wp_tempnam()

### ISSUE THREAD

**Issue by andresg747** [humanmade/S3-Uploads#162]
Hi,

I'm getting this error while trying to execute a cron task to create posts programatically. The problem is the post gets created, the file is uploaded to S3 and I can see the file in media library but no thumbnail. Although when creating posts manually it works perfectly. 

Error_log:
```
[Thu Mar 30 20:13:12.782184 2017] [proxy_fcgi:error] [pid 9434:tid 140374362191616] [client 54.174.193.72:33225]AH01071:
Got error 'PHP message: PHP Fatal error:

Uncaught Error: Call to undefined function wp_tempnam() in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/S3-Uploads-master/inc/class-s3-uploads.php:246

Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/S3-Uploads-master/inc/class-s3-uploads.php(232): S3_Uploads->copy_image_from_s3('s3://epa.club.l...')

#1 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(300): S3_Uploads->wp_filter_read_image_metadata(Array, 's3://epa.club.l...')

#2 /opt/bitnami/apps/wordpress/htdocs/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)

#3 /opt/bitnami/apps/wordpress/htdocs/wp-admin/includes/image.php(505): apply_filters('wp_read_image_m...', Array, 's3://epa.club.l...', 2, Array)

#4 /opt/bitnami/apps/wordpress/htdocs/wp-admin/includes/image.php(141): wp_read_image_metadata('s3://epa.club.l...')

#5 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/epa-import/settings.php(414): wp_generate_attachment_metadata(40025, 's3://epa.club.l.....\n', referer: http://epa.club/wp-cron.php?doing_wp_cron=1490904773.7060000896453857421875
```
If anyone knows why is this happening and could help me out with this, I'd really appreciate it.

Thanks

**Comment by andresg747** [comment]
Solved. 

Our plugin was rewritting the URL with **s3://{bucket_name}/{file_path}**, instead of  **https://s3-sa-east-1.amazonaws.com/{bucket_name}/{file_path}**.
I just learned that wp_generate_attachment_metadata needs the URL of the file, whether it is served locally or remotely (S3) in order to work properly. 

I'm sorry I posted an issue to report an our-side-error but I'll leave this answer, under the administrator's discretion, for further help to other newbies in wordpress like me.

**Comment by nicholak** [comment]
This issue appears to persist to this day, as I have code downloaded only yesterday.

The issue appears to indicate that the file in which the function is defined is not included (wp-admin/includes/file.php).

Please advise. Thanks.

**Comment by nicholak** [comment]
My hacky workaround was to add the following to the top of class-s3-upload.php:

`
if ( defined( 'DOING_CRON' ) )
{
    /**
     * Returns a filename of a Temporary unique file.
     * Please note that the calling function must unlink() this itself.
     *
     * The filename is based off the passed parameter or defaults to the current unix timestamp,
     * while the directory can either be passed as well, or by leaving it blank, default to a writable temporary directory.
     *
     * @since 2.6.0
     *
     * @param string $filename Optional. Filename to base the Unique file off. Default empty.
     * @param string $dir      Optional. Directory to store the file in. Default empty.
     * @return string a writable filename
     */
    function wp_tempnam( $filename = '', $dir = '' ) {
        if ( empty( $dir ) ) {
            $dir = get_temp_dir();
        }
        
        if ( empty( $filename ) || '.' == $filename || '/' == $filename ) {
            $filename = time();
        }
        
        // Use the basename of the given file without the extension as the name for the temporary directory
        $temp_filename = basename( $filename );
        $temp_filename = preg_replace( '|\.[^.]*$|', '', $temp_filename );
        
        // If the folder is falsey, use its parent directory name instead.
        if ( ! $temp_filename ) {
            return wp_tempnam( dirname( $filename ), $dir );
        }
        
        // Suffix some random data to avoid filename conflicts
        $temp_filename .= '-' . wp_generate_password( 6, false );
        $temp_filename .= '.tmp';
        $temp_filename = $dir . wp_unique_filename( $dir, $temp_filename );
        
        $fp = @fopen( $temp_filename, 'x' );
        if ( ! $fp && is_writable( $dir ) && file_exists( $temp_filename ) ) {
            return wp_tempnam( $filename, $dir );
        }
        if ( $fp ) {
            fclose( $fp );
        }
        
        return $temp_filename;
    }
}
`

**Comment by larssn** [comment]
This still seems to be an issue, could you reopen?

**Comment by jbboynton** [comment]
It looks like there's a fix for this in master – here's a [link to the PR](https://github.com/humanmade/S3-Uploads/pull/255).
