### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by darkedge3** [humanmade/S3-Uploads#163]
Trying to activate, I receive the following:
`
Parse error: syntax error, unexpected '$value' (T_VARIABLE) in /var/www/vhosts/**domain**/httpdocs/wp-content/plugins/S3-Uploads-master/lib/aws-sdk/Aws/functions.php on line 36`

Any advice appreciated! Thanks

**Comment by rmccue** [comment]
Hi @darkedge3! This is from a keyword inside the AWS library which requires PHP 5.5+, so it seems like you're running on an older version?

We should document the required version of PHP better to make it more apparent that we require 5.5+.

**Comment by darkedge3** [comment]
Thanks, I'll try that!

**Comment by darkedge3** [comment]
Hi, I've tried each version up to 7.~ but still getting this:

`httpdocs]# wp plugin activate S3-Uploads
PHP Parse error:  syntax error, unexpected '$value' (T_VARIABLE) in /var/www/vhosts/*domain*/httpdocs/wp-content/plugins/S3-Uploads-master/lib/aws-sdk/Aws/functions.php on line 36
Parse error: syntax error, unexpected '$value' (T_VARIABLE) in /var/www/vhosts/*domain*/httpdocs/wp-content/plugins/S3-Uploads-master/lib/aws-sdk/Aws/functions.php on line 36
`

Any other thoughts? I'm excited to use this great plugin!

**Comment by darkedge3** [comment]
Any other thoughts to try on this? Many thanks!

**Comment by rmccue** [comment]
@darkedge3 Are you certain you installed the newer version of PHP correctly? [The line](https://github.com/humanmade/S3-Uploads/blob/8051da95759ae4a04025692346cf7ecaa7fe423d/lib/aws-sdk/Aws/functions.php#L36) is valid code, but generators (and `yield`) were only [added in PHP 5.5](http://php.net/manual/en/language.generators.overview.php).

Depending on your system, you may need to separately install new PHP CLI and CGI/FPM packages (i.e. on Ubuntu, you need to upgrade `php-cli` and `php-fpm`).

I can't reproduce this issue, and it's inside the AWS SDK, which definitely works.

**Comment by darkedge3** [comment]
Hi @rmccue 
Just got to looking at this again.

So, I have the correct version of PHP running for wp-cli:
`sh-4.2$ /usr/share/plesk-wp-cli/bin/wp --info
PHP binary:	/opt/plesk/php/5.5/bin/php
PHP version:	5.5.38
php.ini used:	/opt/plesk/php/5.5/etc/php.ini
WP-CLI root dir:	/usr/share/plesk-wp-cli
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.25.0
sh-4.2$ `

However, I am still getting errors:

`sh-4.2$ /usr/share/plesk-wp-cli/bin/wp s3-uploads migrate-attachments
PHP Warning:  Invalid argument supplied for foreach() in /var/www/vhosts/*domain*.co.uk/httpdocs/wp-content/plugins/wordpress-seo-premium/premium/classes/redirect/class-redirect-handler.php on line 163
Warning: Invalid argument supplied for foreach() in /var/www/vhosts/*domain*.co.uk/httpdocs/wp-content/plugins/wordpress-seo-premium/premium/classes/redirect/class-redirect-handler.php on line 163
PHP Fatal error:  Call to a member function update_db() on a non-object in /var/www/vhosts/*domain*.co.uk/httpdocs/wp-content/plugins/woozone/plugin.php on line 35
Fatal error: Call to a member function update_db() on a non-object in /var/www/vhosts/*domain*.co.uk/httpdocs/wp-content/plugins/woozone/plugin.php on line 35`

although these are different plugins? any idea whats up?! Thanks

**Comment by joehoyle** [comment]
@darkedge3 these are due to different plugins now. Looks like 5.5 fixed the issue with S3 Uploads though. The fatal error here is not from s3 uploads.
