### ISSUE TITLE
Question: Want to migrate my WP uploads folder to S3

### ISSUE THREAD

**Issue by cluber22** [humanmade/S3-Uploads#164]
Is it required that I have SSH access to the server so that I can install and run the http://wp-cli.org commands? Or is there another way to migrate.

My server is basically on AWS ElasticBeanstalk and although I could technically connect to it via SSH, I don't really want to if not necessary. 

Thanks,

**Comment by jgreaves8** [comment]
Yeah you do - there's no interface within the WordPress admin itself. You don't need to actually install wp-cli though, you can just do what I did and rename the "wp-cli.phar" file to just "wp" and then run the command like this:

./wp s3-uploads verify

that way you don't need to move wp-cli into the usr/ directory to execute it. Although you will have to have the wp-cli.phar (or whatever you rename it to) in each WordPress root, it won't be globally available

**Comment by cluber22** [comment]
Okay thank you.
