### ISSUE TITLE
HTTP Error when uploading new images

### ISSUE THREAD

**Issue by jdiaz1302** [humanmade/S3-Uploads#167]
When I try to upload a new image I just get a HTTP error, it doesn't say anything else, just that plain HTTP error.

I'm using the most recent version of WordPress with SSL enabled.

Thanks in advance for any info.

**Comment by rmccue** [comment]
@jdiaz1302 Thanks for filing the issue. We'd need more detail to investigate what's going wrong, including the HTTP error and any debugging steps you've taken. (Also [note our support policy](https://engineering.hmn.md/projects/support/).)

In lieu of that, closing this issue out. If you're still experiencing the issue, report back and reopen the issue, noting the debugging steps you've taken and your system information.
