### ISSUE TITLE
Media library still pointing to local uploads directory

### ISSUE THREAD

**Issue by cluber22** [humanmade/S3-Uploads#170]
As you can see when in wp-admin on the media library, everything is still pointing to the local storage and not S3.

Media library URL: /wp-admin/upload.php

Example of broken image links: http://imgur.com/a/qSq0y

**Comment by fagiani** [comment]
@cluber22 in the print it's not possible to see the current full URL. I've recently faced a similar issue. If it starts with https:// then that might be a mixed content issue or invalid SSL certificate if you're using a full domain bucket name but keeping the default S3 website URL. Hope it helps!

**Comment by joehoyle** [comment]
Closing as inactive.
