### ISSUE TITLE
Enabled, activated, configured, verified, but doesn't do anything?

### ISSUE THREAD

**Issue by gamut** [humanmade/S3-Uploads#178]
It's hard for me to describe a problem that doesn't have any symptoms aside from media uploads never being created in S3, and all URLs still pointing to the site.

How does one diagnose this kind of issue?  The `migrate-attachments` method runs through and creates files in S3, but new uploads don't get moved over.  Am I missing something?

**Comment by rmccue** [comment]
Thanks for being more specific than "doesn't work". :) Few quick questions:

* Is the plugin activated?
* Are the constants (bucket, key/secret or instance profile, region) defined in your wp-config?
* Are you running PHP 5.5+?
* Does `wp s3-uploads verify` tell you anything?

Likely what's happening is that somewhere [during init](https://github.com/humanmade/S3-Uploads/blob/52800e082904f5a3bcfa44e20f2a9b4912568ece/s3-uploads.php#L17-L46), the plugin is silently bailing out. We should improve this by adding some error reporting, but first we should solve your issue.

**Comment by gamut** [comment]
That's affirmative to all questions, and `verify` reports that everything is a-ok:

```
Attempting to upload file s3://supersecretbucket/uploads/1292879121.jpg
File uploaded to S3 successfully.
Attempting to delete file. s3://supersecretbucket/uploads/1292879121.jpg
File deleted from S3 successfully.
```

That's what's so vexing about it.  The bailout is very very silent.

Here's the output of `php -v`:

```
PHP 5.5.9-1ubuntu4.20 (cli) (built: Oct  3 2016 13:00:37)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

**Comment by gamut** [comment]
So, my defines were too low in wp-config.php... Noob error, but I guess it would be helpful if there was some kind of feedback somewhere.

**Comment by rmccue** [comment]
Ah! Good to see you've fixed it, I'll file an issue for more error reporting.

**Comment by gamut** [comment]
Great. Thanks. Just a thought that this should only show something in the admin panel. Dismissible. So the error log doesn't get littered on every request. However, it's reasonable to assume that if the plugin is enabled but env vars aren't set, then something unintentional has occurred.

**Comment by rmccue** [comment]
S3 Uploads doesn't have any UI, and it makes more sense for us to log I think. A lot of warnings getting logged into our alerts will actually get someone to notice it. 😉

**Comment by gamut** [comment]
Indeed.  And, again, I think it's highly unlikely someone would enable the
plugin but not intend to configure it.  So you're probably right that it
should scream bloody murder in the logs.

**Comment by gamut** [comment]
One more thing.  It does detract from the `verify` function that it doesn't actually replicate real WP behaviour.  i.e., while verify picked up the defines, WP -- maybe because of execution order -- didn't. I would make the effort to have it do a complete end to end test -- but I'm not the one making the effort...

**Comment by svaldesm** [comment]
@gamut Been punching my head to the door on this!!!! God damn it. Too low in wp-config too. 
Maybe too noob, but this might be on the FAQs maybe. Thanks!
