### ISSUE TITLE
How to use it for s3 compitible storage like minio,wasabi,ceph s3, swift?

### ISSUE THREAD

**Issue by xianx** [humanmade/S3-Uploads#184]
Hello,

How can I use it with s3 compatible storage like minio,wasabi,ceph s3, swift

With awscli there is option of --endpoint-url
http://docs.aws.amazon.com/cli/latest/reference/

How it could be used with S3-Uploads?

**Comment by etherealite** [comment]
This used to work for me when I tried with v2.0.0-beta3
```php
  add_filter('s3_uploads_s3_client_params', function($params){
    error_log('s3 uploads filter run');
    $params['endpoint'] = S3_UPLOADS_BUCKET_URL;
    error_log(var_export($params, true));
    return $params;
  });
```

But that tag is super far behind master, and when I switched to master, this no longer is working for me.

**Comment by etherealite** [comment]
I got it working again using the master branch I think it's on e9775f60afb20ceba1a15d6a73cb58eb8f72f951.

 I used the same hook that lets you edit the config that gets passed to the s3client factory method. The only difference is that I had to add a new parameter, `use_path_style_endpoin` as you can see bellow.
```php
add_filter('s3_uploads_s3_client_params', function($params){
    $params['endpoint'] = 'http://minio-server.dev'    
    $params['use_path_style_endpoint'] = true;¬
    return $params;
  });

**Comment by joehoyle** [comment]
@etherealite thanks for the support help!
