### ISSUE TITLE
Existing images migrated to S3, but not links in Wordpress

### ISSUE THREAD

**Issue by jenibelle08** [humanmade/S3-Uploads#188]
I've installed the plugin and run the command line to "find and replace" the image URLs in the database, with the goal of having WordPress now use S3 instead of the WordPress upload directory for these existing images.

The S3-Upload tool did successfully copy all the images onto S3 (into an "uploads" directory); however WordPress is still referencing the original copies of the images in the WordPress directory.

In the wp_postmeta table, an entry "amazonS3_cache" is added, but it doesn't appear to have any effect on how WordPress handles the image.

Does anybody have any idea why this might be?

**Comment by brianmori** [comment]
Hello,

I have run the script as well with PHP 7.1 and Wordpress 4.7.1

| wpleus_posts         | guid                  | 9            | SQL  |

the table contains the absolute URLs to the S3, 
select guid from wpleus_posts;

still Wordpress uses the relative links to the upload directory stored in filesystem

I try to add a new file to check the differences

**Comment by brianmori** [comment]
Hello,

I added a new image, and the image was actually stored in the filesystem.

S3 Uploads is actually activated, and the s3-uploads verify is successful.

@joehoyle may it be a bug in the latest commit beta version ?


`
+--------------------------------+----------+-----------+-------------+
| name                           | status   | update    | version     |
+--------------------------------+----------+-----------+-------------+
| contact-form-7                 | active   | available | 4.5.1       |
| disable-feeds                  | active   | none      | 1.4.4       |
| duplicate-post                 | inactive | none      | 3.2         |
| googleanalytics                | active   | available | 1.0.7       |
| listo                          | active   | available | 1.1         |
| quick-pagepost-redirect-plugin | inactive | none      | 5.1.8       |
| really-simple-captcha          | active   | available | 1.9         |
| remove-author-pages            | active   | none      | 0.2         |
| remove-xmlrpc-pingback-ping    | active   | none      | 1.0.0       |
| root-relative-urls             | active   | none      | 2.3         |
| S3-Uploads                     | active   | none      | 2.0.0-beta2 |
| simple-image-sizes             | inactive | none      | 3.1.1       |
| stop-user-enumeration          | active   | available | 1.3.8       |
| tinymce-advanced               | inactive | none      | 4.5.6       |
+--------------------------------+----------+-----------+-------------+

`

**Comment by brianmori** [comment]
I used the release beta3 and the 

| wpleus_posts         | post_content          | 2   

actually changed when doing the replace

**Comment by joehoyle** [comment]
> In the wp_postmeta table, an entry "amazonS3_cache" is added, but it doesn't appear to have any effect on how WordPress handles the image.

This looks like a different S3 plugin, S3 Uploads has no such meta. 

> the table contains the absolute URLs to the S3,
select guid from wpleus_posts;

> still Wordpress uses the relative links to the upload directory stored in filesystem

GUID is not used to generate URLs. If you are not seeing URLs replaced by S3 Uploads, it's quite possible you have other plugins changing this URL. Let let me know if you resolved this, but this issue is very old I'm going to close an inactive.
