### ISSUE TITLE
Stopped uploading

### ISSUE THREAD

**Issue by butchewing** [humanmade/S3-Uploads#193]
Everything was working great, but now, it's not uploading. The file is logged in the media library but the file is not stored in wp-content/uploads or in my S3 bucket.

`wp s3-uploads verify` works
`wp s3-uploads ls` works

No errors logged. 

```
define( 'S3_UPLOADS_BUCKET', 'media.example.com' );
define( 'S3_UPLOADS_KEY', '*******************' );
define( 'S3_UPLOADS_SECRET', '*******************************' );
define( 'S3_UPLOADS_REGION', 'us-east-1' );
define( 'S3_UPLOADS_HTTP_CACHE_CONTROL', 30 * 24 * 60 * 60 );
define( 'S3_UPLOADS_AUTOENABLE', true );
define( 'S3_UPLOADS_BUCKET_URL', 'https://media.example.com' );
```

`wp s3-uploads cp <from> <to>` returns **Success** and file is uploaded.

Is it possible that the file is being prevented from uploading to the `tmp` directory?

**Comment by butchewing** [comment]
The uploading stopped sometime between 2017-08-08 and 2017-08-17

**Comment by butchewing** [comment]
`wp s3-uploads cp <from> <to>` returns success, but nothing is uplaoded.

**Comment by etherealite** [comment]
Did you switch to a new version of the plugin? If you're installing from master, it's changing all the time.

**Comment by butchewing** [comment]
It would be helpful if the version number was changed with each update. Or, at least, a last modified date.

I updated to the latest version and now it's [causing an error](https://github.com/humanmade/S3-Uploads/issues/197). Progress, I suppose :)

**Comment by etherealite** [comment]
There is a version number, it's the commit hash on @master.

The tagged commits are rare and thus lag behind in progress on master by a pretty high degree.  There are tons of fixes in master that aren't in beta3.

I'm on master@ef0aa43d797e0c4c4890661a6bc28b586ff6710f and things seem to be working, but beta3 has autoloader errors for me, so it doesn't work at all.
