### ISSUE TITLE
PHP Warning - failed to open dir: Too many open files in S3-Uploads/lib/aws-sdk/Aws/functions.php on line 179

### ISSUE THREAD

**Issue by bungcayao** [humanmade/S3-Uploads#195]
I seem to have hit a limit of folders/files that I'm able to sync to my s3 bucket. If I have about 132 folders/files in a directory that I'm uploading, it seems to work fine. If I have anything more than that, I get the PHP warning and eventually an Error saying File not found.

I'm thinking the problem is related to this: https://github.com/aws/aws-sdk-php/issues/749
However, I'm not sure how I could implement that into S3-Uploads.

Anyone else have this problem or been able to apply a fix to this?

**Comment by rmccue** [comment]
What are you running that gives you this error?

**Comment by etherealite** [comment]
If I were you I'd be providing detailed repro steps for you issue.

**Comment by rmccue** [comment]
Closing in favour of #396, which seems similar, but has detailed information.
