### ISSUE TITLE
"The uploaded file could not be moved to"

### ISSUE THREAD

**Issue by considine** [humanmade/S3-Uploads#205]
Everything works, 

**Verify:**
wp s3-uploads verify                                                                                                  
Attempting to upload file ...
File uploaded to S3 successfully.
Attempting to delete file. ...
File deleted from S3 successfully.
Success: Looks like your configuration is correct.

**wp s3-uploads upload-directory wp-content/uploads** 
transfers all files properly

However, when inserting media of any type, in any way, the following error is thrown:

![image](https://user-images.githubusercontent.com/10143364/33199683-e1f17d98-d0b6-11e7-802a-5e8482e46cee.png)

Am I the only one with this issue?

Side note:

Uncaught Error: Class 'Aws\Common\Aws' not found in /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-content/plugins/S3-Uploads/inc/class-s3-uploads-wp-cli-command.php:160

When running the wp s3-uploads create-iam-user command

this was referenced here:

#95 

and definitely never resolved (i confirmed to be using the most stable release)

Thanks for any help

**Comment by considine** [comment]
I 
1.) created a new wp installation
2.) created a new aws s3 bucket (tested uploads from CL with credentials)
3.) added s3-uploads plugin, and configured accordingly

and got the same exact results (error: could not move "" to "", on uploading media).

Could someone confirm this?  Maybe I'm misunderstanding the purpose of the plugin... 

Thanks for any help

**Comment by joehoyle** [comment]
@considine are you using the latest Version 2 beta? Also are you loading the AWS-SDK elsewhere in your project, via composer or otherwise?

**Comment by considine** [comment]
Hi, go to releases and use the most recent stable version (download as zip and move to your plugin directory) instead of cloning / adding as a submodule directory. That fixed the issue for me.

**Comment by sebbean** [comment]
interesting. I'd love to use this repo with composer somehow... I supposed it's not absolutely necessary.

I tried adding the repo to composer this way(https://github.com/bean-la/kelton/blob/task/kelton-changes/composer.json#L22) with interesting results.

I'll try your method

**Comment by sebbean** [comment]
@considine just followed your steps, no luck. same error.
Using:
https://github.com/PhilippHeuer/wordpress-heroku
And the bucketeer plugin. 

Will open an issue on the wordpress-heroku project

**Comment by sebbean** [comment]
using my own S3 Credentials and AWS_S3_URL env var on heroku this plugin works fine.

That is to say either this file is broken:
https://github.com/PhilippHeuer/wordpress-heroku/blob/master/config/plugins/heroku/heroku-bucketeer.php

or Bucketeer's credentials are broken?

However, this config file does work as expected:
https://github.com/PhilippHeuer/wordpress-heroku/blob/master/config/plugins/wordpress/wordpress-s3uploads.php

Will update wordpress-heroku project with appropriate issue
