### ISSUE TITLE
"Unable to create directory uploads. Is its parent directory writable by the server?"

### ISSUE THREAD

**Issue by ecairol** [humanmade/S3-Uploads#207]
Hi,

### **From CLI**
Running `wp s3-uploads verify` correctly uploads and deletes an image.

### **From WP Admin Panel**
I was able to upload the first image to `/uploads` in S3, however, subsequent images started throwing the error _Unable to create directory uploads. Is its parent directory writable by the server?_

I changed the upload directory to be organized by Year and Month, so that it creates a new folder structure and again. Again, I was able to upload the first image to `/uploads/2017/12` but for further images, it throws the same error.

--- 
Seems to me that WordPress is trying to create the folder every time a new image is uploaded, and then fails because the folder already exists.

Does anyone have an idea how to debug or solve this problem?

Thanks in advance

**Comment by rmccue** [comment]
This is pretty strange. S3 doesn't actually have directories, so whether you've uploaded a file into a "directory" already shouldn't matter.

Are you using any other plugins that could potentially be doing something strange here?

**Comment by ecairol** [comment]
For anyone out there having the same issue: this was a permissions issue in S3. It allowed you to upload the first image and then throw the error. Check the AIM user's permissions.

**Comment by rmccue** [comment]
Thanks for letting us know, good to hear you got it resolved. 😃 🎁 ☃️

**Comment by mohanjith** [comment]
@ecairol what was the permission that was missing. I'm having the same problem but I have given wide access to the bucket in question.
