### ISSUE TITLE
Media Library slowness

### ISSUE THREAD

**Issue by daohoangson** [humanmade/S3-Uploads#216]
I'm setting up a rather large site and we have lots of images. Everything seems to work (except for the permanent delete issue) but Media Library is painfully slow... After tracking it down I think the problem is with [wp_prepare_attachment_for_js](https://codex.wordpress.org/Function_Reference/wp_prepare_attachment_for_js), specifically these lines:

```php
	if ( isset( $meta['filesize'] ) ) {
		$bytes = $meta['filesize'];
	} elseif ( file_exists( $attached_file ) ) {
		$bytes = filesize( $attached_file );
	} else {
		$bytes = '';
	}
```

WordPress Core doesn't set the `filesize` except for [files that are processed by ID3](https://core.trac.wordpress.org/ticket/33214). That means `wp_prepare_attachment_for_js` almost always call `file_exists()` + `filesize()` and triggers a remote download!

My current workaround is to hook into `wp_get_attachment_metadata` and set `filesize = 0` because I don't care about it that much enough. However, I think this plugin can do the right thing by injecting the size during `wp_generate_attachment_metadata` or similar.

**Comment by joehoyle** [comment]
Hmm good catch, seems like core is the best place to fix this - though I'd be in favor of including a polyfill into s3-uploads to include the filesize on `generate_attachment_metadata` or similar.
