### ISSUE TITLE
Error: "failed to copy" - after migrating servers

### ISSUE THREAD

**Issue by 1x24** [humanmade/S3-Uploads#220]
I migrated servers three days ago, but I have been unable to replicate the working instance of this plugin. Same keys, same access details, same policy, same bucket, same zone.

**I run this command:-**
wp s3-uploads verify

**And get this error:-**
Attempting to upload file s3://BUCKETNAME/uploads/879270283.jpg
Error: Failed to copy / write to S3 - check your policy?

My policy is totally fine - because it is still working on the old server.

I have tried various things e.g. turning off my firewall. I also went into Amazon S3 and set the user's permissions to be the highest admin level possible (no restrictions) - just to see what happens. Then I made the bucket public (for read / write access), but still I am getting this error above.

I run the cp (copy) command and it says it successfully copied, but nothing was copied.

I have no idea what might be wrong here. Please help! What else can I check? I suspect some sort of configuration / security issue. I really need to move off the old server.

**Comment by joehoyle** [comment]
Just a thought- your new server’s date may be wrong, it’s important to have a synced clock to handle the aws signatures.

**Comment by 1x24** [comment]
Hello @joehoyle Thanks, I just cross-checked the time on the server and it's correct. Also using ntpd to synchronize. Another thing I just tried was to disable Suhosin - just in case it's blocking something. Any other ideas on what to try, please? 

I am also unable to create a new IAM user from wp s3-upload. That just fails silently and leaves no errors in the logs.

**Comment by 1x24** [comment]
Solved the problem by creating new access keys. For some reason, it seems that migrating a server will make the old access keys stop working? Ah, well.

P.S. I also downgraded the policies right back, to only what the application needs.
