### ISSUE TITLE
Make plugin updatable (with Github Updater plugin?)

### ISSUE THREAD

**Issue by teolaz** [humanmade/S3-Uploads#222]
As title,
is it possible to have the plugin always up to date in some ways?
I'm handling my themes updates using Github Updater, but if you have other ways, just all is welcome.

**Comment by rmccue** [comment]
We do tag releases (when we can remember to), so you could [subscribe to the Atom feed](view-source:https://github.com/humanmade/S3-Uploads/releases.atom).

Closing this out, as we use git submodules, so bundling an alternative updater library wouldn't make sense for us.

**Comment by rmccue** [comment]
If that’s all it requires, feel free to send a pull request for it :)

**Comment by teolaz** [comment]
I'm thinking about integrating something like this https://github.com/YahnisElsts/plugin-update-checker instead of requiring an external plugin to have the updates handled...
Do you think you can struggle enough to write the main json any time a fix is done?

**Comment by teolaz** [comment]
BTW... is there any thing i need to know before deleting the lib folder and installing all the dependencies included the AWS library using composer?
