### ISSUE TITLE
How this plugin works?

### ISSUE THREAD

**Issue by xianx** [humanmade/S3-Uploads#227]
I want to know how this plugin works?

1. Do this plugin first write to disk and than upload the file to Digital Ocean Spaces? or upload files directly to Digital Ocean Spaces?
2. What will happen if a file failed to upload to s3 during upload process? Will it skip? Will the local file remain on host and there will missing file on s3 and eventually site will show broken file?

**Comment by joehoyle** [comment]
1. Yes it writes to disk in `/tmp` as part of PHP's $_FILES handling, apart from that it's not written anywhere.
2. As it will be in temp, I believe the system will clean them out, in fact PHP probably deletes all the $_FILES on shutdown.

**Comment by xianx** [comment]
What will happen if a file failed to upload to s3 during upload process? Will it skip uploading to s3? Will it retry upload again? Will the local file remain on host and there will missing file on s3 and eventually site will show broken file?

**Comment by joehoyle** [comment]
The process will be exactly the same as if WordPress Core wasn't able to move the file to the uploads directory. It won't be retried, an attachment won't be created. As mentioned before, the local file on the machine:

> As it will be in temp, I believe the system will clean them out, in fact PHP probably deletes all the $_FILES on shutdown.
