### ISSUE TITLE
How to set is public file from s3?

### ISSUE THREAD

**Issue by wagnerlima85** [humanmade/S3-Uploads#230]
Hi, 

I need upload file to s3 and set public, but i'm having some troubles. We can upload files but can't get access to they with **CloudFront** or **absolut path**. Can you show how to do this in your plugin? 

Att,

**Comment by joehoyle** [comment]
This is the origin and behaviour we used for Cloudfront:

![](https://joehoyle-captured.s3.amazonaws.com/UXAZDT0T.png)

![](https://joehoyle-captured.s3.amazonaws.com/OUQIZOZd.png)

This is to map `/uploads` on the site's Cloudfront distribution to the s3 bucket - which you may or may not be doing quite the same, but should give you an idea.

**Comment by wagnerlima85** [comment]
Thanks for your help!

But we use more than one way to send files.
For example: By sending a java service (in our application), we were able to send and view these files that we sent. However I would like to know if there is a possibility to send some parameter to set the file as public.
Best regards

**Comment by joehoyle** [comment]
@wagnerlima85 the ACL for the object is already set to `public-read` in https://github.com/humanmade/S3-Uploads/blob/master/inc/class-s3-uploads.php#L79. It might be your bucket policy blocking access, perhaps.
