### ISSUE TITLE
Pull images from S3?

### ISSUE THREAD

**Issue by dingo-d** [humanmade/S3-Uploads#231]
Is it possible to pull the images from the S3 so that they appear in the media library?

I migrated the images to the S3, and the permalinks were changed (all great), and I deleted the files from the uploads folder. And for some reason the links in the media library started pointing back to the old wp install url instead of S3 link.

On top of that, resaving pages, replaced the S3 link with the wp link (and uploads folder is empty). Is there a `pull` command which will populate the media library?

EDIT:

From what I'm reading on the AWS docs page this should be possible: https://docs.aws.amazon.com/aws-sdk-php/v2/guide/service-s3.html#downloading-objects

**Comment by joehoyle** [comment]
No, this is very far from how the plugin works, the files should never be stored locally in your uploads folder. The media library runs "live" off the S3 files.

> And for some reason the links in the media library started pointing back to the old wp install url instead of S3 link.

This sounds like the problem, and the "some reason" is what you'd need to get to the bottom of. You can inspect the several reasons why S3 Uploads may not be hooking in and replacing the URLs at https://github.com/humanmade/S3-Uploads/blob/master/s3-uploads.php#L17.

**Comment by dingo-d** [comment]
The plugin works, that is, the images were successfully stored in the bucket. I `wp search-replace`d all the tables. But the url in the media library still points to the `uploads` folder, rather than the s3 bucket. I'm currently digging as to where this data is coming from to see what could be wrong.

Also I just now tested and when I tried to upload an image in the media library I got

> Unable to create directory wp-content/uploads/2018/04. Is its parent directory writable by the server?

I thought that the uploads go directly to the s3 bucket?

**Comment by joehoyle** [comment]
This sounds like any piece of evidence that S3 Uploads is now no longer enabled / or configured. As you mentioned, the images _were_ stored in the bucket before, but now are failing to be written to local disk. If S3 Uploads is working as intended, it would now be touching your local uploads directory.

**Comment by dingo-d** [comment]
Ok, the message for the writable directory was the fault of the chown, but the newly uploaded file wasn't uploaded to the bucket. And when I test it using `wp s3-uploads verify` I get

```sh
Attempting to upload file s3://bucket/uploads/851740717.jpg
File uploaded to S3 successfully.
Attempting to delete file. s3://bucket/uploads/851740717.jpg
File deleted from S3 successfully.
Success: Looks like your configuration is correct.
```

So it works... kinda?

**Comment by joehoyle** [comment]
The message you might have just fixed with chown fixed the symptom, but the error is useful to know something isn't working as it should be. You might want to try disabling all other plugins to make sure there's no conflict going on. Anything that is likely to adjust `wp_upload_dir()` would cause issues for example.

**Comment by dingo-d** [comment]
I'll try that, and I'll try to empty the bucket and migrate attachments again. It was working fine until today, so I guess it has to be an issue on my end.

Btw the pull command, I was thinking of a wp-cli command just in case :) 

Thanks
