### ISSUE TITLE
Upload Issue

### ISSUE THREAD

**Issue by zacscott** [humanmade/S3-Uploads#24]
Hi Joe,

Just went to update a site after the couple pull requests we submitted and I am running into a few issues.

Uploads through the browser are failing, yet the verify command is working fine.

![screen shot 2015-06-15 at 10 08 23 am](https://cloud.githubusercontent.com/assets/3852691/8151089/045330a0-1347-11e5-9b5a-d559936ad797.png)

The php error log:

	[15-Jun-2015 00:08:21 UTC] PHP Fatal error:  Uncaught exception 'Guzzle\Common\Exception\RuntimeException' with message 'Guzzle\Http\CachingEntityBody supports only SEEK_SET and SEEK_CUR seek operations' in /Users/zacscott/httpdocs/mumbrella.local.au/wp-content/mu-plugins/S3-Uploads/lib/aws-sdk/Guzzle/Http/CachingEntityBody.php:66
	Stack trace:
	#0 /Users/zacscott/httpdocs/mumbrella.local.au/wp-content/mu-plugins/S3-Uploads/lib/aws-sdk/Aws/S3/StreamWrapper.php(269): Guzzle\Http\CachingEntityBody->seek(0, 2)
	#1 [internal function]: Aws\S3\StreamWrapper->stream_seek(0, 2)
	#2 /Users/zacscott/httpdocs/mumbrella.local.au/wp/wp-admin/includes/image.php(336): exif_read_data('s3://vum-dev/up...')
	#3 /Users/zacscott/httpdocs/mumbrella.local.au/wp/wp-admin/includes/media.php(337): wp_read_image_metadata('s3://vum-dev/up...')
	#4 /Users/zacscott/httpdocs/mumbrella.local.au/wp/wp-admin/includes/ajax-actions.php(1901): media_handle_upload('async-upload', NULL, Array)
	#5 /Users/zacscott/httpdocs/mumbrella.local.au/wp/wp-admin/async-upload.php(43): wp_ajax_upload_attachm in /Users/zacscott/httpdocs/mumbrella.local.au/wp-content/mu-plugins/S3-Uploads/lib/aws-sdk/Guzzle/Http/CachingEntityBody.php on line 66

Any ideas?

Thanks,
- Zac

**Comment by joehoyle** [comment]
Fixed by a9db109, sorry!

**Comment by zacscott** [comment]
Thank you very much for the quick fix Joe

- Zac
