### ISSUE TITLE
Will this work for the wp-personal-data-exports dir/url?

### ISSUE THREAD

**Issue by dingo-d** [humanmade/S3-Uploads#240]
WordPress 4.9.6 added `wp-personal-data-exports` dir for exporting user personal data (GDPR). I'm wondering will this folder be automatically picked up and moved to S3 as well? 

Or do I need to manually modify the upload using `wp_privacy_exports_dir` and `wp_privacy_exports_url` url?

**Comment by joehoyle** [comment]
Yup `wp_privacy_exports_dir` is already hooked in to append to the `wp_upload_dir()` so S3 will be used for this when using S3 Uploads.

**Comment by dingo-d** [comment]
Great to hear that :)
