### ISSUE TITLE
s3_uploads_s3_client_params never executed

### ISSUE THREAD

**Issue by ericchaves** [humanmade/S3-Uploads#245]
Hi folks,

I'm using localstack to develop locally and in order to properly setup the plugin I added the `s3_uploads_s3_client_params` at the end of my wp-config.php but the filter is never executed and whenever I upload a file I got the "could not move to" error. 

What could be preventing the filter from firing? should I declare it in other file instead of wp-config.php?
```
require_once(ABSPATH . 'wp-settings.php');
add_filter('s3_uploads_s3_client_params', function($params){
  if(!empty(getenv('S3_ENDPOINT'))){
    $params['endpoint'] = getenv('S3_ENDPOINT');
    $params['use_path_style_endpoint'] = true;  
  }
  $dump = var_dump($params, true);
  error_log("-------------------------------> DUMP: $dump");
  return $params;
});
```

**Comment by rmccue** [comment]
This is declared too late for the filter to have any effect, you need to place it into a plugin or theme instead. (Note that we're unable to provide support for generic WordPress development.)

**Comment by ericchaves** [comment]
@rmccue Forgive me for asking but I did tried it at several different places before asking here and none of them worked (at wp-config.php, at another plugins_loaded event, among other plugin events). I understand you can't provide WP support but can't you point me a good candidate place for it ? It can't be that hard to only be usable by advanced WP programmers.

Thanks.

**Comment by nbyloff** [comment]
@rmccue I have this in my functions.php file. Using xdebug, the S3 config is loaded during the `plugins_loaded` action. The theme hasn't even been loaded yet so the custom filter isn't even loaded until after `apply_filters('s3_uploads_s3_client_params');` is executed

````
/**
 * add custom Amazon AWS S3 config options
 */
add_filter('s3_uploads_s3_client_params', function($params)
{
    $params['csm'] = false; // AWS_CSM_ENABLED
    return $params;
});
````

**Comment by hlidotbe** [comment]
Same issue here. It's impossible to setup this filter in a theme because the plugins_loaded action is always fired before the theme is setup (https://codex.wordpress.org/Plugin_API/Action_Reference#Actions_Run_During_a_Typical_Request). A better timing for this hook would be `init` I guess. I'll fork and submit a PR.
