### ISSUE TITLE
Rewrites and auto uploads not happening

### ISSUE THREAD

**Issue by emccormickva** [humanmade/S3-Uploads#247]
Hi,

I've installed and activated the latest code from master, and I'm able to verify and migrate just fine. Everything is getting put in my bucket as expected.

However, when creating new media, they are uploaded only to the local /uploads directory and never get pushed to S3. Additionally, URLs aren't being rewritten for anything new or migrated.

I've manually enabled rewriting using 'wp s3-uploads enable' just in case even though I didn't turn off autoenable. and I've confirmed wordpress sees the plugin as activated.  Am I missing something that's needed to enable this functionality? I'm not precisely sure how to go about debugging it. I've cranked up WP_DEBUG but there's no mention of any errors at all.

Thanks,
Erik

**Comment by emccormickva** [comment]
FYI this is PHP 7.1 and WP 4.9.6

**Comment by caballe** [comment]
Same problem here.

Wordpress 4.9.6
S3-Uploads  
PHP 7.2.5

wp s3-uploads verify
Success: Looks like your configuration is correct

regards
Salvador

**Comment by caballe** [comment]
I have checked once again all the configuration and installation, but after 

wp s3-uploads enable command  NO  URL rewriting and NO new uploads on S3 . there is no error message, 

manual file transfer to S3 works without problem, 

regards
Salvador

**Comment by nightelf** [comment]
same problem. Any answers?

**Comment by caballe** [comment]
Thanks for the trick, now is working !!

**Comment by kgoedecke** [comment]
@nightelf made my day :) :+1:

**Comment by mobiusint** [comment]
> OK... so I solved this problem for myself by placing the define('S3_UPLOADS_BUCKET'), etc., at the top of the wp-config.php file, ostensibly above the include for: wp-settings.php.

Worked for me!!! THanks

**Comment by sirtawast** [comment]
> OK... so I solved this problem for myself by placing the define('S3_UPLOADS_BUCKET'), etc., at the top of the wp-config.php file, ostensibly above the include for: wp-settings.php.

Just spent 4 hours debugging. Trying to get some info from logs, doing chown/chmods, `wp s3-uploads verify`, all sorts of knik-knacks. My localhost was working perfectly and I was so confused ... 

Thought it was apache with a rewrite issue or something. But no, in localhost I tend to put everything top. This time the remote config had constants bellow `wp-settings.php`. Thanks a bunch!
