### ISSUE TITLE
Default Storage Class

### ISSUE THREAD

**Issue by pySilver** [humanmade/S3-Uploads#261]
Is there any way to define storage class for uploads? It would be wonderful to have such constant.

**Comment by roborourke** [comment]
It's not documented in the readme but you can use this filter:

https://github.com/humanmade/S3-Uploads/blob/master/inc/class-s3-uploads-stream-wrapper.php#L218

eg.

```php
add_filter( 's3_uploads_putObject_params', function ( $params ) {
    $params['StorageClass'] = 'INTELLIGENT_TIERING';
    return $params;
} );
```

I don't think we'll use a constant here as you may want to apply some logic to it eg. if you had `/uploads/backups` in the path you could set the storage class to `GLACIER` and everything else could be standard or whatever.

The default `STANDARD` seems like a sensible default and what AWS recommend.
