### ISSUE TITLE
A Little More Understanding

### ISSUE THREAD

**Issue by davidbitton** [humanmade/S3-Uploads#273]
I spent some time looking at the code, and I just need a little more understanding. If I'm understanding this correctly, the plugin registers a stream handler for `s3://` and then changes the `upload_dir` to include the "s3" protocol. Subsequently the plugin then handles uploads with that protocol. Is that the gist of things? I ask because I want to be able to use the [Easy Upload Files During Checkout](https://tro.pe/2CBOvKi) plugin which writes to the local filesystem using `wp_handle_upload` which is dependent on the output of `wp_upload_dir` which you're mangling with the use of the `upload_dir` filter. 

Did I get this right? Ultimately I want files uploaded to the site to be uploaded directly to S3 without hitting the local filesystem. Thanks.

**Comment by rmccue** [comment]
> I spent some time looking at the code, and I just need a little more understanding. If I'm understanding this correctly, the plugin registers a stream handler for `s3://` and then changes the `upload_dir` to include the "s3" protocol.

Correct. Specifically, it replaces the root in `upload_dir` e.g. `/var/www/wp-content/uploads/2018` to `s3://{BUCKET}/2018`.

> Subsequently the plugin then handles uploads with that protocol.

Kind of. More specifically:

* WordPress uses the standard PHP APIs to save files to `upload_dir`
* `upload_dir` is `s3://...`, so it uses the PHP stream handler for `s3`
* `S3_Uploads_Stream_Wrapper` uses the AWS SDK to write data to S3

> Is that the gist of things? I ask because I want to be able to use the [Easy Upload Files During Checkout](https://tro.pe/2CBOvKi) plugin which writes to the local filesystem using `wp_handle_upload` which is dependent on the output of `wp_upload_dir` which you're mangling with the use of the `upload_dir` filter.

Presumably, it will work fine, provided it also uses the standard PHP APIs which support stream wrappers. If it uses APIs which don't support stream wrappers (`WP_Filesystem` I think is incompatible), it will break.

Try it and find out :)

> Did I get this right? Ultimately I want files uploaded to the site to be uploaded directly to S3 without hitting the local filesystem. Thanks.

Pretty much, yeah, it will upload directly to S3. It doesn't save them to `wp-content/uploads` then move them.

However, note that when you upload files with PHP, it saves them to your temp directory first, then moves them from there. This is typically not an issue, but if you're looking at this for compliance reasons or similar, it may be.

If all you're concerned about is ensuring nothing writes to `wp-content` (i.e. immutable web directory), then S3 Uploads will solve that issue. :)

**Comment by davidbitton** [comment]
> If all you're concerned about is ensuring nothing writes to `wp-content` (i.e. immutable web directory), then S3 Uploads will solve that issue. :)

That's exactly it. Right now I maintain an AWS EFS share across multiple servers. I want to migrate towards using AWS ECS Fargate (Docker) using the aforementioned immutable filesystem. According to the author of the Woocommerce plugin:

>  I am using the default upload feature of WordPress.

I looked at his code and that appears to be correct. Tomorrow I'll wire all of this up and see what happens. Thanks!

**Comment by rmccue** [comment]
> That's exactly it. Right now I maintain an AWS EFS share across multiple EC2 instances. I want to migrate towards using AWS ECS Fargate (Docker) using the aforementioned immutable filesystem.

S3 Uploads is designed for essentially this use case; we currently run EC2 instances without a share at all, completely independent drives. (We're also migrating to ECS, which is easier given we're already doing this.)

**Comment by davidbitton** [comment]
> (We're also migrating to ECS, which is easier given we're already doing this.)

We'll need to compare notes.

**Comment by zeroiszero** [comment]
Hi, I am running WordPress with ECS Fargate. With `TaskRoleArn` defined in [Task Definition](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#task_role_arn) 

added `define( 'S3_UPLOADS_USE_INSTANCE_PROFILE', true);` to `wp-config.php` without  `S3_UPLOADS_KEY ` and `S3_UPLOADS_SECRET`
