### ISSUE TITLE
Update URL

### ISSUE THREAD

**Issue by jdonnell01** [humanmade/S3-Uploads#274]
First off, this is a great package and it works quite well! However, I am looking to migrate all of my media to a new S3 bucket. I attempted to update the guid field in the wp_posts table, however all of the images still point to my old S3 bucket. Where are the image URLs stored, and can I change them to my new S3 bucket? Thank you!

**Comment by rmccue** [comment]
GUID is intended as an identifier, so it's not the actual attached image (although happens to also be the URL for historical reasons in WordPress); the real URL is in post meta under the `_wp_attached_file` key.

You can also use the `wp s3-uploads migrate-attachments` wp-cli command to handle this instead.
