### ISSUE TITLE
Exclude folder to sync with S3-Bucket

### ISSUE THREAD

**Issue by DelShahab** [humanmade/S3-Uploads#288]
Hi Guys,

Is there a way to exclude a folder in wp-content/upload/example/ to sync with S3-Bucket?

**Comment by DigitalBella** [comment]
I would also like to know how to do this!! Were you able to find a solution to this?

**Comment by patricskigen** [comment]
I am also interested in a solution for this, if anyone comes across one.

**Comment by jlariza** [comment]
Any news on this?

**Comment by Delgesh** [comment]
Sorry, was not able to solve this issue.

**Comment by joehoyle** [comment]
No, this is not possible with S3 uploads. This plugin is intended to replace your whole local uploads directory.

**Comment by duncanplatt** [comment]
Thank you for this, @rlunden!

Forgive me, where would you place this snippet?

**Comment by rlunden** [comment]
> Thank you for this, @rlunden!
> 
> 
> 
> Forgive me, where would you place this snippet?

For example in functions.php

**Comment by rmccue** [comment]
Note that as you're removing those filters for the rest of the request, any _further_ uploads calls would break, so I would not recommend using this technique. It is highly likely this will cause subtle bugs throughout your application with uploaded files.
