### ISSUE TITLE
Uploading to wrong directory

### ISSUE THREAD

**Issue by mobiusint** [humanmade/S3-Uploads#290]
Hi everyone,
I am running the master version and everything works great via CLI, but for some reason when I try to upload something to the media library it puts it in the bucket, but under a folder with no name. 
I think everything is setup correctly b/c it works from the cli. Any help would be appreciated.

Screenshots below:
![image](https://user-images.githubusercontent.com/10602428/50865840-5e8e5b80-1375-11e9-9492-1f36ca2deb40.png)

![image](https://user-images.githubusercontent.com/10602428/50865820-4c142200-1375-11e9-8593-ae8d944604ed.png)

Thank you!

**Comment by joehoyle** [comment]
As this is old, I'm closing, but re-open if you want.
