### ISSUE TITLE
error unexpected '$value' (T_VARIABLE) in  .../wp-content/plugins/S3-Uploads/lib/aws-sdk/Aws/functions.php on line 36

### ISSUE THREAD

**Issue by OsoBear** [humanmade/S3-Uploads#295]
Running S3-Uploads on a Plesk linux server AWS EC2. The default php for the OS is php 5.4. All web servers are running php 7.3. I have a bashrc for root using an alias to 7.3. 

When I run any WP-CLI commands, I get the error:

error unexpected '$value' (T_VARIABLE) in  .../wp-content/plugins/S3-Uploads/lib/aws-sdk/Aws/functions.php on line 36

If I remove S3-Uploads from the plugin directory, WP-CLI commands work correctly. 

Is it possible to install S3-Uploads specifying with php path to use (Ie to a newer version).

thanks!

**Comment by rmccue** [comment]
You may want to try the following for running wp-cli commands:
```
php $(which wp) s3-uploads ...
```

And swap out `php` for whatever your PHP 7.3 binary is.

This is more of a general wp-cli thing than S3 Uploads though, so closing this out.

**Comment by OsoBear** [comment]
Thanks @rmccue. For anyone who runs into a similar situation, I ended up creating a .bashrc file and added the following:

alias wp='/your/pathto/php/7.3/bin/php /usr/local/bin/wp'

It resolved the issue.
