### ISSUE TITLE
Custom Endpoint Resolution

### ISSUE THREAD

**Issue by bobozar** [humanmade/S3-Uploads#298]
I want to use this awesome plugin with Digitalocean Spaces. But I'm confused on where to place the below custom endpoint. Should it be in the s3-uploads.php or wo-config.php?
```

// Filter S3 Uploads params.
add_filter( 's3_uploads_s3_client_params', function ( $params ) {
	$params['endpoint'] = 'https://your.endpoint.com';
	$params['use_path_style_endpoint'] = true;
	$params['debug'] = false; // Set to true if uploads are failing.
	return $params;
} );
```

**Comment by maturecheese** [comment]
Paste that into your functions.php file within your theme

Obvious to most, but it should say explicitly in the doc

**Comment by roborourke** [comment]
@maturecheese @bobozar yep, sorry. I should note that explicitly, was some assumed knowledge on my part
