### ISSUE TITLE
migrate-attachments doesn't respect bucket_url

### ISSUE THREAD

**Issue by tarfoot** [humanmade/S3-Uploads#300]
I've specified S3_UPLOADS_BUCKET_URL (e.g. media.mybucket.com/uploads/content) in my wp-config.php. New uploads are working just fine. 

However, when I try to use `wp s3-uploads migrate-attachments`, files are being placed in and uploads folder in the root of my bucket, and not media.mybucket.com/content/uploads as I've specified.

**Comment by joehoyle** [comment]
This command has now been removed, as it was never reliable. The preferred approach is to use `upload-directory` and then run a `wp search-replace` if you are also updating the URL to S3.
