### ISSUE TITLE
Uploads going in the wrong Year/month folder 

### ISSUE THREAD

**Issue by pramanikriju** [humanmade/S3-Uploads#303]
I have a multisite WordPress setup.
Behaviour on uploading file - 
Expected URL - `https://AWS-BUCKET.com/uploads/sites/MULTISITE-INDEX/CURRENT-YEAR/CURRENT-MONTH/FILENAME`
Actual URL - `https://AWS-BUCKET.com/uploads/sites/MULTISITE-INDEX/2016/3/FILENAME`

**Comment by rmccue** [comment]
S3 Uploads doesn't change the paths inside the uploads directory, so this is coming from whatever is generating the paths. You'll need to dig into whatever the other code is. :)
