### ISSUE TITLE
Delete local via a function

### ISSUE THREAD

**Issue by emaildano** [humanmade/S3-Uploads#304]
Is it possible to apply the delete-local function in the same way the other settings are applied?

I'm using S3 Uploads without CLI access and it's working out fine, I just need the uploads removed from my local directory after they are uploaded to S3.

**Comment by liarco** [comment]
I'm not sure if I'm getting this right, but this seems to be the default behavior:

- a file is uploaded
- it's moved to S3
- it's deleted from the local drive

This is exactly what I get by simply installing and activating the plugin. Hope this helps...

**Comment by emaildano** [comment]
Hmm.. Maybe I had something wrong. I'll take a look and close this is that's the case. @liarco, thanks!

**Comment by emaildano** [comment]
All good

![giphy](https://user-images.githubusercontent.com/1872327/56592176-21fb0e80-65b8-11e9-9962-8cd245e155e6.gif)
