### ISSUE TITLE
s3-uploads verify no longer works in BETA2

### ISSUE THREAD

**Issue by tristanbes** [humanmade/S3-Uploads#309]
This [PR](https://github.com/humanmade/S3-Uploads/pull/308) breaks the `bin/wp --path=web/wp s3-uploads verify` command since this command is looking for a file `s3-uploads/tests/data/sunflower.jpg` that no longer exists when using composer to donwload the package.

**Comment by Youdaman** [comment]
Can confirm.

**Comment by rmccue** [comment]
@joehoyle Can we re-add this file, or update the `verify` command?

**Comment by joehoyle** [comment]
Ah good catch, we should probably add a new file for those purposes, that is smaller, or maybe just upload a test.txt

**Comment by Kocal** [comment]
Friendly bump

**Comment by joeles** [comment]
Friendly bump.

**Comment by nathanielks** [comment]
This has been fixed in 2.2.1!
