### ISSUE TITLE
Manual Install Zip is Missing

### ISSUE THREAD

**Issue by peledies** [humanmade/S3-Uploads#315]
The following link in the readme does not contain the `manual-install.zip`
> Download the manual-install.zip file from the Releases page and extract the ZIP file to your plugins directory.

Where can this be found?

**Comment by liarco** [comment]
You can find any current/previous version in this page: https://github.com/humanmade/S3-Uploads/releases

Click on the "Assets" section to reveal the downloads ;)

**Comment by mattpramschufer** [comment]
Those files do not contain the /vendor folder nor the /tests folder though

**Comment by laurent-le-graverend** [comment]
+1 manual-install.zip is missing

![image](https://user-images.githubusercontent.com/332246/61428033-056e3880-a953-11e9-8804-c01fa4068804.png)

**Comment by mobiusint** [comment]
+1 manual-install.zip missing

**Comment by jemediacorp** [comment]
Can confirm manual-install.zip is still missing as of 09/16/2019.

**Comment by bam0027** [comment]
I was able to use the "Source Code (zip)" link under the 2.1.0 release. After it was installed, I did need to rename the folder to "S3-Uploads", removing the version.

The /vendor folder was created after I ran "composer install" in the plugin folder.

**Comment by joehoyle** [comment]
We've now automated this, and all new versions published to https://github.com/humanmade/S3-Uploads/releases will have a manual-install.zip
