### ISSUE TITLE
Scaleway should not be recommended

### ISSUE THREAD

**Issue by WebPraktikos** [humanmade/S3-Uploads#319]
Please remove Scaleway from the readme. I signed up there based on your server list without reading reviews (eg., https://www.trustpilot.com/review/scaleway.com). Then, couldn’t remove the bank card. Furthermore, they charged me 2 euros for “verification,” which they haven’t returned (27 days so far).

**Comment by johnbillion** [comment]
Sorry you've had a bad experience, but Scaleway is not a recommendation, it's just listed as an S3 compatible alternative.

**Comment by WebPraktikos** [comment]
The only way people go on these sites without reading reviews is from these “lists.“ Usually, you don’t see fraudulent services in any list of capable services written by reputable and ethical people.
