### ISSUE TITLE
Support for base path in S3

### ISSUE THREAD

**Issue by jonathandietz** [humanmade/S3-Uploads#32]
Thanks for writing this plugin.

Is it possible to add support for using a base path on the S3 key when uploading and downloading assets? Having the option to always prepend an S3 key with something like /wordpress or /staging would be useful. 

For example: "/staging/uploads/some_image_name.jpg"

**Comment by rmccue** [comment]
You can append this to your `S3_UPLOADS_BUCKET` setting, as the constant is used just to build the S3 URL internally. For example:
```php
define( 'S3_UPLOADS_BUCKET', 'some-bucket/staging' );
```

Internally, this would essentially be mapped to `s3://some-bucket/staging/uploads/image.jpg`
