### ISSUE TITLE
rewriting images on multisite

### ISSUE THREAD

**Issue by joshco** [humanmade/S3-Uploads#322]
Is there something special that one needs to do to make image url rewriting work on multisites?
I have the plugin network enabled.  it works on the main site, but the image urls on the other sites are still to the server's wp-content/uploads directory.

All of the content, including the subsites are uploaded into the S3 folder.

**Comment by rmccue** [comment]
Ensure you've network-enabled the site, ideally by placing it into mu-plugins. Also, ensure the constants in your wp-config aren't in any conditionals that could apply them only to a specific site.

Other than that, nothing special needed.

**Comment by bradcdelaney** [comment]
When we moved the plugin to the must-use folder and turned on, the network sites stopped working, returning a fatal PHP error indicating an authentication problem with S3. When we had it in the main folder (network activated) it was working for the main site, but not the network, and accessing the credentials in the wp-config.php file.

Is there something special about configuring the S3 credentials for the network sites other than the main wp-config.php file?

WP Debug log error:

[20-May-2019 20:51:22 UTC] PHP Fatal error:  Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error ex
ecuting "ListObjects" on "https://dependablewp-media.s3.amazonaws.com/?delimiter=%2F&prefix=uploads%2Fwp-personal-dat
a-exports%2F&encoding-type=url"; AWS HTTP error: Client error: `GET https://dependablewp-media.s3.amazonaws.com/?deli
miter=%2F&prefix=uploads%2Fwp-personal-data-exports%2F&encoding-type=url` resulted in a `403 Forbidden` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>56FCD6 (truncated...)
AccessDenied (client): Access Denied - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>56FCD687BF2DF667</RequestId><HostId>AtTFZ6
PsgmwlL60y0jAj2BEanQulWujAhzIRdleLoIN2m//Lx0jdiyZojrvmAAm/0XNYIBi2qvw=</HostId></Error>'
