### ISSUE TITLE
Unknown --dry-run and --sync parameters with upload-directory command

### ISSUE THREAD

**Issue by kodie** [humanmade/S3-Uploads#327]
Running `wp s3-uploads upload-directory content/uploads --sync` or `wp s3-uploads upload-directory content/uploads --dry-run` on the latest plugin version results in

```
Error: Parameter errors:
 unknown --sync parameter
```

and

```
Error: Parameter errors:
 unknown --dry-run parameter
```

**Comment by jemediacorp** [comment]
Receiving the exact same error after installing the plugin for the first time today from a cloned copy of the Git repository (complete with running composer install as the documentation suggests). Here's the plugin info reported by wp-cli:


Plugin S3-Uploads details:
    Name: S3 Uploads
    Status: Active
    Version: 2.1.0-RC2
    Author: Human Made Limited
    Description: Store uploads in S3
