### ISSUE TITLE
AWS-SDK conflict

### ISSUE THREAD

**Issue by zocoloco** [humanmade/S3-Uploads#329]
Hi. I replied to another thread but it was closed before I submitted my reply so I opened a new issue.  I also know this was addressed in issue #299 

The first person who posted has the conflict issue with W3 Total Cache. I'm having the issue with a different plugin - UpdraftPlus. You said S3-Uploads loads the AWS SDK conditionally...but I believe it checks to see if the SDK exists during installation, and if not, it installs the version it require. If the second plugin isn't calling the SDK at that point, it will see it as non-existent. Then the version S3-Uploads installs becomes the constant that is used for all plugins, rather than just S3-Uploads. If a different plugin uses an older version of the SDK, the one S3-updates requires then supersedes it.

From a troubleshooting perspective, this is what makes sense to me. For example:
TEST ONE: one plugin activated requiring the AWS SDK:

UpdraftPlus
results: everything works as expected
TEST TWO: two plugins activated both requiring the AWS SDK:
UpdraftPlus
S3-Uploads
results: UpdraftPlus stops working
TEST THREE: two plugins activated both requiring the AWS SDK:
UpdraftPlus
WP Offload Media Lite
results: everything works as expected

As you mentioned, Total Cache had a constant W3TC_SKIPLIB_AWS constant, to trigger loading the AWS-SDK. I also noticed that in UpdraftPlus code, they have a constant to make sure the correct version of the SDK is called     

`const LATEST_API_VERSION = '2006-03-01';`

But I didn't notice anywhere in S3-uploads code where it specified a version of the AWS-SDK.

I know you're using v3 SDK, while others are still using v2. They're not doing it because they don't want to upgrade, they opting for V2 to have backwards compatibility with PHP versions prior to 5.5.

This was a great read on the same subject:
[https://deliciousbrains.com/dependency-management-wordpress-proposal/](url)

And here was the industry proposal they suggested:
[https://deliciousbrains.com/dependency-management-wordpress-proposal/](url)

Your thoughts? if you set a constant in S3-Uploads, could it help avoid this conflict? Trying to make sense of this so both plugins can be used simultaneously.

**Comment by noplanman** [comment]
@zocoloco Have you managed to solve this somehow? I'm running into the same issue with BackWPup.

(see #377 which might be an option if implemented)

**Comment by joehoyle** [comment]
> The first person who posted has the conflict issue with W3 Total Cache. I'm having the issue with a different plugin - UpdraftPlus. You said S3-Uploads loads the AWS SDK conditionally...but I believe it checks to see if the SDK exists during installation, and if not, it installs the version it require. If the second plugin isn't calling the SDK at that point, it will see it as non-existent. Then the version S3-Uploads installs becomes the constant that is used for all plugins, rather than just S3-Uploads. If a different plugin uses an older version of the SDK, the one S3-updates requires then supersedes it.

This isn't true, no. The plugin does a runtime check in https://github.com/humanmade/S3-Uploads/blob/master/s3-uploads.php#L19, it will only include it's own server of the AWS Sdk if either 1: you have not installed the plugin using `composer`, and / or the AWS SDK has not already been included by another plugin. It is possible that UpdraftPlus is including it's copy of the AWS SDK after S3 Uploads, but no detection in this plugin can fix that case.

I'd recommend you install S3-uploads and UpdraftPlus via composer, so they can both resolve the same copy of the AWS SDK. (Assuming that behaviour is supported in UpdraftPlus)
