### ISSUE TITLE
test folder does not exist when installing using composer

### ISSUE THREAD

**Issue by jlariza** [humanmade/S3-Uploads#332]
Good day,

I installed the plugin using `composer require humanmade/s3-uploads`. I added the configuration, but when I run `wp s3-uploads verify` I get

`PHP Warning:  copy(/path/to/project/wp-content/plugins/s3-uploads/tests/data/sunflower.jpg): failed to open stream: No such file or directory in /path/to/project/wp-project/wp-content/plugins/s3-uploads/inc/class-s3-uploads-wp-cli-command.php on line 30`

and, when I check the plugin folder, I only get these files/folders
![image](https://user-images.githubusercontent.com/16421045/61052887-f36c2300-a3b1-11e9-91b0-cd22d42b9b56.png)

In order to test my configuration, I had to add that file manually.

I even tried downloading the plugin directly from github, downloading the zip file, but the tests folder was not included

Thank you

**Comment by Doocey** [comment]
@jlariza - Did you get it working? I'm facing the same problem, and even adding the above folders/image it still throws the same error.

**Comment by joeles** [comment]
Friendly bump.

**Comment by tkaprol** [comment]
That's correct, I had to clone repository again and copy files into the folder to run it.

**Comment by nathanielks** [comment]
This has been fixed in 2.2.1!
