### ISSUE TITLE
HTTP ERROR 500 if activated

### ISSUE THREAD

**Issue by pcintav** [humanmade/S3-Uploads#335]
Get this if activate the plugin (s3-uploads 2.1.0):
This page isn’t working wwwwww.com is currently unable to handle this request.
HTTP ERROR 500

any idea why?

**Comment by rmccue** [comment]
This isn't enough detail for us to be able to help you. Please provide at least your error log.

Note the [Human Made support policy](https://engineering.hmn.md/projects/support/). We do not offer entry-level support, and you need to be able to debug issues yourself. If you're looking for a more consumer-friendly plugin, [WP Offload Media](https://deliciousbrains.com/wp-offload-media/) may be a good choice.

**Comment by pcintav** [comment]
its weird no error log recorded. Installed booth plugin of yours and the problem are persist.
