### ISSUE TITLE
Conflict with RevSlider 6.x

### ISSUE THREAD

**Issue by tarfoot** [humanmade/S3-Uploads#343]
When using s3-uploads and Slider Revolution 6.x, the page editor will load continuously and will sometimes, timeout.

The apache common access log on my system seems to show that /wp-admin/admin-ajax.php is taking up a lot of processing time.

I *think* this is caused by the PHP Version check on line 71 of s3-uploads.php. I believe the version_compare function requires 'PHP_Version' to come first in the array of arguments. Am I right?

Steps to Reproduce: 

Install Wordpress 5.2.3
Install Plugin: RevSlider 6.1.1
Install Plugin: S3-Uploads 2.1.0
Attempt to edit Sample Page (comes with installation of WP)
Page Editor takes forever to load

Can anyone else confirm that this is an issue?

**Comment by hayes-erick** [comment]
I have the same issue. I have do remoce RevSlider

**Comment by joehoyle** [comment]
@tarfoot while not _impossible_, it's say it's very unlikely that version_compare is causing this. It's quite possible that your Slider plugin is causes excessive reads on files in the uploads directory (which is considered against best-practice).
