### ISSUE TITLE
Multiple Buckets for Same Project

### ISSUE THREAD

**Issue by tkaprol** [humanmade/S3-Uploads#349]
Hello, 

We are using the plugin, thanks for it. In a case I need to store some files in another bucket. 

Like I need to keep files separated in different buckets. Like bucket2019 for images uploaded in 2019, bucket2018 and so on.

I have checked **s3_uploads_s3_client_params** but it just keeps credentials. 

Is there any workaround to set another bucket?

Thanks,

**Comment by joehoyle** [comment]
Hi @tkaprol,

You could use the `s3_uploads_putObject_params` filter for this, which will let you change the bucket on a per-file basis. However, the URL generation might be a bit more tricky. Unless you do something like setup a CloudFront distribution to route your different url prefixes to different bucket, and use a single URL pattern on the front-end / output of the website.
