### ISSUE TITLE
Activating increase server response time

### ISSUE THREAD

**Issue by florianbepunkt** [humanmade/S3-Uploads#350]
When activating the plugin pages load times increase to 3-4 times the previous amount. Not talking about the time the images load, but the initial server response (Time To First Byte) is several seconds.

**Comment by rmccue** [comment]
I believe @joehoyle has a better idea about why this is happening, but my basic understanding is that the AWS connection is a bit slow, and we instantiate the connection on every page load regardless of whether it's used or not.

**Comment by joehoyle** [comment]
No connection is made on every page-load unless you have some, let's say, not-following best practice code which is doing file checks / disk access on the uploads directory on every page load, which I suspect is what is happening here.

S3 Uploads _does_ currently initialize an instance of the AWS SDK / S3Client objects on each page load, which does add a few ms in overhead, which https://github.com/humanmade/S3-Uploads/pull/128 is created to address.

**Comment by florianbepunkt** [comment]
Strange, we do none of the checks you mentioned. For comparison we switched to the S3 CDN feature of W3 total cache and the issue is gone. We use the img srcset attribute quite heavily… maybe this is the culprit and all versions are actually loaded from s3

**Comment by joehoyle** [comment]
WordPress' default srcset generation does not cause of disk-reads on uploaded files, however it's possible you have other plugins that are doing that. I'm going to close this out as "expected behaviour".
