### ISSUE TITLE
Plugin version is not updated

### ISSUE THREAD

**Issue by abazeed** [humanmade/S3-Uploads#359]
The plugin version shows `2.1.0-RC2` after updating the plugin, it should be updated in the [s3-uploads.php](https://github.com/humanmade/S3-Uploads/blob/master/s3-uploads.php) file, line  [7](https://github.com/humanmade/S3-Uploads/blob/bc1df42517c1ccbfbfc61fe4802008d22948a9b8/s3-uploads.php#L7).

**Comment by joehoyle** [comment]
My bad, this will now be fixed in future version per https://github.com/humanmade/S3-Uploads/blob/master/s3-uploads.php#L7
