### ISSUE TITLE
What if we (try to) activate the plugin thru wordpress backend interface?

### ISSUE THREAD

**Issue by bathindahelper** [humanmade/S3-Uploads#364]
It throws an unknown error "There has been a critcial error on your website" when I tried to 'activate' the plugin from wordpress backend (wp-admin) interface. And website stops loading (frontend or backend).

Are we to only activate it thru CLI?
If so, is there only 1 line of command to be given in the terminal window? Can we give that command at root prompt or in some other particular directory/path?

**Comment by pixelbrad** [comment]
Did you add the following constants to your wp-config.php?
```
define( 'S3_UPLOADS_BUCKET', 'my-bucket' );
define( 'S3_UPLOADS_KEY', '' );
define( 'S3_UPLOADS_SECRET', '' );
define( 'S3_UPLOADS_REGION', '' ); // the s3 bucket region (excluding the rest of the URL)
```

**Comment by bathindahelper** [comment]
Oh! Sorry. I didn't/hadn't done that. I'll try that.
