### ISSUE TITLE
Vendor autoload fails after installing via Composer on Windows

### ISSUE THREAD

**Issue by Dynamo6** [humanmade/S3-Uploads#367]
After installing S3-Uploads via Composer on Windows the plugin appears under /wp-content/plugins/s3-uploads however trying to activate it causes a fatal error. This is related to line 22 in s3-uploads.php:

`require_once dirname(__FILE__) . '/vendor/autoload.php';`

The code appears to be looking for a vendor folder *inside* the s3-uploads folder, which does not exist. To fix this issue the code should to be updated as follows:

`require_once ABSPATH . '/vendor/autoload.php';`

This will cause the plugin to look at the site root for the vendors folder.

**Comment by rmccue** [comment]
This is for the bundled autoloader for the standalone version of the plugin; this code is only called if the AWS SDK is not loaded.

When loading via Composer, make sure you're loading the autoloader yourself and this shouldn't occur.
