### ISSUE TITLE
Installation error?

### ISSUE THREAD

**Issue by AdrienPoupa** [humanmade/S3-Uploads#368]
I tried to install the plugin by doing

```
composer require humanmade/s3-uploads
```

at the root of my WordPress installation. Then I enabled it with WP CLI (that I also installed with Composer):

```
vendor/wp-cli/wp-cli/bin/wp plugin activate s3-uploads
```

But I was getting the following error because the dependencies could not be loaded:

```
Warning: require_once(/var/www/wp-content/plugins/s3-uploads/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/wp-content/plugins/s3-uploads/s3-uploads.php on line 21
```

I had to composer install within the plugin directory whereas I thought it would retrieve the dependencies from the root of my WP installation? or am I missing something?

Thanks

Edit: looks like a duplicate of https://github.com/humanmade/S3-Uploads/issues/313

**Comment by codeagencybe** [comment]
Any update yet on this issue? 
I'm having exactly same problem. 

`[21-Jan-2020 11:19:14 UTC] PHP Warning:  require_once(/var/www/demo/wp-content/plugins/S3-Uploads-2.2.1/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/demo/wp-content/plugins/S3-Uploads-2.2.1/s3-uploads.php on line 21
[21-Jan-2020 11:19:14 UTC] PHP Fatal error:  require_once(): Failed opening required '/var/www/demo/wp-content/plugins/S3-Uploads-2.2.1/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/demo/wp-content/plugins/S3-Uploads-2.2.1/s3-uploads.php on line 21
`

**Comment by x0rzkov** [comment]
I could not install the plugin neither

**Comment by rmccue** [comment]
Hi. If you install S3 Uploads via Composer, you need to ensure you're loading Composer's autoload file yourself, and before S3 Uploads is loaded.

This error only happens if you are loading via Composer **and** are not correctly loading Composer's autoload file.

**Comment by AdrienPoupa** [comment]
No, you are the one not doing it correctly... As a user, I expect to be able to install the plugin via Composer from the root of my WP installation, enable it with WP CLI and it should work out of the box.

Having to cd in the plugin's directory to manually install the dependencies is a non sense, and the number of users reacting to this ticket proves it.

**Comment by rmccue** [comment]
You do not need to manually install the dependencies, you need to load Composer's autoloader to ensure the AWS SDK can be correctly loaded. The `require` statement in question is a fallback for non-Composer installs who are using the manually built zips.

S3 Uploads as a package is not meant to load the autoload file itself.

Without the require statement, you'd be seeing a different fatal error stating that the AWS SDK classes are undefined, as they can't be autoloaded.

Please also be aware of [our support policy](https://engineering.hmn.md/projects/support/). :)

**Comment by AdrienPoupa** [comment]
Maybe it's just me then, but I don't understand what is expected when installing it via composer. The readme says:

> Install Using Composer
> 
> composer require humanmade/s3-uploads

This is all that should be needed to install the plugin, right? And I assume this is done at the root of the WP installation.

Since this is not working, I think we either need to update the readme to reflect the correct installation steps for composer, or modify the code to allow loading the autoloader from WP's root.

**Comment by rmccue** [comment]
That's all that's required once you have Composer set up in your project, per [the instructions there](https://getcomposer.org/doc/01-basic-usage.md#autoloading). You'll likely need to add the autoload file to your wp-config.php, or into an mu-plugin. Depending on how you're loading WordPress itself, there may be other steps.

**Comment by codeagencybe** [comment]
I got it working but I had to move some files manually. 
If you run the commands it creates the s3-uploads folder in /wp-contents/plugins/ but the dependencies are in the wrong location (in root) which cause that errors to happen. 
So I had to move the files manually into the same plugin folder and then it works fine. 
None of this is described in your readme, so I agree with @AdrienPoupa if you fail to document, it's normal you get support tickets because you fail to explain the procedure you had in mind with your plugin. 

It's just a few lines extra in your readme to make it better understandable for everybody, I don't see what would harm your "support policy". If you care so much about your time, then documentating is actually saving you more time than rather come back here to elaborate on the steps.

**Comment by codeagencybe** [comment]
Or possibly better, why not upload the manual-install zip like release 2.1.0 RC2 ?

**Comment by AdrienPoupa** [comment]
`You'll likely need to add the autoload file to your wp-config.php, or into an mu-plugin. `
I am using wpackagist and never needed to do that, so I guess this is why this is not working. But yes in this case I think it is worth adding a few lines in the readme to avoid any confusion.

**Comment by AdrienPoupa** [comment]
@codeagencybe using Composer is much better than a zip to manage updates

**Comment by rmccue** [comment]
You're welcome to provide a pull request to add additional documentation if you want :) We don't need that at Human Made, so we are not going to dedicate time to doing so.

**Comment by Zeneixe** [comment]
I have the same problem, this is the only plugin that has this issue among the 10s of plugins I install using composer.

**Comment by Zeneixe** [comment]
I have the same issue, been using s3-uploads for years, just updated to latest version using `composer update` and it broke. Never had any issues with the other tens of plugins I use, what's so different with this plugin?

**Comment by AdrienPoupa** [comment]
Nothing is different except the maintainers' mindset

**Comment by Zeneixe** [comment]
I don't want to flame the maintainers, but please can we have a documented solution?

**Comment by rmccue** [comment]
To be clear: wpackagist doesn't actually install Composer packages, it installs WordPress plugins via Composer. This means they don't need to use Composer's proper architecture, so they don't need the autoload file. Composer [specifically notes that this is required in their installation notes](https://getcomposer.org/doc/01-basic-usage.md#autoloading).

The solution to the original issue is to install Composer's autoloader into your project; our recommended method is to place the autoload loading code into wp-config.

Please also note that S3 Uploads is published as free, open source software, and per our [support policy](https://engineering.hmn.md/projects/support/):
> We design our plugins for other developers. This means that running our plugins involves a certain level of technical proficiency.

If you're looking for a more off-the-shelf consumer solution, try [WP Offload Media](https://deliciousbrains.com/wp-offload-media/), published by our friends at Delicious Brains.

**Comment by Zeneixe** [comment]
@rmccue thanks for your reply, all the other libraries generate an autoload.php file in their folder, plus I have a vendor/autoload.php file in the root folder, so I assume I already "installed autoloader".

**Comment by rmccue** [comment]
Are you requiring the `vendor/autoload.php` in your root folder before S3 Uploads is loaded?

**Comment by Zeneixe** [comment]
Well I have a problem with this, because our root vendor/autoload.php location changes in production after we deploy (was done by a consultant). No, I don't have that require

**Comment by rmccue** [comment]
I'm afraid we can't help much with your specific deployment issues, or the specifics of how to add that line; you may need to ask said consultant how best to enable that. :)

**Comment by Zeneixe** [comment]
Yeah ok, though I'd consider why only this library has this issue in particular, doesn't seem user friendly at all

**Comment by rmccue** [comment]
I've opened #413 to clarify the documentation slightly.

Other plugins (i.e. via wpackagist) "work" because they're a hack to use Composer to install WordPress plugins, but which don't otherwise use Composer fully. S3 Uploads is not a regular WordPress plugin (and we do not publish it on WordPress.org), but rather a standard Composer package. Installing other Composer packages (not wpackagist plugins) would cause similar issues, but which may manifest in other ways.

Ultimately, S3 Uploads is designed for our usage, and while we make it open source for others to use, it's not suitable for everyone. As I noted, WP Offload Media is a great, user-friendly plugin that makes for a good alternative.

**Comment by Zeneixe** [comment]
I understand, thanks for taking the time to explain :)

**Comment by AdrienPoupa** [comment]
Thanks for taking the time to document this, it fixes the original issue.
