### ISSUE TITLE
Attach manual-install.zip for 2.2.1

### ISSUE THREAD

**Issue by karser** [humanmade/S3-Uploads#371]
Hello, could you attach manual-install.zip for 2.2.1, please?

**Comment by codeagencybe** [comment]
Any update yet on this?

**Comment by vdwijngaert** [comment]
[s3-uploads.zip](https://github.com/humanmade/S3-Uploads/files/4702245/s3-uploads.zip) should work :)

**Comment by rmccue** [comment]
Hi, I've uploaded the manual-install to 2.2.1. Also, #415 will automate this so we don't forget in the future.

Apologies for the delay!

**Comment by karser** [comment]
Awesome, thanks! Will update my project then!
