### ISSUE TITLE
WordPress 5.3.2 update breaks S3-Uploads

### ISSUE THREAD

**Issue by conwaydev** [humanmade/S3-Uploads#374]
Heres a video detailing what we're seeing: https://share.getcloudapp.com/v1umGQNv.

### Steps to validate

1) On a clean WordPress install with 5.3.2 install the latest S3-Uploads plugin
2) Try to upload a new piece of media
3) See that you get an AWS error

```
GuzzleHttp\Exception\ClientException: Client error: `GET [S3 bucket]/?delimiter=%2F&prefix=uploads%2F2020%2F01%2F&encoding-type=url` resulted in a `403 Forbidden` response:
<?xml version="1.0" encod in /plugins/S3-Uploads/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 195
```

4) Downgrade your WordPress install to 5.3
5) Try to upload media
6) See that media is uploaded appropriately

**Comment by austinpray** [comment]
Does this happen for you with the latest release? Saw you were on a RC of 2.1

**Comment by jshwlkr** [comment]
I'm seeing this same error on 2.1.0-RC2.

**Comment by conwaydev** [comment]
Right now I'm trying to see if changing the IAM permissions on the AWS user to be able to listObjects on the whole bucket might fix this, but still awaiting a PR on my end. I hope thats all it is, it seems a lot changed with the way WordPress handles media uploads after 5.1.0, as it stands I had to revert all our Wordpresses to 5.2.5 (5.3.0 had some security vulnerabilities 🤕 )

**Comment by conwaydev** [comment]
oh the plugin, this is from the last official release https://github.com/humanmade/S3-Uploads/releases/tag/2.2.1

**Comment by jshwlkr** [comment]
Oh! Same for me. I'm grabbing the latest release, the WP dashboard is reporting it as 2.1.0-RC2.

**Comment by jshwlkr** [comment]
Is there a possibility we could get a response to this issue, @joehoyle or @rmccue (or whoever)? I'm not necessarily asking for a fix, I have some big media heavy sites under my care and I'm wondering whether or not I should wait and hope this issue is resolved for me or bite the bullet and implement a different solution. Apologies if you're busy and I'm just throwing wood on the fire.

**Comment by joehoyle** [comment]
@jshwlkr sorry had missed this, will investigate.

**Comment by conwaydev** [comment]
I was noticing I was having similar issues with the wp-offload-media plugin as well, but I couldn't pinpoint what changed in WP 5.3.1 (or 5.3.2) that did this. I will say adding the ability to `listObjects` for my S3 user didn't actually fix anything and I still continue to see this error.

**Comment by joehoyle** [comment]
Hmm I was not able to reproduce this, to anyone that is seeing this, could you add a copy of the IAM policy document (remove any private information). Also, did you use the `generate-iam-policy` command or some other way of writing the policy?

Thanks!

**Comment by jshwlkr** [comment]
I was not the person to originally set this up (or maintain it until a few months ago), so I'm not sure how the policy was generated.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "folder/*"
            ]
        }
    ]
}
```

**Comment by conwaydev** [comment]
I believe this was created in the console, redacting the bucket name:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": [SID #],
      "Effect": "Allow",
      "Action": [
        "s3:CreateBucket",
        "s3:DeleteObject",
        "s3:Put*",
        "s3:Get*",
        "s3:List*"
      ],
      "Resource": [
        "arn:aws:s3:::[BUCKET]",
        "arn:aws:s3:::[BUCKET]/*"
      ]
    }
  ]
}
```

**Comment by vacas** [comment]
I was going through this problem as well. The thing is we've used this package on an older version of WP (as @conwaydev mentions initially), but we also updated our PHP version from 7.0 to 7.4. When I downgraded our Wordpress and checked the logs, I got a few errors:
```
nginx stderr | [error] 16#0: *24 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/wordpress/wp-content/plugins/S3-Uploads/vendor/aws/aws-sdk-php/src/Api/Parser/PayloadParserTrait.php:44
Stack trace:
#0 /var/www/wordpress/wp-content/plugins/S3-Uploads/vendor/aws/aws-sdk-php/src/Api/Parser/RestXmlParser.php(39): Aws\Api\Parser\RestXmlParser->parseXml(Object(GuzzleHttp\Psr7\Stream), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/wordpress/wp-content/plugins/S3-Uploads/vendor/aws/aws-sdk-php/src/Api/Parser/RestXmlParser.php(31): Aws\Api\Parser\RestXmlParser->parseMemberFromStream(Object(GuzzleHttp\Psr7\Stream), Object(Aws\Api\StructureShape), Object(GuzzleHttp\Psr7\Response))
#2 /var/www/wordpress/wp-content/plugins/S3-Uploads/vendor/aws/aws-sdk-php/src/Api/Parser/AbstractRestParser.php(63): Aws\Api\Parser\RestXmlParser->payload(Object(GuzzleHttp\Psr7\Response), Object(Aws\Api\StructureShape), Array)
#3 /var/www/wordpress/wp-content/plugins/S3-Uploads/vendor/aws/aws-sdk-php/src/S3/Retryable" while reading response header from upstream, client: 172.31.36.128, server: localhost, request: "POST /wp-admin/async-upload.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: ...
```

This made me ponder if the AWS SDK package in the plugin were up to date. So, once I went into the plugin, I noticed that `aws/aws-sdk-php` was on version [3.18](https://github.com/aws/aws-sdk-php/releases/tag/3.18.0), which was released back in April 2016. Once I updated to the latest version ([v3.133.11](https://github.com/aws/aws-sdk-php/releases/tag/3.133.11), which was released yesterday, actually) and I included `php7.4-xml` to my `Dockerfile`, everything seems to be working beautifully. So, there's seems to be a conflict of PHP versions.

Hope this helps.

**Comment by vacas** [comment]
@conwaydev, I was having trouble with the plugin and the latest WP version. I later realized that since the latest WP version uses php7.4, I wasn't installing the necessary packages for php 7.4 in my `Dockerfile` to get this plugin to run correctly. I saw you were using Vagrant - do you have any specific configurations for it?

**Comment by conwaydev** [comment]
@vacas interesting! Upgrading to 7.4 does indeed fix the issue, unfortunately I don't believe our hosting provider supports 7.4. What is the package that was causing the trouble?

**Comment by vacas** [comment]
It was `php7.4-xml`, which fixed the issues for me.

**Comment by vacas** [comment]
@conwaydev - Let me correct myself: I wasn't having issues with `php7.4-xml`, I just didn't install it in my container. Since we were coming from php 7.0, it wasn't needed in a past version of the S3-Uploads plugin or WP, but for php 7.4, it is necessary.

**Comment by vacas** [comment]
Also, pondering on this last night, @joehoyle, might be a good idea to document something around the WP and PHP versions in the Readme. Other than that, @conwaydev, would you say this issue is good to close?

**Comment by conwaydev** [comment]
Yeah apologies I'll close! 

In other inexplainable news the bug isn't happening for me anymore? There were a couple moving parts to this, but I'm seeing it upload totally fine on PHP 7.3 in that exact vagrant container. Its possible that updating our IAM user to allow to perform the actions on the whole bucket may have fixed my initial issue.

**Comment by vacas** [comment]
Well, good to hear you found a solution that works, friend. Cheers! 🍻

**Comment by joehoyle** [comment]
@vacas yes, if we are missing a `Requirements` section on say, what PHP Modules you need, that would be great!

**Comment by vacas** [comment]
@joehoyle, I'll take a look into this during next week
