### ISSUE TITLE
Move config to functions for Multisite and multiple objects

### ISSUE THREAD

**Issue by chuckingit** [humanmade/S3-Uploads#384]
Hi - this plugin looks promising ... I'm wondering if there is a way to move the config settings to a functions.php or custom plugin setting this way I could use your plugin on multiple sites on a multisite install, each having their own object S3 area vs one big default section for an entire network ..??.. thanks in advance for pointers to tweak code (if applicable) ... cordially, chuck scott

**Comment by joehoyle** [comment]
Hi @chuckingit,

Interesting idea. This might be doable with the existing hooks, but I think is not likely something we'd support directly in the plugin. WordPress assumed that all sites store their files within the same base dir, and changing that expectation could have unwanted bugs and side effects. it may wirk for you usecase, but I don't think it's something we'd build in.

If you do try to use the existing filters and hooks in S3 Uploads, and those are not powerful enough to echeive this, I'd be happy to atleast accept PRs for hooks that would make this more possible.
