### ISSUE TITLE
Verification do not working with custom s3 like service

### ISSUE THREAD

**Issue by polRk** [humanmade/S3-Uploads#385]
I'm using s3 digital ocean spaces

wp-config.php
```
define( 'WP_DEBUG', 'true' );
define('WP_PLUGIN_DIR', '/bitnami/wordpress' . '/wp-content/plugins');
define( 'S3_UPLOADS_REGION', 'fra1' );
define( 'S3_UPLOADS_BUCKET', 'highseason' );
define( 'S3_UPLOADS_KEY', 'secret' );
define( 'S3_UPLOADS_SECRET', 'secret' );
define( 'S3_UPLOADS_BUCKET_URL', 'https://cdn.highseason.pro' );
```

wp s3-uploads verify
```
wordpress@highseason-dev-6bc5bfbcdc-7jlv6:/$ wp s3-uploads verify
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /bitnami/wordpress/wp-content/plugins/s3-uploads/lib/getid3/getid3.php on line 554
Deprecated: Array and string offset access syntax with curly braces is deprecated in /bitnami/wordpress/wp-content/plugins/s3-uploads/lib/getid3/getid3.php on line 554
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /bitnami/wordpress/wp-content/plugins/s3-uploads/lib/getid3/getid3.php on line 555
Deprecated: Array and string offset access syntax with curly braces is deprecated in /bitnami/wordpress/wp-content/plugins/s3-uploads/lib/getid3/getid3.php on line 555
Attempting to upload file s3://highseason/uploads/503469681.txt
PHP Warning:  Error executing "PutObject" on "https://highseason.s3.fra1.amazonaws.com/uploads/503469681.txt"; AWS HTTP error: cURL error 6: Could not resolve host: highseason.s3.fra1.amazonaws.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /bitnami/wordpress/wp-content/plugins/s3-uploads/inc/class-s3-uploads-stream-wrapper.php on line 835
Warning: Error executing "PutObject" on "https://highseason.s3.fra1.amazonaws.com/uploads/503469681.txt"; AWS HTTP error: cURL error 6: Could not resolve host: highseason.s3.fra1.amazonaws.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /bitnami/wordpress/wp-content/plugins/s3-uploads/inc/class-s3-uploads-stream-wrapper.php on line 835
PHP Warning:  copy(s3://highseason/uploads/503469681.txt): failed to open stream: "S3_Uploads_Stream_Wrapper::stream_open" call failed in /bitnami/wordpress/wp-content/plugins/s3-uploads/inc/class-s3-uploads-wp-cli-command.php on line 30
Warning: copy(s3://highseason/uploads/503469681.txt): failed to open stream: "S3_Uploads_Stream_Wrapper::stream_open" call failed in /bitnami/wordpress/wp-content/plugins/s3-uploads/inc/class-s3-uploads-wp-cli-command.php on line 30
Error: Failed to copy / write to S3 - check your policy?
```

**Comment by polRk** [comment]
Update wp-config.php
```
define('WP_PLUGIN_DIR', '/bitnami/wordpress' . '/wp-content/plugins');
define( 'S3_UPLOADS_REGION', 'fra1' );
define( 'S3_UPLOADS_BUCKET', 'highseason' );
define( 'S3_UPLOADS_KEY', 'key' );
define( 'S3_UPLOADS_SECRET', 'key' );
define( 'S3_UPLOADS_BUCKET_URL', 'cdn.highseason.pro' );
define( 'S3_UPLOADS_ENDPOINT', 'fra1.digitaloceanspaces.com' );
```

restart
```
   28  wp plugin activate s3-uploads
   29  wp plugin deactivate s3-uploads
   30  wp plugin activate s3-uploads
   31  wp s3-uploads verify
   32  history
```

wordpress@highseason-dev-6bc5bfbcdc-7jlv6:/$ wp s3-uploads verify
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /bitnami/wordpress/wp-content/plugins/s3-uploads/lib/getid3/getid3.php on line 554
Deprecated: Array and string offset access syntax with curly braces is deprecated in /bitnami/wordpress/wp-content/plugins/s3-uploads/lib/getid3/getid3.php on line 554
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /bitnami/wordpress/wp-content/plugins/s3-uploads/lib/getid3/getid3.php on line 555
Deprecated: Array and string offset access syntax with curly braces is deprecated in /bitnami/wordpress/wp-content/plugins/s3-uploads/lib/getid3/getid3.php on line 555
Attempting to upload file s3://highseason/uploads/1610446858.txt
PHP Warning:  Error executing "PutObject" on "https://highseason.s3.fra1.amazonaws.com/uploads/1610446858.txt"; AWS HTTP error: cURL error 6: Could not resolve host: highseason.s3.fra1.amazonaws.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /bitnami/wordpress/wp-content/plugins/s3-uploads/inc/class-s3-uploads-stream-wrapper.php on line 835
Warning: Error executing "PutObject" on "https://highseason.s3.fra1.amazonaws.com/uploads/1610446858.txt"; AWS HTTP error: cURL error 6: Could not resolve host: highseason.s3.fra1.amazonaws.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /bitnami/wordpress/wp-content/plugins/s3-uploads/inc/class-s3-uploads-stream-wrapper.php on line 835
PHP Warning:  copy(s3://highseason/uploads/1610446858.txt): failed to open stream: "S3_Uploads_Stream_Wrapper::stream_open" call failed in /bitnami/wordpress/wp-content/plugins/s3-uploads/inc/class-s3-uploads-wp-cli-command.php on line 30
Warning: copy(s3://highseason/uploads/1610446858.txt): failed to open stream: "S3_Uploads_Stream_Wrapper::stream_open" call failed in /bitnami/wordpress/wp-content/plugins/s3-uploads/inc/class-s3-uploads-wp-cli-command.php on line 30
Error: Failed to copy / write to S3 - check your policy?

**Comment by polRk** [comment]
Variable S3_UPLOADS_BUCKET_URL is defined
```
PHP Notice:  Constant S3_UPLOADS_BUCKET_URL already defined in phar:///opt/bitnami/wp-cli/bin/wp-cli.phar/vendor/wp-cli/eval-command/src/Eval_Command.php(37) : eval()'d code on line 1

$ wp eval 'define( "S3_UPLOADS_BUCKET_URL", "cdn.highseason.pro" );'
```

**Comment by noplanman** [comment]
The problem here seems to be the connection to the host, which is failing:
`AWS HTTP error: cURL error 6: Could not resolve host: highseason.s3.fra1.amazonaws.com`

@polRk Are you sure you have the correct host name?

**Comment by polRk** [comment]
@noplanman I **DO NOT USE** amazonaws.com, i use DO Spaces

**Comment by polRk** [comment]
I fix that by changing `S3_UPLOADS_ENDPOINT = https://fra1.digitaloceanspaces.com`, `S3_UPLOADS_BUCKET_URL  =  highseason.fra1.digitaloceanspaces.com`

**Comment by polRk** [comment]
But, it working not good. It upload files to s3://bucket/**highseason**, why your code add sub path highseason ?

As a result, I deleted the plugin because the plugin didn't upload files to s3 after I uploaded files via wp-admin media. Only manual trigger worked.

**Comment by rmccue** [comment]
Please note that we do not offer detailed support here, and as we don't use S3-like services, we can't offer help with that. See our [support policy](https://engineering.hmn.md/projects/support/).

As noted in the documentation, [`S3_UPLOADS_BUCKET_URL` is used for the URL to serve images from](https://github.com/humanmade/S3-Uploads#url-rewrites). Custom endpoints use [a different style of configuration](https://github.com/humanmade/S3-Uploads#custom-endpoints) via the `s3_uploads_s3_client_params` filter. `S3_UPLOADS_ENDPOINT` is **not** an official configuration option, and will have no effect (unless you happen to be using the very outdated #268 branch, which you should not).

**Comment by pixeldevsio** [comment]
In case anyone else runs into the issue of Digital Ocean not working with the S3 plugin. Here's a quick guide of how to get it working.

https://gist.github.com/pixeldevsio/4509cea4c158da85e94804072c9ab915
