### ISSUE TITLE
Error installing from 2.2.1 zip

### ISSUE THREAD

**Issue by mattmuller** [humanmade/S3-Uploads#388]
Hi, I have unzipped 2.2.1 and FTP'd into the plugins folder and checked the permissions.

I have set all the config data in wp-config.

I have renamed it S3-Uploads and then Im running wp plugin activate S3-Uploads.

I get the following errors...

`Warning: require_once(/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/S3-Uploads/vendor/autoload.php): failed to open stream: No such file or directory in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/S3-Uploads/s3-uploads.php on line 21
PHP Fatal error:  require_once(): Failed opening required '/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/S3-Uploads/vendor/autoload.php' (include_path='.:/opt/bitnami/php/lib/php') in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/S3-Uploads/s3-uploads.php on line 21
Fatal error: require_once(): Failed opening required '/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/S3-Uploads/vendor/autoload.php' (include_path='.:/opt/bitnami/php/lib/php') in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/S3-Uploads/s3-uploads.php on line 21`

Does anyone know why I'm getting these errors, please?

Thanks,

Matt

**Comment by heathera2016** [comment]
How did you solve this problem?
