### ISSUE TITLE
[info] - the 2nd part of the equation

### ISSUE THREAD

**Issue by 7php** [humanmade/S3-Uploads#407]
Hi,
I understand that s3-uploads is for background (or manual w.r.t to cli) uploading of assets on S3.

For the 2nd part of the equation, which is serving assets from the S3, for that what do you use?

**Comment by 7php** [comment]
my bad, I think this solves: https://github.com/humanmade/S3-Uploads#url-rewrites

**Comment by rmccue** [comment]
We use Tachyon for serving images: https://github.com/humanmade/tachyon
