### ISSUE TITLE
Behaviour of S3_UPLOADS_AUTOENABLE

### ISSUE THREAD

**Issue by rubas** [humanmade/S3-Uploads#408]
`S3_UPLOADS_AUTOENABLE` is not behaving as expected based on the [documentation](https://github.com/humanmade/S3-Uploads#default-behaviour).

You can **not** overwrite the behaviour just with `S3_UPLOADS_AUTOENABLE = false`. You also need to `set_option('s3_uploads_enabled')` to something that is not  `enabled`.

https://github.com/humanmade/S3-Uploads/blob/master/s3-uploads.php#L109
```
/**
 * Check if URL rewriting is enabled.
 *
 * Define S3_UPLOADS_AUTOENABLE to false in your wp-config to disable, or use the
 * s3_uploads_enabled option.
 *
 * @return bool
 */
function s3_uploads_enabled()
{
  // Make sure the plugin is enabled when autoenable is on
  $constant_autoenable_off = (defined('S3_UPLOADS_AUTOENABLE') && false === S3_UPLOADS_AUTOENABLE);

  if ($constant_autoenable_off && 'enabled' !== get_option('s3_uploads_enabled')) {                         // If the plugin is not enabled, skip
    return false;
  }

  return true;
}
```

**Comment by 7php** [comment]
this code here seems ambiguous:
`if ($constant_autoenable_off && 'enabled' !== get_option('s3_uploads_enabled'))`

should probably use an OR `||` instead of AND `&&` ?
