### ISSUE TITLE
Fatal error where /vendor/autoload.php doesn't exist

### ISSUE THREAD

**Issue by tylerlindell** [humanmade/S3-Uploads#414]
getting a fatal error stating No such file or directory in /wp-content/plugins/S3-Uploads-2.2.1/vendor/autoload.php.

Installed plugin through WP UI plugin upload zip

I have installed AWS SDK via composer although, the autoload.php file is located in composer's default vendor directory.

How do I fix this? Thanks

**Comment by rmccue** [comment]
Hi! S3 Uploads is trying to load `vendor/autoload.php` because the AWS SDK isn't loaded.

We just updated the docs in #413; can you make sure you have the `require_once` line noted [here](https://github.com/humanmade/S3-Uploads#install-using-composer) in your `wp-config.php`?

**Comment by tylerlindell** [comment]
it says to use `__DIR__` but that points to my WP directory but the `autoload.php` file is located in my home directory. Maybe not the same for others but thanks for pointing me in this direction. 

I'm using an EC2 instance with the bitnami image but maybe this will work for more people if composer's vendor directory is located in the "HOME" location as well.

I was able to solve it with this
```
require_once $_SERVER['HOME'] . '/vendor/autoload.php';
```

**Comment by rmccue** [comment]
👍 Each setup will be slightly different, so it may need adjusting. This issue at least will appear in search results if anyone else is using Bitnami :)

Closing out.
