### ISSUE TITLE
Should we remove type hinting on wp_get_attachment_image_src because of WordPress?

### ISSUE THREAD

**Issue by stuartshields** [humanmade/S3-Uploads#416]
@joehoyle So I'm working on the Secure Media stuff and came across this error:
```
Uncaught Error: Argument 2 passed to S3_Uploads::add_s3_signed_params_to_attachment_image_src() must be of the type integer, string given
```

This is happening because we expect $post_id to only be `int`: 
https://github.com/humanmade/S3-Uploads/blob/master/inc/class-s3-uploads.php#L486

However in WordPress if you do something like:
```
wp_get_attachment_image_src( get_post_thumbnail_id( get_the_ID() ), 'full', false )
```

`get_post_thumbnail_id` returns int|string:
```
(int|string) Post thumbnail ID or empty string if the post does not exist.
```
reference: https://developer.wordpress.org/reference/functions/get_post_thumbnail_id/

Thoughts on this? As it may break other projects code.

**Comment by joehoyle** [comment]
Hrm is this string(0) @stuartshields? Per https://3v4l.org/qotFg, it looks like this error should only be triggered if it's passed `""`, because `"1"` will be cast to an int.

**Comment by joehoyle** [comment]
So, yes, looks like we will need to remove this typehint, unfortunately,.

**Comment by Koli14** [comment]
> So, yes, looks like we will need to remove this typehint, unfortunately,.

I have created a PR for this: https://github.com/humanmade/S3-Uploads/pull/458
