### ISSUE TITLE
Guzzle error

### ISSUE THREAD

**Issue by AlanJIsaacson** [humanmade/S3-Uploads#419]
We are getting the error below when trying to verify the plugin. We have tried changing the thrown Error to a Throwable as suggested in a potential github hotfix, which prevented this error, however the plugin then uploads zero-byte files to the bucket. 

We do have versioning enabled on the bucket.

PHP 7.3.17
All PHP mods match a similiar server that has no issues.

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Aws\Handler\GuzzleV6\GuzzleHandler::Aws\Handler\GuzzleV6\{closure}() must be an instance of Exception, instance of Error given, called in /data/var/www/vhosts/expansion/staging/releases/8/web/content/plugins/S3-Uploads/vendor/guzzlehttp/promises/src/Promise.php on line 203 and defined in /data/var/www/vhosts/expansion/staging/releases/8/web/content/plugins/S3-Uploads/vendor/aws/aws-sdk-php/src/Handler/GuzzleV6/GuzzleHandler.php:45`

**Comment by joehoyle** [comment]
@AlanJIsaacson do you have any other plugins (or other deps) that are using Guzzle? I've seen this kind of thing happen when the wrong version of Guzzle has been loaded by another autoloader or plugin.

**Comment by AlanJIsaacson** [comment]
Thank you very much @joehoyle we disabled another plugin using Guzzle and it worked immediately. My be one for you to list as a check in the docs somewhere, especially if verify fails. 

Thanks again
