### ISSUE TITLE
Img src still set to the local disk url even after uploading to S3

### ISSUE THREAD

**Issue by ishwinder** [humanmade/S3-Uploads#424]
We had a wordpress install with existing media that we uploaded to Amazon S3 using wp cli command mentioned in readme. Everything worked well however the `src` attribute of the image that already existed in the media library is still set to the local directory on the server. The `srcset` attribute is set fine to s3 bucket though.

The problem doesn't occur with newly uploaded images into the media gallery(Their `src` and `srcset` attributes both point to S3). Would appreciate help on direction in which we should debug.

**Comment by joehoyle** [comment]
Hi @ishwinder,

When you run the WP CLI command to upload files to S3, you'll also need to manually run a `wp search-replace` to update all image URLs the database to point to the S3 url.
