### ISSUE TITLE
Great work! Thanks A LOT! Appreciate it so much BUT...

### ISSUE THREAD

**Issue by gitmko0** [humanmade/S3-Uploads#428]
How do i sha256 the file and name it as directory in s3?

e.g. new.jpg
$sharesults = sha256("new.jpg"); <-- the content of new.jpg

testing.s3.amazon.com/......../$sharesults/new.jpg?

how do i do this?

**Comment by roborourke** [comment]
You can work with S3 using PHP's file system functions and the `s3://` protocol. This plugin adds a stream wrapper protocol meaning you can reference files as if they were on a file system using a path like this for example: `s3://bucket-name/path/to/file.jpg`.

In your case it would be something like:

```php
$file = 'new.jpg'; // Assuming this is an existing file.
$s3_path = sprintf( 's3://%s/%s/%s', S3_UPLOADS_BUCKET, sha256( $file ), $file );
copy( $file, $s3_path );
```

**Comment by gitmko0** [comment]
where do i input the above line?

**Comment by rmccue** [comment]
You would want to put this into a separate plugin and hook into the relevant upload functions in WordPress to rename the file/directory; this might be best to do before it gets to S3 Uploads at all.

Please also note [our support policy](https://engineering.hmn.md/projects/support/), as we're unable to offer super detailed support :)

**Comment by gitmko0** [comment]
this seemed to be a very easy add_filter / add_action hook thing for you guys.
care to share the code here?

can someone pls help? basically it will be better if we can just symlink using the sha256 so duplicate files can have duplicate names BUT the data will be stored only once.

function changefilenameupload() {
   $file = 'new.jpg'; // Assuming this is an existing file.  
   $s3_path = sprintf( 's3://%s/%s/%s', S3_UPLOADS_BUCKET, sha256( $file ), $file );
   copy( $file, $s3_path );
}

add_filter('whatfilteristhis','changefilenameupload',99,0?);

**Comment by roborourke** [comment]
If you want to prevent duplicate files being stored then it's far more complicated, certainly not an easy `add_action` / `add_filter` call I'm afraid!

The above code isn't actually doing what you want either, I misunderstood and thought you wanted an `sha` hash of the file name not the file contents. You might hit PHP memory limit problems trying to hash the file contents if the image is big.

To be honest given that S3 storage is so cheap and you want the files to be accessed by different names anyway it's not really worth the effort of trying to do this in my opinion.

Ultimately we can't give you the answer you're after here really as it'd be a custom feature and custom development work so not something that comes under the support we offer so I'm going to close this out. You could try over on the WordPress stack exchange site but it's going to take some fairly deep knowledge of WP and S3 to get the result you're after.

**Comment by gitmko0** [comment]
please dont close this thread. i'm sure there are helpful people who can help.

yes s3 is very cheap BUT will put another CDN in front to make it cheaper for the bandwidth. 
Can anyone help with this?

Can  you not close this?
