### ISSUE TITLE
Response time increases 500ms-1000ms after enabling the plugin

### ISSUE THREAD

**Issue by adamithk** [humanmade/S3-Uploads#431]
I don't know if anyone else has noticed this, but after enabling the plugin, calling an endpoint I get an increased response time by a significant amount. It's just retrieving advanced custom field content for one post. I have similar results with other wordpress S3 plugins, so I'm wondering what needs to be done to prepend the cloudfront url to the image path. Surely it shouldn't add that much overheard to an api call?

Or is it a caching issue?

Perhaps someone can shed some light on their configuration.

I'm using Wordpress 5.4.2 with S3 Uploads 2.2.2.

Thanks

**Comment by joehoyle** [comment]
It sounds like you have some code that is checking file contents of uploads on every page load. Something like `getimagesize()` for example. By default, WordPress will not do that so perhaps your theme or plugins are responsible.
