### ISSUE TITLE
Fantastic work! How do i prevent specific directory from being uploaded to s3?

### ISSUE THREAD

**Issue by gitmko0** [humanmade/S3-Uploads#432]
Fantastic work! How do i prevent specific directory from being uploaded to s3?

I'm using fast velocity minify cache and a site/[site_id]/cache directory is created. 

how do i prevent this cache folder from being uploaded to s3? only this cache folder.

this is my final question regarding this plugin. thx for the hard work.

**Comment by joehoyle** [comment]
Hi @gitmko0, you'd have to change where the cache directory is configured. S3 uploads doesn't support having any excludes. If you can use filters or settings for the plugin that wants to make use of a cache DIR to instead store it's cache at something like `/tmp` that might be a better approach.
