### ISSUE TITLE
can you make this plugin hhvm compatible?

### ISSUE THREAD

**Issue by gitmko0** [humanmade/S3-Uploads#440]
that'll make this plugin perfect

**Comment by joehoyle** [comment]
What is specifically incompatible right now? We don't use or test on HHVM, but I'd be ok with PRs than fix simple issues.

**Comment by rmccue** [comment]
To address the original title here: we don't use HHVM, so we don't intend on doing any work to support it from our side, per our [support policy](https://engineering.hmn.md/projects/support/). We're happy to accept any pull requests that would improve this, provided they don't increase our support and maintenance burden.

**Comment by gitmko0** [comment]
i havent tested but do u think hhvm will work with this plugin?

**Comment by rmccue** [comment]
No idea, but be aware that HHVM [has dropped compatibility with PHP](https://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html) so there's no guarantees. I'd recommend trying it yourself.
