### ISSUE TITLE
Version configuration option missing for client.

### ISSUE THREAD

**Issue by natereist** [humanmade/S3-Uploads#442]
Unable to get this configured due to the following error:

`Fatal error: Uncaught InvalidArgumentException: Missing required client configuration options: 
version: (string)`

I did try adding a filter to `s3_uploads_s3_client_params` to set a version like below in a mu-plugin file:

`<?php
// Filter S3 Uploads params.
add_filter( 's3_uploads_s3_client_params', function ( $params ) {
	$params['version'] = "2006-03-01";
	return $params;
} );`

Any idea what I might be missing? I'm running php 7.4, WordPress 5.5, ubuntu 18.04

**Comment by joehoyle** [comment]
Hmm I have not seen that before, can you make sure it still does this with no other plugins activated?

**Comment by natereist** [comment]
After trying that in a few locations I'm consistently getting a different error when trying to run `wp s3-uploads create-iam-user`:

`PHP Fatal error:  Uncaught Error: Class 'Aws\Common\Aws' not found in /Users/natereist/Local Sites/s3test/app/public/wp-content/plugins/S3-Uploads/inc/class-s3-uploads-wp-cli-command.php:76`

This is a fresh install of WordPress with no other plugins and using twentytwenty.

Couple other notes that might effect this, so i'll include them :) 

- Running on Local (by flywheel) for this, but I did try on a droplet running ubuntu.
- I cloned the git repo, not installed via composer, and I am 3.0.0-beta currently. Maybe there is a different branch I should use?
- I ran `composer install` in the S3-Uploads plugin directory on my machine (mac), not in the docker container in Local.

This is my first time trying this plugin, so I'm sure I'm missing something lol.

Thanks!

**Comment by natereist** [comment]
I found the issue with this after some more testing. 

There was an SES factory using arguments that didn't jive with the SDK loaded in with this plugin. I had been using another (likely older) AWS SDK before. I've corrected the arguments ( credentials and version ) there and it resolved to work.
