### ISSUE TITLE
Imagify / webp format images

### ISSUE THREAD

**Issue by belthaZornv** [humanmade/S3-Uploads#444]
Firstly, good work on the plugin, it's easy to use and works well! - I just have one question in regards to webp/imagify images not appearing in S3 - is this a known behaviour? is there any setting that I can set so other formats are detected and moved to S3? 

Also seems like using: 

```define( 'S3_UPLOADS_DISABLE_REPLACE_UPLOAD_URL', true );```

Still replaces and rewrites some URLs, such as the one used by Imagify (url replaced to s3://bucketname...) - and it only switches off if I use the autoenable setting.

**Comment by belthaZornv** [comment]
I've managed to go around the `rewriting` by specifying the `define( 'S3_UPLOADS_BUCKET_URL', 'https://your.origin.url.example/path' );` setting. - Could you kindly guide me towards where the upload is happening (so I can extend and add the .webp images from imagify)?

**Comment by belthaZornv** [comment]
I've used `inotifywait` to upload `.webp` images to the S3 bucket; although I'm still stuck on the rewriting the URLs to `s3://bucketname/...` it's not the whole hostname anyway.

**Comment by belthaZornv** [comment]
managed to use AWS CLI + Inotify - thanks for your work.

**Comment by tiggeymone** [comment]
Hello beltha, I'm interested in this topic, can you share the configuration you used to perform the conversion from standard image to webp, and then the URL rewriting? Thank you in advance!
