### ISSUE TITLE
Error executing "PutObject" using add_filter

### ISSUE THREAD

**Issue by qant** [humanmade/S3-Uploads#446]
I was looking to implement you wonderful plugin for s3 scaleway storage with your filter:

```
// Filter S3 Uploads params.
add_filter( 's3_uploads_s3_client_params', function ( $params ) {
	$params['endpoint'] = 'https://s3.fr-par.scw.cloud';
	$params['use_path_style_endpoint'] = true;
	$params['debug'] = true; // Set to true if uploads are failing.
	return $params;
} );
```

Then i run:  `wp s3-uploads verify` But is not working because i see en debug this warning and the URL is still use "**amazonaws.com**" part instead of "**scw.cloud**" provided with filer:

```[22-Sep-2020 16:36:06 UTC] PHP Warning:  Error executing "PutObject" on "https://compbcn.s3.fr-par.amazonaws.com/uploads/1222095858.txt"; AWS HTTP error: cURL error 6: Could not resolve host: compbcn.s3.fr-par.amazonaws.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://compbcn.s3.fr-par.amazonaws.com/uploads/1222095858.txt in....```

Why is not working? What i can do?

**Comment by SergeyPichugin** [comment]
Hi @qant , im replaced url in plugin file class-s3-uploads.php

line 140

return apply_filters ('s3_uploads_bucket_url', 'https: //'. $ bucket. '.HERE WAS URL AMAZON'. $ path);

it worked for me, but I think it's not very good to do this

**Comment by mxkyb** [comment]
Where did you put that snippet?

**Comment by rmccue** [comment]
You can define `S3_UPLOADS_BUCKET_URL` to set the URL:

```php
define( 'S3_UPLOADS_BUCKET_URL', 'https://your-bucket-url.example.com' );
```

Alternatively, you can filter `s3_uploads_bucket_url`.

Please note that [per our support policy](https://engineering.hmn.md/projects/support/) we're unable to offer further detailed support.
