### ISSUE TITLE
How about doing another CF-Uploads to upload to cloudflare workers' storage?

### ISSUE THREAD

**Issue by gitmko0** [humanmade/S3-Uploads#453]
How about doing another CF-Uploads to upload to cloudflare workers' storage?
Cloudflare Workers' storage is cheaper in terms of bandwidth. Possible to get this done as part of the roadmap?

**Comment by joehoyle** [comment]
Hey @gitmko0, thanks for the suggestion.

Unless CloudFlare Storage is API compatible with AWS S3, then this is outside the scope of this plugin. You are of course welcome to fork S3 Uploads as a starting point.

If CloudFlare storage is API compatible, S3 Uploads already supports using custom S3 endpoints. 

Thanks!
