### ISSUE TITLE
Please update dependency aws-sdk-php

### ISSUE THREAD

**Issue by vijayant123** [humanmade/S3-Uploads#455]
Hello,

Thanks for this awesome plugin. Please update the dependencies on this plugin. You use a very old version of aws-sdk-php and this causes other plugins that use this package to fail. For example BackWPup that uses s3 to store backups keeps failing when s3-uploads is active. This issues is present in other s3 backup plugins too when used with s3-uploads. Please look into updating this plugin and also publishing it on Wordpress.org

**Comment by joehoyle** [comment]
Hi @vijayant123 we have no plans to release this plugin on WordPress.org. The current composer constraint is "~3.18", which I believe should also capture the latest version of the AWS SDK.
