### ISSUE TITLE
Using on-demand pre-signed URLs for S3 upload?

### ISSUE THREAD

**Issue by dtbaker** [humanmade/S3-Uploads#460]
Hello,

We would like to move away from generating long lived AWS access keys for S3. 

I'm wondering if you have seen any implementations where your plugin can fetch a pre-signed upload URL from an API endpoint when it needs to perform an upload?

This would make us more comfortable using the plugin with more SaaS providers, as we could control secret rotation and any sort of acls centrally in house while offloading the WordPress hosting side of things. 

If you haven't seen that type of implementation before, I'd love to give it a crack, so open to suggestions on best places to integrate (or even if you've got another idea like hooking into a filter that returns temporary AWS access keys via our API to avoid the long lived ones).

Thanks heaps!

**Comment by joehoyle** [comment]
Hi @dtbaker,

Good question! Short answer: no, S3-Uploads is a drop-in replacement for the filesystem storage of WordPress, it doesn't really change anything to do with how files are uploaded. What you are talking about here is more like custom upload functionality using presigned upload URLs that needs custom work to be done client side (like in the WordPress media library).

We run S3-Uploads in AWS, so all machines authentice with IAM profiles, not AWS access keys / tokens (well, technically they are short-lived access keys and tokens, but their rotation and management is handled by EC2).

**Comment by dtbaker** [comment]
Thanks @joehoyle ! 

I might try to hook in a lambda that returns a shot lived access key so we can manage that kind of thing from our side. Cheers
