### ISSUE TITLE
Possible to use CDN / rewritten url to call the the media library file instead of accessing S3 all the time?

### ISSUE THREAD

**Issue by gitmko0** [humanmade/S3-Uploads#462]
Each time accessing S3 backend is costly due to the transaction cost involved.
Possible to reduce this using the rewritten url? I've already used the CDN but it seems this plugin is still incurring higher cost of transactional access to s3 backend.

**Comment by joehoyle** [comment]
Yes, we support using a different URL than S3 in https://github.com/humanmade/S3-Uploads#url-rewrites. You can then set up CloudFront with a S3 origin, and use https://github.com/humanmade/S3-Uploads#url-rewrites to point to the CloudFront distribution.
