### ISSUE TITLE
If already using url rewrite to offload to CDN, possible to minimize the network call to s3 directly?

### ISSUE THREAD

**Issue by hiqsociety** [humanmade/S3-Uploads#463]
If already using url rewrite to offload to CDN, possible to minimize the network call to s3 directly?
Maybe I'm using some plugins / themes etc but my s3 costs is very high. possible to reduce this by leveraging on the rewritten url and lesser call towards s3?

**Comment by joehoyle** [comment]
See https://github.com/humanmade/S3-Uploads#url-rewrites for a note on how to use this with a CDN like CloudFlare for CloudFront.
