### ISSUE TITLE
Can I also use this to load css and javascript

### ISSUE THREAD

**Issue by fahaadsheikh** [humanmade/S3-Uploads#465]
I see it is a very good resource for the media library, but can I also use this to load css and js files from cloudfront and s3?

**Comment by joehoyle** [comment]
Hi @fahaadsheikh, S3-Uploads doesn't support doing that directly. To do so, you'd need to write quite a lot of custom functionality on top of S3-uploads to upload static assets to S3, and then handle the URL replacements yourself too.
