### ISSUE TITLE
Official Facebook Pixel 2.2.1 + Contact Form7 5.3 + S3uploads

### ISSUE THREAD

**Issue by greg-digit** [humanmade/S3-Uploads#467]
Official Facebook Pixel 2.2.1 + Contact Form7 5.3 + S3uploads
After a plugin update this morning there was a Fatal error.
- with all three plugins enabled (site crashes)
- Fatal error: Uncaught Error: Call to undefined function GuzzleHttp\_idn_uri_convert()
- /public_html/wp-content/plugins/s3-uploads/vendor/guzzlehttp/guzzle/src/Client.php on line 220

**Comment by rmccue** [comment]
This sounds like the Facebook Pixel plugin is attempting to use a different, incompatible version of Guzzle compared to the AWS SDK. It may be incompatible with the AWS SDK, and hence with S3 Uploads for that reason.

As this appears to be an issue with another plugin, closing this out. Feel free to reopen if you identify any bugs in S3 Uploads as a result of this.

Note also that we only provide [limited support for our open source plugins](https://engineering.hmn.md/projects/support/).
