### ISSUE TITLE
Processing uploaded zip files

### ISSUE THREAD

**Issue by WeAreHaus** [humanmade/S3-Uploads#468]
I get some errors from other plugins such as Elementor and wp-all-import that offer the possibility to upload zip files which is unzipped and processed. I think it has to do with the filesystem which returns `s3://path/to/file.zip` paths. Leading the php ZipArchive to look in the wrong place.

Is there any workaround for these type of files that are supposed to be handled with a local path after upload?

**Comment by joehoyle** [comment]
@WeAreHaus good question, I've run into similar issues whenever something is only compatible with (or assumed) the file path is a local-filesystem path. I think that's the case for ZipArchive, it's also true for Imagick. The workaround there is to download the file to the `tmp` DIR before passing to Imagick, see: https://github.com/humanmade/S3-Uploads/blob/master/inc/class-image-editor-imagick.php#L60

This does mean the plugin you are using will need the appropriate filters / actions to be able to do that, which might not be the case though.
