### ISSUE TITLE
Possible to lower the cost?

### ISSUE THREAD

**Issue by gitmko0** [humanmade/S3-Uploads#481]
Each time it's viewed in Media Upload section, it will call S3 instead of the CDN. possible to fix this and make the cost lowest possible? S3 is still very expensive being called to use like this.

**Comment by joehoyle** [comment]
@gitmko0 yes, you can use a CDN infant of S3. The is outside of the scope of this plugin, but you can then define S3 constants to set the public "bucket URL" to the CDN endpoint, see https://github.com/humanmade/S3-Uploads#url-rewrites
