### ISSUE TITLE
Sorry for asking, I have yet to check the script in detail. s3-uploads only take cares of /wp-content/uploads directory or...?

### ISSUE THREAD

**Issue by gitmko0** [humanmade/S3-Uploads#484]
Sorry for asking, I have yet to check the script in detail. 
s3-uploads only take cares of /wp-content/uploads directory or things that are media?

i'm using divi and /wp-content/et-cache/ <- will this also be in s3 using s3-uploads? caching folders should NOT be in s3.

how do i resolve this? should i put et-cache to public_html or... what's the best way forward?

**Comment by rmccue** [comment]
Please note our [support policy](https://engineering.hmn.md/projects/support/); we are unable to offer detailed support.

S3 Uploads only handles the upload directory; specifically, any uses of `wp_upload_dir()`. For any other directories, you'll need to handle these yourself in custom code.
