### ISSUE TITLE
Composer Dependencies

### ISSUE THREAD

**Issue by kirill-next** [humanmade/S3-Uploads#486]
Hey guys,

Take a look here:
https://github.com/humanmade/S3-Uploads/blob/d58519b20a8983d79c98b3595c1a00f413f894b7/inc/namespace.php#L7

If updating and installing dependencies on top dir level (i.e. project root) and assuming I do have AWS SDK installed but not anything else this local autoload will not be initialised and therefore dependencies will not be present.

This happened when we added the AWS SDK in our project without the rest of the dependencies S3-Uploads is using. This fired up 500 status warnings all over the place :)

**Comment by rmccue** [comment]
> This happened when we added the AWS SDK in our project without the rest of the dependencies S3-Uploads is using

The only dependencies of S3 Uploads are the AWS SDK and WordPress, so I'm not sure what issue you're hitting here. We install S3 Uploads from Composer on production sites without issue, and the bundled dependencies are really only for people installing S3 Uploads as a raw plugin.

What were the warnings you were seeing?

**Comment by kirill-next** [comment]
To be fair, we're using an older forked version of the plugin.
However, I did get the error that class Imagify\Optimizer was not found.

**Comment by rmccue** [comment]
We don't have any such file, so the issue is with the forked version. :)
