### ISSUE TITLE
verify and cp not behaving on new installation

### ISSUE THREAD

**Issue by stdbull** [humanmade/S3-Uploads#488]
Hello folks. I'm deploying S3-Uploads on a small web server running Wordpress on FreeBSD 11 and php 7.4 and had a couple of teething issues at the installation phase which I wanted to query with you. I installed the plugin with composer today and activated it. All good. I have an AWS IAM user with the required policy to access the bucket, and this is configured in my wp-config.php as:
```
define( 'S3_UPLOADS_BUCKET', 'my-bucket' );
define( 'S3_UPLOADS_REGION', 'my-region' );
define( 'S3_UPLOADS_KEY', 'XXXX' );
define( 'S3_UPLOADS_SECRET', 'YYYY' );
define( 'S3_UPLOADS_AUTOENABLE', false );
```
I can list and rm files just fine. Two issues I had when testing the installation are:
1. When performing a **verify** the operation is reported to succeed when it cannot (bucket was not public at the time).
2. When performing a **cp** the plugin reports `PHP Warning:  copy(): Unable to find the wrapper "s3" - did you forget to enable it when you configured PHP?`

I'm taking the installation step by step as I need to migrate data from the local file system to S3 prior to going live. That's the reason for having S3_UPLOADS_AUTOENABLE set to false.

So onto testing the installation using user www who has correct privs for the existing server...

**1.**
I started with my-bucket set to private.
I had **empty strings** for S3_UPLOADS_KEY and S3_UPLOADS_SECRET.
I ran the **verify** command expecting it to fail, but it produced:
```
# sudo -u www wp s3-uploads verify
Success: Looks like your configuration is correct.
Attempting to upload file /path/to/wp-content/uploads/1381375368.txt
File uploaded to S3 successfully.
Attempting to delete file. /path/to/wp-content/uploads/1381375368.txt
File deleted from S3 successfully.
```
Obviously I was a bit surprised by that.

After checking that my bucket was definitely not public, I made it public and tried again (still expecting it to fail because there was no policy or user being used by the plugin which had any privileges to access the bucket). I also commented out the delete of the test file, ie the delete line below was commented out in class-s3-uploads-wp-cli-command.php:
```
                // Delete the file off S3.
                WP_CLI::print_value( 'Attempting to delete file. ' . $s3_path );
                $delete = unlink( $s3_path );
```
Obviously the file deletion was flagged as an error, but the upload was still indicated as being ok.
Obviously there was no file created in the bucket either.

I then added valid values for S3_UPLOADS_KEY and S3_UPLOADS_SECRET and performed the same test, still with the file delete commented out. The file was **not uploaded** (checked with another S3 client and the AWS web interface).

So I conclude that the **verify** functionality has a problem.

**2.**
Continuing with valid values for S3_UPLOADS_KEY and S3_UPLOADS_SECRET I tried listing my bucket with **ls**. This worked fine. I tried deleting a file on the bucket with **rm**. That worked fine too. I tried copying a file on the local file system to the bucket with **cp**. That did not work. The file was not copied to the bucket and the plugin produced errors along the lines of what was reported in #289 and mentioned as being related to #100. So running either the following commands...

`sudo -u www wp s3-uploads cp ./bar.txt s3://my-bucket/foo.txt`
`sudo -u www wp s3-uploads cp /tried/full/path/to/bar.txt s3://my-bucket/foo.txt`

...produced:

`PHP Warning:  copy(): Unable to find the wrapper "s3" - did you forget to enable it when you configured PHP?`

It also reported:

`Success: Completed copy from /full/path/to/bar.txt to s3://my-bucket/foo.txt`

So I conclude that the **cp** command also has a problem.

Is there something wrong with the installation?
Basic read (**ls**) and write (**rm**) seem to work, but I'm concerned that something may impact the migration of data so I would like to understand these issues first, with emphasis on the failure of the **cp** command.

The plugin looks great and seems exactly what I need. Hopefully we can get to the bottom of these two questions.
Hope to hear from you soon.

Cheers,
--  Matt

**Comment by stdbull** [comment]
The **upload-directory** command seems to work, but it does not seem to need the name of the bucket in the destination (perhaps this is my misunderstanding). It does not upload the directory if I omit the trailing slash from the src (ie if I used 'testdir' there is nothing uploaded).
```
# ls -l testdir/
total 1
-rw-r--r--  1 www  www  0 Feb  4 16:21 foo.txt
```
`# sudo -u www wp s3-uploads upload-directory ./testdir s3://my-bucket/`

```
# sudo -u www wp s3-uploads ls                              
my-bucket/foo.txt
```
What is weird is if I do this...

` # sudo -u www wp s3-uploads upload-directory testdir/ s3://`

...I see:
```
# sudo -u www wp s3-uploads ls
s3:/foo.txt
```

I can use **cp** and have it not produce the PHP errors (remove the `s3://` URI and the name of the bucket in the destination) but it doesn't upload the file to S3 - it just copies it to the current directory on the server. But I think that's probably expected :-)

For example:
```
# sudo -u www wp s3-uploads cp ./bar.txt bob.txt
Success: Completed copy from ./bar.txt to bob.txt
```
It's not in the S3 bucket, but it exists locally.

The PHP errors are encountered if I use an `s3://` URI with anything.

Deleting a directory or file in the S3 bucket with **rm** works fine.

I feel like I'm missing a trick with the syntax, but can't figure what it is.
Is **cp** broken somehow?

**Comment by stdbull** [comment]
I turned on auto uploads tonight as a test and uploaded a 13MB size file to the media gallery. The file was created on S3 with the expected directory hierarchy, but it was zero bytes. Eventually, Wordpress obviously got tired of waiting and reported `Post-processing of the image failed likely because the server is busy or does not have enough resources. Uploading a smaller image may help. Suggested maximum size is 2500 pixels.`
I saw this mentioned in #457  
Refreshing things (S3 and in WP) never changed anything. The file remains on S3 as a 0 byte file.

So I don't know if this problem is related to the issues I saw with **cp**, or if there is another problem.
I'm in the UK and my S3 region is eu-west-2, so latency should be minimal.

If anyone has any thoughts on all this, I'd be grateful for any support.

**Comment by stdbull** [comment]
Ok, so the files do eventually appear in S3 in entirety. I obviously just need to wait longer :-)

**Comment by rmccue** [comment]
Hey @stdbull :)

The post-processing mentioned here is WP resizing the images into thumbnails, and then pushing those up to S3. If you have a lot of image sizes, this may take a while; additionally, large images are resized first to a slightly-less-large size, and then resized to the others.

We use [Tachyon](https://github.com/humanmade/tachyon) to handle image resizing, which means only the original is uploaded; this reduces the amount of work needed on upload.

Otherwise, I'm not sure why the files are _eventually_ appearing; there's nothing in WP or S3 Uploads that should be delaying this. This may be an eventual-consistency thing on AWS' side that you're seeing.

With regards to the CLI commands, it is definitely possible that those contain bugs; they're generally only used for quick debugging and verification, so they get a lot less eyes on them than the rest of the codebase.

**Comment by stdbull** [comment]
Thanks @rmccue 
The 'size of zero' thing is very odd. I was wanting to use **cp** to try and bottom out the upload issue I was having.
It's a shame it's not working as expected. As a result I've had to turn on S3_UPLOADS_AUTOENABLE.
It's not a big deal but it would be great if the **cp** command worked.

I tried the same upload test again now, only this time with a smaller (2MB) jpeg. But the behaviour is the same:

Add a 2MB file to the WP media lib.
A couple of seconds after uploading has completed:
  - Observe correct uploads/year/month/filename creation on S3
  - File uploads/year/month/filename shows on S3 as zero bytes.
20 mins later it's still 0 bytes.

I tried another test from a different S3 client (Forklift on MacOS) to push a larger 13MB jpeg to the same bucket while waiting for the 2MB file to change size.
The 13MB file _only showed up on S3 once the transfer was complete_ in Forklift. That took less than a minute.

So the zero bytes problem only seems related to the web server running S3 Uploads.
Is there a way that I can get some debug info out of the plugin to see what's going on?
Cheers.

**Comment by stdbull** [comment]
Ok, so the zero bytes thing is related to the IAM user policy S3 Uploads is using.
I've tried two policies - one that S3 Uploads recommends (via **generate-iam-policy**) and one that I've used with another basic S3 client (simple rw access). Both those policies results in a zero byte file when used by S3 Uploads (interestingly the simple rw S3 client policy is fine with a basic S3 client to get/put files in the same bucket).

I tested used another IAM user policy (Full S3 access) with S3 Uploads, and the 2MB file is created _very quickly_ on S3 after the WP upload completes. Super :-)

So I guess the zero bytes issue is specifically related to the policy.

One last question if you don't mind.. :-)
If I wanted to copy rather than upload directly to S3, is that a relative simple code change to make?
I think S3 Upload fits 95% of what I need to do, but I would like the ability to copy rather than upload directly to S3 on upload (maybe a new wp-config option?).
Also it would be excellent if it could trigger on new files being added to the uploads directory and upload them directly.
I know there are a few plugins out there that offer this, but they look a bit too fancy and try to do too much (I've tried two that just don't seem to work).
S3 Uploads is what I want to use. Hopefully I can make it work for me :-)

Cheers guys.

**Comment by rmccue** [comment]
Glad to hear you worked it out; we may need to change that default IAM policy if so.


>  If I wanted to copy rather than upload directly to S3, is that a relative simple code change to make?
>  Also it would be excellent if it could trigger on new files being added to the uploads directory and upload them directly.

S3 Uploads is designed to override WP's upload directory, so is not really designed for either of these use cases. For something like this, you may be better off rolling your own solution instead. As we don't need this functionality, we don't provide it in S3 Uploads (even as an option) [per our support policy](https://engineering.hmn.md/projects/support/). If there's any extension points (actions/filters) that would help you implement this though, we can add those.

**Comment by stdbull** [comment]
No worries. That's cool. I understand completely :-) I'll keep having a play around and see if I can come up with something.
I contemplated using [s3fs](https://github.com/s3fs-fuse/s3fs-fuse) in addition to S3 Uploads, to provide a 'facade' for other plugins (which are coded to expect a local file system) in order for them to perform their actions, eg a thumbnail generator plugin wouldn't know it was manipulating images on an s3 fs or a local fs. Then have all the thumbnail URLs rewritten to https://my-bucket.s3.amazonaws.com/uploads/xxx/yyy so they can be rendered in the browser. Just an idea... 

Mind you, it looks like I can use your WP [Tachyon plugin](https://github.com/humanmade/tachyon-plugin) to perform some level of customisation of the resized image that are able to get generated once the S3 upload is complete.
I'll have a read of those docs. It would be great if it allowed images of different sizes to be generated.
Is that possible? That's my last question :-)

Cheers.

**Comment by rmccue** [comment]
Tachyon dynamically resizes images from S3 based on the query parameters; we use it in combination with CloudFront to serve resized images handled by S3 Uploads. The Tachyon plugin specifically hooks into WP so that when WP inserts a resized image, it generates a Tachyon URL with the appropriate size parameters. You can also build those URLs directly yourself for more control if you need to.

(Specifically, it'll insert URLs like `https://your-tachyon-instance/2020/01/your_file.jpg?height=1024&width=800`)

**Comment by stdbull** [comment]
Right, but when you [previously](https://github.com/humanmade/S3-Uploads/issues/488#issuecomment-774000743) wrote:

> The post-processing mentioned here is WP resizing the images into thumbnails, and then pushing those up to S3. 

I don't see WP pushing anything else (eg the resized images it normally creates when an image is added to the media lib) up to S3. All I see on S3 is the image added to the media lib (which S3 Uploads puts on S3) and a scaled down image of that (e.g. 'name-scaled.jpg' which is generated after the upload to S3 has completed).

Is it expected that WP is able to generate resized thumbnails of the image added the media lib? I don't see how that can work because, for example, ImageMagick would need to operate on the image locally, but it doesn't exist locally - it exists only on S3.

 I'm still not entirely sure of the reason for the scaled image appearing in the bucket. You mentioned it's used to resize other images. Do you mean that it's used by Tachyon? That's fine if Tachyon is required in the end to end solution, but it seems unnecessary if Tachyon isn't required. Is it possible to turn off generation of the 'name-scaled.jpg' images that appear in the bucket?

**Comment by stdbull** [comment]
All done here. Thanks a lot for the inputs. Appreciated.

**Comment by rmccue** [comment]
> I don't see WP pushing anything else (eg the resized images it normally creates when an image is added to the media lib) up to S3.

Ah, perhaps it is not then. WP will usually generate these automatically, so you might have code elsewhere which is disabling this behaviour.

> Is it expected that WP is able to generate resized thumbnails of the image added the media lib? I don't see how that can work because, for example, ImageMagick would need to operate on the image locally, but it doesn't exist locally - it exists only on S3.

Technically, the resizing happens via WP's Image Editor classes, and S3 Uploads [contains an overridden version of this](https://github.com/humanmade/S3-Uploads/blob/master/inc/class-image-editor-imagick.php), which will download a temporary copy of the file to the temp directory to operate on.

> I'm still not entirely sure of the reason for the scaled image appearing in the bucket.

[This Make post lays out why it does this](https://make.wordpress.org/core/2019/10/09/introducing-handling-of-big-images-in-wordpress-5-3/); it's WP behaviour, rather than Tachyon. tl;dr: WP does an initial resize on upload to reduce the cost of generating future resized versions. This happens regardless of whether you're using Tachyon or not.
