### ISSUE TITLE
Disable S3 Uploads rerooting to be able to generate PDF invoices (WooCommerce)

### ISSUE THREAD

**Issue by jeremypetersen** [humanmade/S3-Uploads#489]
Hi,

One year ago I added a fix to my `functions.php` file to be able to disable S3 Uploads rerooting for the plugin [WooCommerce PDF Invoices & Packing Slips](https://wordpress.org/plugins/woocommerce-pdf-invoices-packing-slips/) to work :

```
// Disable S3 Uploads rerooting to be able to generate PDF invoices (WooCommerce).
public function changeInvoicePdfPath($tmp_base)
{
    if (class_exists('S3_Uploads') && is_callable(['S3_Uploads', 'get_instance'])) {
        // unregister S3 path override filters
        S3_Uploads::get_instance()->tear_down();
        // get unfiltered path
        $upload_dir = wp_upload_dir();
        if (!empty($upload_dir['error'])) {
            $tmp_base = false;
        } else {
            $upload_base = trailingslashit($upload_dir['basedir']);
            $tmp_base    = $upload_base.'wpo_wcpdf/';
        }
        // reboot S3 filters
        S3_Uploads::get_instance()->setup();
    }

    return $tmp_base;
}
```

It seems that this fix doesn't work anymore since I got this error using the invoices plugin :

```
Warning: require(): s3:// wrapper is disabled in the server configuration by allow_url_include=0 in /srv/app/wordpress/spalina/web/app/plugins/woocommerce-pdf-invoices-packing-slips/vendor/dompdf/dompdf/src/FontMetrics.php on line 140

Warning: require(s3://wp-spalina-fr/uploads/wpo_wcpdf_152b37308327eab1e668fdd3ccf711aa/fonts/dompdf_font_family_cache.php): failed to open stream: no suitable wrapper could be found in /srv/app/wordpress/spalina/web/app/plugins/woocommerce-pdf-invoices-packing-slips/vendor/dompdf/dompdf/src/FontMetrics.php on line 140

Fatal error: require(): Failed opening required 's3://wp-spalina-fr/uploads/wpo_wcpdf_152b37308327eab1e668fdd3ccf711aa/fonts/dompdf_font_family_cache.php' (include_path='.:/usr/share/php') in /srv/app/wordpress/spalina/web/app/plugins/woocommerce-pdf-invoices-packing-slips/vendor/dompdf/dompdf/src/FontMetrics.php on line 140
```

I think we can't even pass the if statement (`if (class_exists('S3_Uploads') && is_callable(['S3_Uploads', 'get_instance']))`). Did you change something in your class names ? Can you please help by providing the good way to reroot ?

Thanks in advance !

**Comment by rmccue** [comment]
As noted in the error, `allow_url_include` must be enabled. It appears your PHP configuration has changed to disallow this.

The class names have indeed changed in the development version available on GitHub, and the main class is now `S3_Uploads\Plugin`.

Please also note our [support policy](https://engineering.hmn.md/projects/support/) as we are unable to provide detailed support.
