### ISSUE TITLE
Undocumented functionality

### ISSUE THREAD

**Issue by spacedmonkey** [humanmade/S3-Uploads#49]
I noticed that the S3 Upload plugin has some functionality that is not documented in the readme.md. Is it possible to explain what the following defines do and what the impact, be it on functionality or performance. S3_UPLOADS_USE_LOCAL and S3_UPLOADS_DISABLE_REPLACE_UPLOAD_URL ?

Is it possible that functionality that might not be documented?

**Comment by joehoyle** [comment]
I added documentation for `S3_UPLOADS_USE_LOCAL` in https://github.com/humanmade/S3-Uploads#offline-development. `S3_UPLOADS_DISABLE_REPLACE_UPLOAD_URL` is currently internal
