### ISSUE TITLE
webp files not being generated with ewww + S3-Uploads

### ISSUE THREAD

**Issue by return-tosleep** [humanmade/S3-Uploads#490]
Facing issue when using https://wordpress.org/plugins/ewww-image-optimizer/ and S3-Uploads together. When S3-Uploads is disabled, ewww generates `.webp` images for each upload. But after enabling S3-Uploads the `.webp` images are not generated or available on S3.

**Comment by rmccue** [comment]
Hi @return-tosleep! Please note our [support policy](https://engineering.hmn.md/projects/support/); we're unable to assist with plugin compatibility issues, but if you identify any direct bugs in S3 Uploads, we're happy to look at fixing those. We don't use ewww at Human Made, so we can't offer advice on compatibility with it.

Closing this out for now, but feel free to comment further, or reopen if you identify any bugs in S3 Uploads causing this.
