### ISSUE TITLE
Allow the plugin to assume shared credentials instead of Access Keys

### ISSUE THREAD

**Issue by kibblerz** [humanmade/S3-Uploads#495]
For someone with dozens of websites to manage, this plugin allows an easier way to implement S3 Offloads without dealing with the hassle of a GUI plugin, which is great. 

But, there's no support for assuming shared credentials. This becomes an administration nightmare at scale, since Access Keys should be routinely rotated.

If anyone has any suggestions on how to best approach this, I will attempt to implement it myself and create a PR if needed.

**Comment by joehoyle** [comment]
See the readme https://github.com/humanmade/S3-Uploads, specifically:

```
// Or if using IAM instance profiles, you can use the instance's credentials:
define( 'S3_UPLOADS_USE_INSTANCE_PROFILE', true );
```
