### ISSUE TITLE
Stable release for private uploads?

### ISSUE THREAD

**Issue by joemcgill** [humanmade/S3-Uploads#502]
👋🏻 I've got a project where I'm wanting to swap out custom shimmed private uploads and make use of the functionality from #398, but it doesn't seem to be part of a tagged stable release yet, [based on this conversation](https://github.com/humanmade/S3-Uploads/pull/401#issuecomment-782300782) between @joehoyle and @goldenapples.

Is there a plan to tag a stable 2.X release with this, or should we plan to use the 3.0.0-alpha for now? If the latter, do you have a ~ETA for when a stable 3.0 release will be available to use, rather than an alpha version?

**Comment by joehoyle** [comment]
Hey @joemcgill,

So private uploads will not be in @2.X, so your best bet is to wait for a stable 3.0. I believe we have rolled 3.0 in the upcoming Altis 7 launch, so providing we don't find any blockers and need to rollback to 2.0, I think the release for that is planned around end of April.

**Comment by joemcgill** [comment]
Sounds good. Thanks for confirmation!
