### ISSUE TITLE
Possible to remove from  /uploads/ from path with CDN?

### ISSUE THREAD

**Issue by tomgreeEn** [humanmade/S3-Uploads#505]
Hi
I'm connecting via a CDN. So the path to a file is https://cdn.mysite.com/uploads/2020/07/logo.png

I'd like to remove 'uploads' so that the URL becomes https://cdn.mysite.com/2020/07/logo.png

I can point the CDN at /uploads to work with the above structure, but I'm not clear if there is a way to alter the rewrite rules to remove /uploads from the path at the WP end. 

Is this something that the plugin supports? 

Alternatively, is it possible to use a different string from 'uploads'?

Thanks

**Comment by joehoyle** [comment]
@tomgreeEn you should be able to do this by filtering the value of `wp_upload_dir()` as you would in WordPress without this plugin (to strip `/uploads/`). You can then set a custom hostname for the S3 Uploads via the `S3_UPLOADS_BUCKET_URL` constant (see https://github.com/humanmade/S3-Uploads#url-rewrites)

**Comment by tomgreeEn** [comment]
Great, thank you. 

If useful for anyone else finding this, this is the code I used to remove /uploads from the URL:

```
add_filter('upload_dir', 'grly_remove_uploads_subdir');

function grly_remove_uploads_subdir($dirs) {
	$dirs['baseurl'] = S3_UPLOADS_BUCKET_URL;
	$dirs['basedir'] = ABSPATH . 'wp-content'; // this would usually be wp-content/uploads
	$dirs['path'] = $dirs['basedir'] . $dirs['subdir'];
	$dirs['url'] = $dirs['baseurl'] . $dirs['subdir'];

	return $dirs;
}
```
