### ISSUE TITLE
Default Content Directory Incorrect

### ISSUE THREAD

**Issue by BrandonShutter** [humanmade/S3-Uploads#51]
Hey there.  I'm using [Bedrock] (https://github.com/roots/bedrock), and right now when I install and use this plugin, it automatically uploads the files into `/uploads` in `S3.`  This is ignoring my content directory I have declared previously.

    define('CONTENT_DIR', '/app');
    define('WP_CONTENT_DIR', $webroot_dir . CONTENT_DIR);
    define('WP_CONTENT_URL', WP_HOME . CONTENT_DIR);

I need this to upload them from `/app/uploads` instead of just `/uploads`

Right now I'm using `wp s3-uploads cp /uploads/ /app/uploads/` to upload, but all new images I'm uploading are incorrect.

**Comment by fklein-lu** [comment]
The plugin uses the Core `wp_upload_dir()` function to determine the directory in which the content is stored. It seems to me that the Core `UPLOADS` constant should be used to point to the directory of your choice.

Could you please try setting this constant and see whether this fixes the issue?

**Comment by rslnk** [comment]
@fklein-lu @BrandonShutter I'd like to re-open this issue. It seems that if the core `UPLOADS` is defined outside the `wp-content/` folder S3-Uploads doesn't pick it up. I'm also using [bedrock](https://roots.io/bedrock) setup, which put's WordPress in it's own subdirectory. However, I don't think that this is Bedrock issue. It looks like that any custom value defined in `UPLOADS` is ignored by the plugin.

I've tried the following options with no result:
`define( 'UPLOADS',  '' . 'media' );`
``define( 'UPLOADS',  'media' );``

**Comment by BrandonShutter** [comment]
I can no longer help debug this, I've moved on to using Delicious Brain's plugin and have had zero issues.

Brandon Shutter
