### ISSUE TITLE
Must be an instance of S3_Uploads\AWS\Command, instance of Aws\Command given

### ISSUE THREAD

**Issue by techypaul** [humanmade/S3-Uploads#513]
When running:

`wp s3-uploads upload-directory /var/www/wordpress/wp-content/uploads/ uploads --verbose`

I recieve:

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to S3_Uploads\WP_CLI_Command::S3_Uploads\{closure}() must be an instance of S3_Uploads\AWS\Command, instance of Aws\Command given, called in /var/www/wordpress/vendor/aws/aws-sdk-php/src/S3/Transfer.php on line 395 and defined in /var/www/wordpress/wp-content/plugins/s3-uploads/inc/class-wp-cli-command.php:209`

If I modify the line 209:

`'before'      => function ( AWS\Command $command ) {`
to
`'before'      => function ( Aws\Command $command ) {`

It works fine. I have used this tool before without issues. I am thinking this is a change in SDK possibly, but please advise?

**Comment by techypaul** [comment]
I realised v3 is released. I get this in composer show:

```
aws/aws-sdk-php                  3.180.0
humanmade/s3-uploads             3.0.0
```

If I set to v2 in composer, i.e.
`"humanmade/s3-uploads": ">=2.0 <3.0"`

I get:
```
aws/aws-sdk-php                  3.180.2
humanmade/s3-uploads             2.3.0
```

And everything is working. I will stick with v2 but given that it is the only change I am making, I leave this issue open as I don't understand the problem.

**Comment by iamlili** [comment]
Hi,

Came here to report this exact bug

I also just installed the latest:
```
aws/aws-sdk-php                                   3.183.10 
humanmade/s3-uploads                              3.0.0  
```

HOWEVER - this is what worked for me

changed
`'before' => function ( AWS\Command $command ) {`
to
`'before' => function ( \AWS\Command $command ) {`
