### ISSUE TITLE
Question: differences between v2 and v3?

### ISSUE THREAD

**Issue by oobi** [humanmade/S3-Uploads#539]
Hey thanks a bunch for the hard work put into this plugin! 

I was wondering if there was any available documentation or a change log to highlight differences between the 2.x and 3.x  builds? If we're currently running 2.x in production, is it worth upgrading to v3?

**Comment by grappler** [comment]
Looking the differences here: https://github.com/humanmade/S3-Uploads/compare/2.3.0...3.0.2

@joehoyle Are there breaking changes between v2 and v3?

**Comment by rmccue** [comment]
v3 was a backwards compatibility break as we switched to namespaces. There's no other significant changes, and no data migration or anything is needed.

We recommend keeping up-to-date in any case.
