### ISSUE TITLE
Can LS bucket but can not verify or upload

### ISSUE THREAD

**Issue by Kaboofa** [humanmade/S3-Uploads#54]
>php wp-cli.phar s3-uploads verify

```
Deprecated: Directive 'register_long_arrays' is deprecated in PHP 5.3 and greater in Unknown on line 0

Deprecated: Directive 'magic_quotes_gpc' is deprecated in PHP 5.3 and greater in Unknown on line 0
Attempting to upload file s3://site/uploads/178792104.jpg
Fatal error: Call to a member function headObject() on a non-object in /usr/local/www/site/www/wp-content/plugins/S3-Uploads/inc/class-s3-uploads-stream-wrapper.php on line 169
```

**Comment by fklein-lu** [comment]
I've looked through the code, and there doesn't seem to be a reason why these deprecated messages get thrown.

I'd propose that you look into the configuration of the server on which the code is running. If the error persists, please provide more details on how to produce the error, and with information about the stack on which the code is running.
