### ISSUE TITLE
Is it possible to offload only a few specific files or folders inside WordPress /Upload directory?

### ISSUE THREAD

**Issue by htmlswift** [humanmade/S3-Uploads#548]
Hello there, 

Is it possible to offload only a few specific files or folder inside WordPress /Upload directory?
Can you please let me know? and If there is a way, can you help with that?

I actually need to offload an Elementor form uploaded file to Amazon S3 Bucket. Currently it is getting saved to /Upload folder.

Thanks!

**Comment by joehoyle** [comment]
No, this is not possible, see https://github.com/humanmade/S3-Uploads/issues/432 and other previous issues.
