### ISSUE TITLE
Only offload new files or option to specify if it should go to S3

### ISSUE THREAD

**Issue by avblink** [humanmade/S3-Uploads#549]
Would be good to have an option to offload only newly uploaded files to s3.
Another good option would be to specify if the file should be uploaded to s3 or local server.

The use case for the last suggestion would be if user wants to upload large files to S3 because it generates a huge traffic when others try to download it.

Thank you

**Comment by rmccue** [comment]
We don't need this capability internally, so we aren't going to add this. We only add functionality to our plugins to support the use cases that we use; [see our support policy](https://engineering.hmn.md/projects/support/) for more information.
