### ISSUE TITLE
Browsing media library is quite slow

### ISSUE THREAD

**Issue by anugupta** [humanmade/S3-Uploads#55]
Browsing the media library is quite slow - the infinite scroll takes several seconds (between 5 and 15)  to load the next set of images.

Is this is necessary consequence of offloading images to S3, or might there be something messed up in my configuration (on the server or S3) ?

**Comment by joehoyle** [comment]
@anugupta s3 uploads shouldn't affect the load speed of the extra items into the media browser, however it's possible the images themselves loading is slower (the request to fetch the atachments list from WordPress versus the HTTP request for each image). 

If it's the speed of each image loading, then you might want to take a look at CloudFront or another CDN which could sit in front of amazon s3 to improve load times.
