### ISSUE TITLE
Editing / re-cropping source images after S3 upload

### ISSUE THREAD

**Issue by oobi** [humanmade/S3-Uploads#553]
We're using S3-Uploads and it's working really well for us. I've just recently discovered, however, that it's no longer possible to re-crop or edit images as they are no longer stored on the server. 

Is there an existing way to do this? We usually use the "crop thumbnails" plugin but I'm open to anything that works.
https://wordpress.org/plugins/crop-thumbnails/

I assume there would need to be some kind of intervention like re-downloading the image from S3, manipulating it then re-uploading. 

Has anyone managed to find a solution for this? I'd assume it's a fairly common problem when offloading media to any CDN? 

cheers,
Chris

**Comment by oobi** [comment]
Thanks again, Ryan - that link was busted though?

**Comment by rmccue** [comment]
Oh yeah, repo's private; here's [a gist of the same](https://gist.github.com/rmccue/55bb0e2d243a103b3230f69cc02f6c71)
