### ISSUE TITLE
Storing aws credentials in .env

### ISSUE THREAD

**Issue by LarkRiseMedia** [humanmade/S3-Uploads#555]
Would it not be safer if we were able to stop the credentials needed into an .env file as opposed to storing them in wp-config. As far as I can tell this is not the recommended way anywhere??

**Comment by rmccue** [comment]
S3 Uploads takes an unopinionated approach to how exactly you provide it with credentials; if you use environment variables, you may wish to use something like `define( 'S3_UPLOADS_KEY', getenv( 'HM_S3_UPLOADS_KEY' ) )`.

The recommended way of providing credentials on EC2 instances is to use instance profiles, which can then be automatically rotated via IAM.
