### ISSUE TITLE
issue on plugin usage, all configs set but had problem with region.

### ISSUE THREAD

**Issue by renzit** [humanmade/S3-Uploads#558]
I had the following issue:

PHP Parse error:  syntax error, unexpected '?' in /wp-content/plugins/s3-uploads/inc/class-plugin.php on line 244

wp-config.php

define( 'S3_UPLOADS_BUCKET', 'MYURL );
define( 'S3_UPLOADS_REGION', 'MY-REGION' );
define( 'S3_UPLOADS_KEY', 'MY_KEY' );
define( 'S3_UPLOADS_SECRET', 'MY_SECRET' );
define( 'S3_UPLOADS_USE_INSTANCE_PROFILE', false );
if ( is_readable( __DIR__ . '/vendor/autoload.php' ) ) {
  require_once __DIR__ . '/vendor/autoload.php';
}

any clue of what could be happening here?

**Comment by rmccue** [comment]
S3 Uploads requires PHP 7.4 minimum, this error indicators your version of PHP is too old.
