### ISSUE TITLE
Metadata when uploading to S3

### ISSUE THREAD

**Issue by jonathan88n** [humanmade/S3-Uploads#572]
Is there a way to send metadata from media files within WordPress to the S3 buckets?

**Comment by jonathan88n** [comment]
> Media metadata in WordPress is stored in the database rather than the filesystem generally, while EXIF metadata is embedded within image files directly. S3 Uploads does not change this behaviour; if you need different behaviour here, you'd need to write a custom plugin to implement it.

Thank you for your quick response. I noticed an item I used the S3-Uploads plugin for, had a Amazon S3 Metadata tag:

Type
System defined

Key
Content-Type

Value
text/plain

I was hoping to be able to add another metadata tag if possible to future uploaded items (not just images).

**Comment by rmccue** [comment]
Ah, for that, you can probably use the PutObject params filter: https://github.com/humanmade/S3-Uploads/blob/master/inc/class-stream-wrapper.php#L245-L252

**Comment by jonathan88n** [comment]
Are you able to give an example of adding just simple text alongside of Content-Type key-value pair?
For example:

S3-Upload a file via wordpress:

S3 Bucket has this metadata tags for that item:

Content-Type: text/plain
From: wordpressSite.domain.com

**Comment by rmccue** [comment]
I'm afraid we can't provide examples for extending S3 Uploads. Please see our support policy: https://engineering.hmn.md/projects/support/
