### ISSUE TITLE
Direct uploads

### ISSUE THREAD

**Issue by abazeed** [humanmade/S3-Uploads#578]
Does this plugin support the direct uploads to S3? So files will be sent and stored directly on the cloud skipping the local storage of the WordPress server.
I think this should utilize the pre-signed URLs to get a temporary link that the client browser will use to store the file on S3 directly.

**Comment by rmccue** [comment]
No, this is not currently supported by S3 Uploads.

**Comment by abazeed** [comment]
Any plans to add this feature to the plugin in the future? It's very useful and will enhance the performance of the plugin.

**Comment by rmccue** [comment]
There are no plans to add it at this stage, as we don't need this functionality. Feel free to fork the plugin and add it :)

**Comment by abazeed** [comment]
Thank you @joehoyle for the clarification. There's one plugin that supports direct uploads [Media Cloud](https://mediacloud.press/), but it's a huge plugin that supports many cloud services. I need one plugin that only supports S3. Thank you again!
