### ISSUE TITLE
Cannot use with S3 in Frankfurt Region (and China)

### ISSUE THREAD

**Issue by ergunozyurt** [humanmade/S3-Uploads#58]
Gives the error when you try to verify 

`PHP Warning:  The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. in /wp-content/plugins/S3-Uploads-master/lib/aws-sdk/Aws/S3/StreamWrapper.php on line 759`

It's related to "Signature Version 4" on Frankfurt and China regions

`In the China (Beijing) and EU (Frankfurt) regions, Amazon S3 supports only Signature Version 4, and AWS SDKs use this signature version to authenticate requests.`

for the help: http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html#specify-signature-version

**Comment by joehoyle** [comment]
@ergunozyurt can you refined the `S3_UPLOADS_REGION` region:

```PHP
define( 'S3_UPLOADS_REGION', 'eu-central-1' );
```
For example

**Comment by ergunozyurt** [comment]
hey thanks!

I've just figured and came to write same thing. 
Sorry to bother. 

Let me include this information to readme.
