### ISSUE TITLE
Support for uploading large files using multipart upload?

### ISSUE THREAD

**Issue by SeBsZ** [humanmade/S3-Uploads#602]
Thanks for this plugin. Right now, when I try to upload a size that's too large for my S3 provider, I get the following error:
```
Error executing "PutObject" on "https://xxx/wp-content/uploads/2022/09/85/6317611a32454/largefile.zip"; AWS HTTP error: Client error: `PUT https://xxx/wp-content/uploads/2022/09/85/6317611a32454/largefile.zip` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?><Error><Code>EntityTooLarge</Code><BucketName>xxx</BucketNa (truncated...)
 EntityTooLarge (client):  - <?xml version="1.0" encoding="UTF-8"?><Error><Code>EntityTooLarge</Code><BucketName>xxx</BucketName><RequestId>tx00000000000002ad271b5-006319afc8-265969b6-default</RequestId><HostId>265969b6-default-default</HostId></Error>
```

Are there plans to add Multipart upload support to this plugin? See https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html

Many thanks for your help

**Comment by joehoyle** [comment]
No plans, but would be willing to accept a PR!

**Comment by SeBsZ** [comment]
Thanks, will see what I can do. No promises.

**Comment by rmccue** [comment]
Closing this out as not planned, but if anyone wants to make a PR, please do!

**Comment by workcodework** [comment]
did anyone make a PR yet?
multipart upload sems to ideal for files sizes about 50mb
