### ISSUE TITLE
S3_Uploads plugin activation issue

### ISSUE THREAD

**Issue by ameeyswain** [humanmade/S3-Uploads#627]
Hi team, 
I am trying to update the plugin but it's throwing an error. We are using mu-plugins which has composer and has 'aws-sdk' package. Is there any work around to fix the issue ? 

`PHP Fatal error:  Uncaught Error: Class 'S3_Uploads\Plugin' not found in /wp-content/plugins/s3-uploads/inc/namespace.php:32
Stack trace:
#0 /wp-includes/class-wp-hook.php(308): S3_Uploads\init()
#1 /wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#2 /wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /wp-settings.php(486): do_action()
#4 /wp-config.php(247): require_once('/wp...')
#5 /wp-load.php(50): require_once('/wp...')
#6 /wp-admin/admin-ajax.php(22): require_once('/wp...')
#7 {main}`

Thanks
Ameey Kumar

**Comment by rmccue** [comment]
If you're providing aws-sdk from another plugin, S3 Uploads must be installed via Composer in order to generate the correct autoloader.

**Comment by ameeyswain** [comment]
I have been trying to fix it by using the mu-plugins composer package but getting the same error again and again. could you please help us by providing step by step process to resolve the issue.

my composer running here on this path: wp-content/mu-plugins/composer/vendor/autoload.php

thanks!

**Comment by rmccue** [comment]
Per [our support policy](https://engineering.hmn.md/projects/support/), we do not provide end-user support and cannot assist with debugging. If you're unable to debug this further yourself, consider an alternative solution like the excellent [WP Offload Media](https://deliciousbrains.com/wp-offload-media/).
