### ISSUE TITLE
Fix release folder name

### ISSUE THREAD

**Issue by hj-collab** [humanmade/S3-Uploads#638]
Hi,

WP CLI can easily install plugins from a Github repository. However, I noticed that there is an issue with your repository. The folder name and zip name in the release are currently set as "manualinstall" instead of "S3-Uploads".

I have observed that it is crucial for the plugin folder name to remain as "S3-Uploads" due to hardcoded references. Could you please ensure that the plugin folder name remains as "S3-Uploads" when creating a release?

This change will reduce the process from four steps (downloading the zip, extracting, renaming the folder, and activating) to a single WP CLI command. Thank you.

Best regards,

**Comment by rmccue** [comment]
Thanks for the issue! We're going to remove this installation method (see #644), so going to close this out.
