### ISSUE TITLE
Fatal error wp s3-uploads upload-directory

### ISSUE THREAD

**Issue by ndstyle** [humanmade/S3-Uploads#643]
Hi.

I downloaded, installed and configured the plugin following all steps. 

If I run the `wp s3-uploads verify` command it seems to work correctly giving me this message: File uploaded to S3 successfully and File deleted from S3 successfully.

If I run the `wp s3-uploads upload-directory` command I get the following error message:

`Fatal error: Declaration of Aws\S3\Transfer::promise() must be compatible with GuzzleHttp\Promise\PromisorInterface::promise(): GuzzleHttp\Promise\PromiseInterface in /vendor/aws/aws-sdk-php/src/S3/Transfer.php on line 149`

Can you help me solve the problem?

Thanks

Context:

- PHP 8.0.29
- s3-uploads version 3.0.7
- wordpress: 6.2.2

**Comment by ndstyle** [comment]
Hi.

Is there no one who can help me solve this error? 

Thanks

**Comment by rmccue** [comment]
We do not provide user support for S3 Uploads, and you'll need to debug any problems; see our support policy: https://engineering.hmn.md/projects/support/

If you're looking for a more user-oriented plugin, we suggest WP Offload Media by Delicious Brains. :)
