### ISSUE TITLE
Installation Failure by all methods. 

### ISSUE THREAD

**Issue by NKNdevs** [humanmade/S3-Uploads#670]
Initially tried to install by using git clone and then running composer install inside the plugin directory (S3-Uploads). I get two errors. 
```  Problem 1
    - Root composer.json requires phpunit/phpunit 7.5 -> satisfiable by phpunit/phpunit[7.5.0].
    - phpunit/phpunit 7.5.0 requires php ^7.1 -> your php version (8.2.18) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires pcov/clobber ^2.0 -> satisfiable by pcov/clobber[v2.0.0, v2.0.1, v2.0.2, v2.0.3].
    - pcov/clobber[v2.0.0, ..., v2.0.3] require ext-pcov ^1.0 -> it is missing from your system. Install or enable PHP's pcov extension.
 ```
 Initially tried to install by downloading the manual-install.zip and unzipping it. 

 I am running PHP 8.0. Composer picks up 8.2 (also installed on the machine). Have tried installing php-pcov at the system level. Not picked up. 
 
 Have looked at composer.json and see that phpunit and pcov/clobber are in the 'require-dev' section. Tried running with composer install --no-dev, but get the same errors. 
 
 Also tried installing with the manual-install.zip. Got a different set of errors there, but I see that method is depracated, and hasn't been updated since 3.0.3 anyway, so that's probably not advisable.

**Comment by rmccue** [comment]
> Initially tried to install by downloading the manual-install.zip and unzipping it.

It's unclear what errors you're actually hitting here, but please note that we don't offer detailed end-user support; see https://engineering.hmn.md/projects/support/ for our support policy.

The problems you're seeing from Composer are related to your system configuration; try setting the [platform setting](https://getcomposer.org/doc/06-config.md#platform) if Composer is getting your versions wrong. Again though, we won't be able to help with Composer usage.

If you're able to clearly identify a bug in S3 Uploads with reproducible steps, please feel free to reopen.

**Comment by NKNdevs** [comment]
Just to add ... I was able to get composer to run by doing the git clone command, and then replacing composer.json with this version from a fork
https://raw.githubusercontent.com/kresnasatya/S3-Uploads/update-dev-deps/composer.json
So possibly you might need to update that file with this version?
