### ISSUE TITLE
Trying to install the plugin with php8

### ISSUE THREAD

**Issue by kirsley** [humanmade/S3-Uploads#671]
We've been using manual installation as we used this plugin inside a docker. Now, when I even try to use compose install from within the cloned folder, it says 
  Problem 1
    - Root composer.json requires phpunit/phpunit 7.5 -> satisfiable by phpunit/phpunit[7.5.0].
    - phpunit/phpunit 7.5.0 requires php ^7.1 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires pcov/clobber ^2.0 -> satisfiable by pcov/clobber[v2.0.0, v2.0.1, v2.0.2, v2.0.3].
    - pcov/clobber[v2.0.0, ..., v2.0.3] require ext-pcov ^1.0 -> it is missing from your system. Install or enable PHP's pcov extension.

Is it not compatible yet with php 8 or higher?

**Comment by mellinger** [comment]
I think you're encountering the same problem as this user (and myself): https://github.com/humanmade/S3-Uploads/issues/670

The solve they posted at the end worked for me.

**Comment by kirsley** [comment]
yes, it worked thanks! I also had to add this in wp-config.php instead of what is shown in Readm file, as, for some reason, it wasn't trying to open the vendor folder in plugins path, but in root path
"require __DIR__ . '/wp-content/plugins/s3-uploads/vendor/autoload.php';"
