### ISSUE TITLE
Consider adding support for Git Updater and RepoMan

### ISSUE THREAD

**Issue by jessuppi** [humanmade/S3-Uploads#677]
Hello there,

Please consider adding support for Git Updater and RepoMan by adding these lines to your plugin header:

```
GitHub Plugin URI: humanmade/S3-Uploads
Primary Branch: master
```

Ref: https://github.com/humanmade/S3-Uploads/blob/master/s3-uploads.php

More info:

https://github.com/littlebizzy/repoman

**Comment by rmccue** [comment]
Our only officially supported installation mechanism is via Composer, we no longer support other mechanisms (see #644).
