### ISSUE TITLE
WP-CLI verify should respect s3_uploads_enabled()

### ISSUE THREAD

**Issue by dev169** [humanmade/S3-Uploads#78]
Minor quibble, `wp s3-uploads verify` doesn't check if we've actually enabled uploading to S3 and happily goes on testing the local filesystem. In `S3-Uploads/inc/class-s3-uploads-wp-cli-command.php` one could add on [line 18](https://github.com/humanmade/S3-Uploads/blob/master/inc/class-s3-uploads-wp-cli-command.php#L18):

```
if ( ! s3_uploads_enabled() ) {
    WP_CLI::error('Uploading to S3 disabled. Either set S3_UPLOADS_AUTOENABLE to True, or toggle via WP-CLI: wp s3-uploads enable');
    return;
}
```

**Comment by joehoyle** [comment]
This is intentional so you can verify it before activating it.
