### ISSUE TITLE
Avoid connecting unless needed

### ISSUE THREAD

**Issue by rmccue** [humanmade/S3-Uploads#8]
It takes a while to connect to S3 (can be up to 2s from the other side of the world), so we should avoid doing it unless needed.

This may require core to change, as `wp_upload_dir` right now calls `wp_mkdir_p` constantly, which is a gigantic pain.

cc @dd32

**Comment by joehoyle** [comment]
I thought I put in a really nasty hack to ignore the `wp_upload_dir` call, but maybe that broke.

**Comment by joehoyle** [comment]
Hmm, so creating the `s3` client object shouldn't cause any network activity, not sure why you would have been seeing that. We have to init the client object to register the streamwrapper also.

**Comment by joehoyle** [comment]
I did some more testing, and can confirm a connection is not made to s3 unless you are specifically trying to stat files etc.
