### ISSUE TITLE
plugin collisions when other plugin uses guzzle

### ISSUE THREAD

**Issue by ivoba** [humanmade/S3-Uploads#80]
hi,
i just experienced an error similar to this https://github.com/humanmade/S3-Uploads/issues/24 

```
'Guzzle\Common\Exception\RuntimeException' with message 'Guzzle\Http\CachingEntityBody supports only SEEK_SET and SEEK_CUR seek operation
```

although i was already on the latest version where the hack for guzzle was applied:  
https://github.com/humanmade/S3-Uploads/commit/a9db1096ca5a042386073851c96061102265b309

it turned out i was also using sendgrid-email-delivery-simplified plugin and a composer loaded guzzle which was somehow replacing your shipped guzzle and the hack had no effect anymore.

just to let you know.

**Comment by joehoyle** [comment]
Ahh, good point - the AWS SDK hacks we have is super nasty, so I'd really like to remove them - let's keep this open as a reminder of the downsides.

**Comment by joshuajabbour** [comment]
Bummer, these hacks are making it so we can't use this plugin...

**Comment by joehoyle** [comment]
All AWS SDK hacks have been removed. It's also recommended to installed S3 Uploads using composer, so all your plugins can share Guzzle instances.
