### ISSUE TITLE
Only deletes cropped files and original file and not the extra original image-sizes

### ISSUE THREAD

**Issue by jmslbam** [humanmade/S3-Uploads#82]
Steps to reproduce:

1. Upload image
2. Crop this image so it has the original file with it's image sizes and the new cropped version and it's image sizes.
3. Delete the image.

Result:
> This deletes the original upload, the cropped-original and the cropped image-sizes, but leaves the original image-sizes files.

**Comment by jmslbam** [comment]
At this moment I even have an issue with the fact that it leaves all the image-sizes, even of those not cropped.

**Comment by rslnk** [comment]
Yep, I've tested this today and can confirm that deleting an image via WP Media Library only deletes that original image, but **does not delete** additionally generated sizes from S3 bucket.

**Comment by metadan** [comment]
I'm seeing this also

**Comment by joehoyle** [comment]
This was fixed in #87
