### ISSUE TITLE
Custom Post Type Throwing HTTP Error

### ISSUE THREAD

**Issue by ehoanshelt** [humanmade/S3-Uploads#83]
Post and Page post types work fine and upload successfully. When using customer post type however, I'm seeing a HTTP Error pop up. Error Logs show no issue for me to debug further.

If you need me to provide any addtional information, plese let me know.

**Comment by joehoyle** [comment]
Is this when you try to uploads to the media library from within editing a post in the CPT?

Could you paste the response from the HTTP request (use Chrome dev tools to inspect the XHR request in the upload).

Thanks!

**Comment by ehoanshelt** [comment]
This case is when I try uploading an image in the Featured Images of the CPT.

Here is the HTTP request:

```
POST http:/domain.com/wp-admin/async-upload.php 500 (Internal Server Error)
```

I dsiabled the plugin and upload worked fine.

**Comment by ehoanshelt** [comment]
Update:
It appears to upload the image to S3 and set everything right in the database for new images on the CPT.

**Comment by ehoanshelt** [comment]
The issue is resolved. It was an issue with how some custom code was using ImageMagik.
