### ISSUE TITLE
Temporary files aren't cleaned up if an error occurs during saving

### ISSUE THREAD

**Issue by rmccue** [humanmade/S3-Uploads#84]
I suspect this is the cause of our inode exhaustion: in the image editor code, we grab a temp file name and tell WP to write to it, but [never clean it up if there's an error](https://github.com/humanmade/S3-Uploads/blob/3c23f4af12c6e47bf317e0409c1c2f9f7ce6ccee/inc/class-s3-uploads-image-editor-imagick.php#L18-L26). If WP hits an error after creating the file but before finishing, then the file will stick around.

In our case, the file is getting created but not written to, so I strongly suspect `fopen` is returning false in `WP_Image_Editor::make_image`, but this value is never checked in the Imagick `_save` method. Still not sure entirely what's happening there, but we should be running the `unlink` just in case anyway.

**Comment by rmccue** [comment]
> Still not sure entirely what's happening there

Oh, actually, `tempnam` actually creates the file, so that explains how the file is being created.

**Comment by joehoyle** [comment]
Fixed in #86
