### ISSUE TITLE
Can we get the latest features added (WP cli enhancements, etc.) into a tagged 0.9.1 release?

### ISSUE THREAD

**Issue by jackdpeterson** [humanmade/S3-Uploads#91]
I would like to get these installable as soon as possible without needing to set composer to a specific commit hash. I'm not sure what all is on your radar for new features ... but the CLI enhancements are enough IMHO to get a minor release tag in there.

Cheers!

**Comment by joehoyle** [comment]
Latest release is up at https://github.com/humanmade/S3-Uploads/releases/tag/v1.1.0!
