### ISSUE TITLE
wp plugin activate does not work for PHP 5.3.9

### ISSUE THREAD

**Issue by treehau5** [humanmade/S3-Uploads#93]
Hello, 

The error I was receiving when attempting to follow the directions was 

`PHP Parse error:  syntax error, unexpected '[' in /usr/share/www/wp/wp-content/plugins/S3-Uploads/inc/class-s3-uploads-wp-cli-command.php on line 417`

The only reason I am bringing it up here is because wp-cli's docs claim to support PHP down to 5.3.2, so this may cause issues for other people attempting to try this out!

When I upgraded to PHP 5.4, it worked as expected. 

I am new to PHP so apologies in advance. Would it be helpful for me to submit a PR to document the minimum PHP requirement somewhere, or were you all expecting it to work with 5.3.x?

**Comment by joehoyle** [comment]
Ahh yes, the new required version is 5.5

**Comment by mpolichette** [comment]
This should be in the README.md
