### ISSUE TITLE
S3_UPLOADS_REGION now required constant

### ISSUE THREAD

**Issue by tcrsavage** [humanmade/S3-Uploads#96]
Potentially going to cause issues on HM hosted stacks where plugin is updated but constants not yet defined. 

@joehoyle looks like this came in last week but there's nothing in place to set this yet on our hosting systems.

**Comment by joehoyle** [comment]
Hmm I _thought_ it was, however this is on the master branch anyway, the latest stable release doesn't have this. I was hoping that the region was auto discovered via the instance policy (like the secret and key) but maybe I'm wrong on that.

**Comment by chrisvanpatten** [comment]
Yeah we noticed a bunch of breakage on our sites because of this. Fortunately we test before deploying so it's not the end of the world, but it could be an issue for others.

**Comment by joehoyle** [comment]
So, unfortunately this was required by the SDK update, now we are doing actual release numbers we'll have changelogs too in the future to notify people of breaking changes. Sorry about that!
